CREATE INDEX IDX_EVENTTYPES1 ON EVENTTYPES (ELEMENT);
CREATE INDEX IDX_DEPLPROP_DEPL ON JBPM4_DEPLOYPROP (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP1 ON JBPM4_DEPLOYPROP (OBJNAME_, KEY_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP2 ON JBPM4_DEPLOYPROP (STRINGVAL_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP3 ON JBPM4_DEPLOYPROP (KEY_);
CREATE INDEX IDX_EXEC_INSTANCE ON JBPM4_EXECUTION (INSTANCE_);
CREATE INDEX IDX_EXEC_PARENT ON JBPM4_EXECUTION (PARENT_);
CREATE INDEX IDX_EXEC_SUBPI ON JBPM4_EXECUTION (SUBPROCINST_);
CREATE INDEX IDX_EXEC_SUPEREXEC ON JBPM4_EXECUTION (SUPEREXEC_);
CREATE INDEX IDX_JBPM4_EXECUTION1 ON JBPM4_EXECUTION (PROCDEFID_);
CREATE INDEX IDX_HACTI_HPROCI ON JBPM4_HIST_ACTINST (HPROCI_);
CREATE INDEX IDX_HTI_HTASK ON JBPM4_HIST_ACTINST (HTASK_);
CREATE INDEX IDX_HDET_HACTI ON JBPM4_HIST_DETAIL (HACTI_);
CREATE INDEX IDX_HDET_HPROCI ON JBPM4_HIST_DETAIL (HPROCI_);
CREATE INDEX IDX_HDET_HTASK ON JBPM4_HIST_DETAIL (HTASK_);
CREATE INDEX IDX_HDET_HVAR ON JBPM4_HIST_DETAIL (HVAR_);
CREATE INDEX IDX_JBPM4_HIST_PROCINST1 ON JBPM4_HIST_PROCINST (PROCDEFID_);
CREATE INDEX IDX_HSUPERT_SUB ON JBPM4_HIST_TASK (SUPERTASK_);
CREATE INDEX IDX_HVAR_HPROCI ON JBPM4_HIST_VAR (HPROCI_);
CREATE INDEX IDX_HVAR_HTASK ON JBPM4_HIST_VAR (HTASK_);
CREATE INDEX IDX_JBPM4_HIST_VAR_1 ON JBPM4_HIST_VAR (PROCINSTID_, VARNAME_, VALUE_);
CREATE INDEX IDX_GROUP_PARENT ON JBPM4_ID_GROUP (PARENT_);
CREATE INDEX IDX_MEM_GROUP ON JBPM4_ID_MEMBERSHIP (GROUP_);
CREATE INDEX IDX_MEM_USER ON JBPM4_ID_MEMBERSHIP (USER_);
CREATE INDEX IDX_JOBDUEDATE ON JBPM4_JOB (DUEDATE_);
CREATE INDEX IDX_JOBLOCKEXP ON JBPM4_JOB (LOCKEXPTIME_);
CREATE INDEX IDX_JOBRETRIES ON JBPM4_JOB (RETRIES_);
CREATE INDEX IDX_JOB_CFG ON JBPM4_JOB (CFG_);
CREATE INDEX IDX_JOB_EXE ON JBPM4_JOB (EXECUTION_);
CREATE INDEX IDX_JOB_PRINST ON JBPM4_JOB (PROCESSINSTANCE_);
CREATE INDEX IDX_LOB_DEPLOYMENT ON JBPM4_LOB (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_PARTICIPATION1 ON JBPM4_PARTICIPATION (TASK_, TYPE_, USERID_);
CREATE INDEX IDX_PART_TASK ON JBPM4_PARTICIPATION (TASK_);
CREATE INDEX IDX_SWIMLANE_EXEC ON JBPM4_SWIMLANE (EXECUTION_);
CREATE INDEX IDX_JBPM4_TASK1 ON JBPM4_TASK (ASSIGNEE_);
CREATE INDEX IDX_TASK_SUPERTASK ON JBPM4_TASK (SUPERTASK_);
CREATE INDEX IDX_JBPM4_VARIABLE1 ON JBPM4_VARIABLE (CLASS_, KEY_, STRING_VALUE_);
CREATE INDEX IDX_VAR_EXECUTION ON JBPM4_VARIABLE (EXECUTION_);
CREATE INDEX IDX_VAR_EXESYS ON JBPM4_VARIABLE (EXESYS_);
CREATE INDEX IDX_VAR_LOB ON JBPM4_VARIABLE (LOB_);
CREATE INDEX IDX_VAR_TASK ON JBPM4_VARIABLE (TASK_);
CREATE INDEX IDX_OC_JBPM5EXT_PROCDEF_EXT1 ON OC_JBPM5EXT_PROCDEF_EXTENSION (PROCESS_ID);
CREATE INDEX IDX_OC_JPDL4EXT_PROCDEF_EXT1 ON OC_JPDL4EXT_PROCDEF_EXTENSION (PROCESS_DEFINITION_KEY, PROCESS_DEFINITION_VERSION);
CREATE INDEX IDX_OC_PERMISSION1 ON OC_PERMISSION (PERMISSION_TARGET, PERMISSION_ACTION);

ALTER TABLE CFG_DEPENDENCY ADD CONSTRAINT FKB6719226DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DB901B50 FOREIGN KEY (RESOURCE_TYPE) REFERENCES CFG_RESOURCE_TYPE (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE_PARAM ADD CONSTRAINT FK7A56567745CA4CB9 FOREIGN KEY (RESOURCE) REFERENCES CFG_RESOURCE (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D572C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D5736B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE EVENTTYPES ADD CONSTRAINT FKB0E5621F7665489A FOREIGN KEY (INSTANCEID) REFERENCES JBPM5_PROCINST_INFO (INSTANCEID);

ALTER TABLE JBPM4_DEPLOYPROP ADD CONSTRAINT FK_DEPLPROP_DEPL FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_INSTANCE FOREIGN KEY (INSTANCE_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUBPI FOREIGN KEY (SUBPROCINST_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUPEREXEC FOREIGN KEY (SUPEREXEC_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HACTI_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HTI_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HACTI FOREIGN KEY (HACTI_) REFERENCES JBPM4_HIST_ACTINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HVAR FOREIGN KEY (HVAR_) REFERENCES JBPM4_HIST_VAR (DBID_);

ALTER TABLE JBPM4_HIST_TASK ADD CONSTRAINT FK_HSUPERT_SUB FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_ID_GROUP ADD CONSTRAINT FK_GROUP_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_GROUP FOREIGN KEY (GROUP_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_USER FOREIGN KEY (USER_) REFERENCES JBPM4_ID_USER (DBID_);

ALTER TABLE JBPM4_JOB ADD CONSTRAINT FK_JOB_CFG FOREIGN KEY (CFG_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_LOB ADD CONSTRAINT FK_LOB_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_SWIMLANE FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_SWIMLANE ADD CONSTRAINT FK_SWIMLANE_EXEC FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SUPERTASK FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SWIML FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXECUTION FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXESYS FOREIGN KEY (EXESYS_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_LOB FOREIGN KEY (LOB_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD78EF5F064 FOREIGN KEY (ATTACHEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD7F21826D9 FOREIGN KEY (TASKDATA_ATTACHMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_BOOL_EXPR ADD CONSTRAINT FK3690AAF6AFB75F7D FOREIGN KEY (ESCALATION_CONSTRAINTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0B2FF04688 FOREIGN KEY (ADDEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0BB35E68F5 FOREIGN KEY (TASKDATA_COMMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C27ABEB8A FOREIGN KEY (DEADLINES_ENDDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C684BACA3 FOREIGN KEY (DEADLINES_STARTDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_ESCALATION ADD CONSTRAINT FK8459BF49C7A04C70 FOREIGN KEY (DEADLINE_ESCALATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A2162DFB4 FOREIGN KEY (NOTIFICATION_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A3330F6D9 FOREIGN KEY (DEADLINE_DOCUMENTATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A5EEBB6D9 FOREIGN KEY (REASSIGNMENT_DOCUMENTATION_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A69B21EE8 FOREIGN KEY (TASK_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A8046A239 FOREIGN KEY (NOTIFICATION_DOCUMENTATION_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A98B62B FOREIGN KEY (TASK_NAMES_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AB2FA6B18 FOREIGN KEY (TASK_SUBJECTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AD488CEEB FOREIGN KEY (NOTIFICATION_NAMES_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AF952CEE4 FOREIGN KEY (NOTIFICATION_SUBJECTS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_N10N ADD CONSTRAINT FKA36CB2B53E0890B FOREIGN KEY (ESCALATION_NOTIFICATIONS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A91F7B912A FOREIGN KEY (EMAILHEADERS_ID) REFERENCES JBPM5_HT_MAILNHDR (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A98EE05A12 FOREIGN KEY (JBPM5_HT_N10N_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_REASSIGNMENT ADD CONSTRAINT FK11824F4A5C17EE0 FOREIGN KEY (ESCALATION_REASSIGNMENTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_SUBTASK_STRATEGY ADD CONSTRAINT FK8C53C08136B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD396CE1EF3A FOREIGN KEY (ACTUALOWNER_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD399E619A0 FOREIGN KEY (CREATEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD39F213F8B5 FOREIGN KEY (TASKINITIATOR_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JB_JOB_TYPE_PARAM ADD CONSTRAINT FKB413F6F165EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB ADD CONSTRAINT FK9447C66465EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB_PARAM ADD CONSTRAINT FK673EE6F2D83EF726 FOREIGN KEY (SCHEDULED_JOB) REFERENCES JB_SCHEDULED_JOB (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1D46DC060 FOREIGN KEY (USER_TO) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1F1695C8F FOREIGN KEY (USER_FROM) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE02C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE09C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E9C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE OC_COMMON_USER ADD CONSTRAINT FK940943B41BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_CUSTOM_PAGE ADD CONSTRAINT FK9CCD5CB24CB60E09 FOREIGN KEY (PAGE_TYPE) REFERENCES OC_PAGE_TYPE (CODE);

ALTER TABLE OC_EXT_ENT2ENT_FLD_EXPR ADD CONSTRAINT FK51B13C1ACA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY ADD CONSTRAINT FKEC84FB0CF0ECEDE4 FOREIGN KEY (EXTERNAL_SYSTEM) REFERENCES OC_EXT_SYSTEM (ID);

ALTER TABLE OC_EXT_ENTITY2ENTITY ADD CONSTRAINT FK641E3609BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607B027AA58 FOREIGN KEY (EXTERNAL_ENTITY_REFERENCE) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836D2DDA4D17 FOREIGN KEY (EXTERNAL_ENTITY_FIELD) REFERENCES OC_EXT_ENTITY_FIELD (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836DCA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENT_ID2ID ADD CONSTRAINT FKF5665DB5CA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69A12F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69AFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D1958112F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D19581F1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_JBPM5EXT_ATTRIBUTE ADD CONSTRAINT FK2B5A04A93572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_PROCESS_VARIABLE ADD CONSTRAINT FKE07A5F9F3572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VALIDATION ADD CONSTRAINT FKFC6F0FC03572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833EAF2F98 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JBPM5EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JBPM5REPO_PROCEXT_RSRC ADD CONSTRAINT FK9B6B8DBEE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_PROC_RESOURCE ADD CONSTRAINT FKF19E98FFE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_RESOURCE ADD CONSTRAINT FK971FA4E6567B3CB3 FOREIGN KEY (DEPLOYMENT) REFERENCES OC_JBPM5REPO_DEPLOYMENT (ID);

ALTER TABLE OC_JBPM5_TASK_VAR ADD CONSTRAINT FKA4BF6AF7928994C4 FOREIGN KEY (TASK) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE OC_JPDL4EXT_ATTRIBUTE ADD CONSTRAINT FKC6148E6350B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_PROCESS_VARIABLE ADD CONSTRAINT FK9B1E50A550B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VALIDATION ADD CONSTRAINT FKC8A5E5FA50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D27F42577 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JPDL4EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_PERMISSION ADD CONSTRAINT FK8686E11AF1EBAB7 FOREIGN KEY (PERMISSION_CATEGORY) REFERENCES OC_PERMISSION_CATEGORY (ID);

ALTER TABLE OC_QUERY ADD CONSTRAINT FK2836DA9D59C34F46 FOREIGN KEY (QUERY_TYPE) REFERENCES OC_QUERY_TYPE (ID);

ALTER TABLE OC_QUERY_FIELD ADD CONSTRAINT FKCF48B4D86A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_QUERY_PARAM ADD CONSTRAINT FKCFD22C6B6A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D133F526F7 FOREIGN KEY (MASTER_QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D1A985BF25 FOREIGN KEY (ENGINE) REFERENCES OC_REPORT_ENGINE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_SECURITY_GROUP ADD CONSTRAINT FK77A5DE8BDBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E4551BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E455DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TYPED_PRINCIPAL_PERMISSION ADD CONSTRAINT FK3DA89080FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USERPROFILE_PARAM ADD CONSTRAINT FKF9E5E2E1F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C5612F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C564DD86731 FOREIGN KEY (TENANT_USER) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C568C6EA467 FOREIGN KEY (TENANT_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E42C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E436B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C22C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C236B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D52C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D536B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFF2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFFE17E130F FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE RTM_ENTITY_DEFINITION ADD CONSTRAINT FKAE4EB63BED0054E FOREIGN KEY (CODE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK6243006039AA7BD0 FOREIGN KEY (FILTER_VALUE_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK62430060F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B170CE9EC6 FOREIGN KEY (PARENT_PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B1F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_OPERATION ADD CONSTRAINT FK6AAD977FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_ENTITY_VALIDATOR ADD CONSTRAINT FKC56CCD6AF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C2389DA9B FOREIGN KEY (PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C238C53A FOREIGN KEY (ENTITY_PARENT_FIELD) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF8F8EA10 FOREIGN KEY (DATA_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E083419AF1 FOREIGN KEY (FIELD_DEFINITION) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E0F919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_MENU_ITEM ADD CONSTRAINT FK147B8FFC08A43F7 FOREIGN KEY (PARENT) REFERENCES RTM_MENU_ITEM (CODE);