/*  Generators or sequences */
CREATE SEQUENCE ATTACHMENT_ID_SEQ;
CREATE SEQUENCE BOOLEANEXPR_ID_SEQ;
CREATE SEQUENCE COMMENT_ID_SEQ;
CREATE SEQUENCE CONTENT_ID_SEQ;
CREATE SEQUENCE DEADLINE_ID_SEQ;
CREATE SEQUENCE EMAILNOTIFHEAD_ID_SEQ;
CREATE SEQUENCE ERM_SEQUENCE start 10987689;
CREATE SEQUENCE ESCALATION_ID_SEQ;
CREATE SEQUENCE HIBERNATE_SEQUENCE start 40105962;
CREATE SEQUENCE I18NTEXT_ID_SEQ start 3492058;
CREATE SEQUENCE NOTIFICATION_ID_SEQ;
CREATE SEQUENCE OC_JBPM5_TASK_TX_TXID_SEQ start 2;
CREATE SEQUENCE OC_JBPM5_TIMER_INFO_SEQ start 7726954;
CREATE SEQUENCE REASSIGNMENT_ID_SEQ;
CREATE SEQUENCE SESSIONINFO_ID_SEQ start 355416;
CREATE SEQUENCE WORKITEMINFO_ID_SEQ start 3498180;


/* Table: CFG_ARTIFACT, Owner: SYSDBA */
CREATE TABLE CFG_ARTIFACT (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        VERSION BIGINT NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLED SMALLINT,
        INSTALL_LOG text,
PRIMARY KEY (ID));

/* Table: CFG_DEPENDENCY, Owner: SYSDBA */
CREATE TABLE CFG_DEPENDENCY (ID BIGINT NOT NULL,
        DEPENDENCY_CODE VARCHAR(255) NOT NULL,
        DEPENDENCY_VERSION BIGINT NOT NULL,
        ARTIFACT BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE (ID BIGINT NOT NULL,
        PATH VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        INSTALL_ORDER BIGINT NOT NULL,
        RESOURCE_TYPE BIGINT NOT NULL,
        ARTIFACT BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_PARAM, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_PARAM (ID BIGINT NOT NULL,
        PARAM_VALUE VARCHAR(255) NOT NULL,
        PARAM_NAME VARCHAR(255) NOT NULL,
        RESOURCE BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_TYPE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_TYPE (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLER VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: DELEGATION_DELEGATES, Owner: SYSDBA */
CREATE TABLE DELEGATION_DELEGATES (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: ERMS_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERMS_EXTLINK (ID BIGINT NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID BIGINT NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERMS_EXTLINK PRIMARY KEY (ID));

/* Table: ERMS_FILTERED, Owner: SYSDBA */
CREATE TABLE ERMS_FILTERED (ID BIGINT NOT NULL,
        SEARCHID BIGINT);

/* Table: ERMS_SAVED_FILTER, Owner: SYSDBA */
CREATE TABLE ERMS_SAVED_FILTER (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT NOT NULL,
        USER_ID BIGINT,
        NAME VARCHAR(250) NOT NULL,
        XMLDATA oid NOT NULL,
CONSTRAINT PK_ERMS_SAVED_FILTER PRIMARY KEY (ID));

/* Table: ERM_ADDRESSEEDOC, Owner: SYSDBA */
CREATE TABLE ERM_ADDRESSEEDOC (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        INTCONTRAGENT SMALLINT,
        ADDRESSEE BIGINT,
        INTADDRESSEE BIGINT,
        RECIPIENT VARCHAR(255),
        INTRECIPIENT BIGINT,
        DELIVERYKIND BIGINT,
        DATEDELIVERY TIMESTAMP,
CONSTRAINT PK_ERM_ADDRESSEEDOC PRIMARY KEY (ID));

/* Table: ERM_AGENTREQUEST, Owner: SYSDBA */
CREATE TABLE ERM_AGENTREQUEST (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        AGENTTYPE BIGINT,
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN BIGINT,
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        DOCDATE TIMESTAMP,
        COMMENTS VARCHAR(255),
        RESULT BIGINT,
        USERREQUEST BIGINT,
        SHORTTITLE VARCHAR(255),
        KPP BIGINT,
CONSTRAINT PK_ERM_AGENTREQUEST PRIMARY KEY (ID));

/* Table: ERM_AGENTTYPE, Owner: SYSDBA */
CREATE TABLE ERM_AGENTTYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_AGENTTYPE PRIMARY KEY (ID));

/* Table: ERM_ASUDINTEGRATIONRULE, Owner: SYSDBA */
CREATE TABLE ERM_ASUDINTEGRATIONRULE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(255),
        TASKPROCESSORNAME VARCHAR(255),
        TASKNAME VARCHAR(255),
        JBPMPROCESS BIGINT,
        COMMANDELEXPRESSION VARCHAR(1024),
        TASKTYPE BIGINT,
        SKIPEXPRESSION VARCHAR(1024),
CONSTRAINT PK_ERM_ASUDINTEGRATIONRULE PRIMARY KEY (ID));

/* Table: ERM_BIN_CONTENT, Owner: SYSDBA */
CREATE TABLE ERM_BIN_CONTENT (ID BIGINT NOT NULL,
        CONTENT_ID BIGINT NOT NULL,
        CONTENT_VER INTEGER NOT NULL,
        MODIFIED_BY VARCHAR(255),
        LAST_MODIFIED TIMESTAMP,
        IS_ACTUAL SMALLINT,
        SIGNED SMALLINT,
        SIGN_DATE TIMESTAMP,
        SIGN_AUTHOR VARCHAR(255),
        MIMETYPE VARCHAR(255),
        ENCODING VARCHAR(255),
        FILENAME VARCHAR(255),
        SIGN_ALGORITHM VARCHAR(255),
CONSTRAINT PK_ERM_BIN_CONTENT PRIMARY KEY (ID));

/* Table: ERM_BOARD, Owner: SYSDBA */
CREATE TABLE ERM_BOARD (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CHAIRMAN BIGINT,
        SECRETARY BIGINT,
        ANAME VARCHAR(255),
        CODE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
CONSTRAINT PK_ERM_BOARD PRIMARY KEY (ID));

/* Table: ERM_CONTRAGENT, Owner: SYSDBA */
CREATE TABLE ERM_CONTRAGENT (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        AGENTTYPE BIGINT,
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN BIGINT,
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        active SMALLINT,
        SHORTTITLE VARCHAR(255),
        KPP BIGINT,
CONSTRAINT PK_ERM_CONTRAGENT PRIMARY KEY (ID));

/* Table: ERM_DELEGATION, Owner: SYSDBA */
CREATE TABLE ERM_DELEGATION (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EMPLOYER BIGINT,
        DELEGAT BIGINT,
        PROCESS BIGINT,
        USERTASK BIGINT,
        ADDTASK SMALLINT,
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        active SMALLINT,
CONSTRAINT PK_ERM_DELEGATION PRIMARY KEY (ID));

/* Table: ERM_DELIVERYKIND, Owner: SYSDBA */
CREATE TABLE ERM_DELIVERYKIND (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DELIVERYKIND PRIMARY KEY (ID));

/* Table: ERM_DOCKIND, Owner: SYSDBA */
CREATE TABLE ERM_DOCKIND (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
        INDEXKIND VARCHAR(16),
        APPROVAL SMALLINT,
        BOARD SMALLINT,
        active SMALLINT,
CONSTRAINT PK_ERM_DOCKIND PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERING, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERING (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ORGUNIT BIGINT,
        BOARD BIGINT,
        DOCTYPE BIGINT,
        DOCKIND BIGINT,
        PERIOD BIGINT,
        PREFIX VARCHAR(255),
        POSTFIX VARCHAR(255),
CONSTRAINT PK_ERM_DOCNUMBERING PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERSEQ, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERSEQ (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODCODE VARCHAR(10),
        NEXTNUMBER BIGINT,
CONSTRAINT PK_ERM_DOCNUMBERSEQ PRIMARY KEY (ID));

/* Table: ERM_DOCRELATED, Owner: SYSDBA */
CREATE TABLE ERM_DOCRELATED (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOC BIGINT,
        ANAME BIGINT,
        SOURCEDOC BIGINT,
CONSTRAINT PK_ERM_DOCRELATED PRIMARY KEY (ID));

/* Table: ERM_DOCSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_DOCSTATUS (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DOCSTATUS PRIMARY KEY (ID));

/* Table: ERM_DOCTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTEMPLATE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ANAME VARCHAR(255),
        DOCKIND BIGINT,
        ORGUNIT BIGINT,
        file BIGINT,
        LINK VARCHAR(255),
CONSTRAINT PK_ERM_DOCTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_DOCTYPE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(5),
        ANAME VARCHAR(255),
        INDEXTYPE VARCHAR(16),
CONSTRAINT PK_ERM_DOCTYPE PRIMARY KEY (ID));

/* Table: ERM_DOCUMENT, Owner: SYSDBA */
CREATE TABLE ERM_DOCUMENT (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        BRANCH BIGINT,
        STATUS BIGINT,
        DOCTYPE BIGINT,
        DOCKIND BIGINT,
        NUMBER VARCHAR(255),
        REGDATE TIMESTAMP,
        OUTNUMBER VARCHAR(255),
        INTCONTRAGENT SMALLINT,
        ASUD VARCHAR(255),
        AGENT BIGINT,
        AGENTREQUEST BIGINT,
        INAUTHOR VARCHAR(255),
        INTCORRESPONDENT BIGINT,
        BOARD BIGINT,
        AUTHOR BIGINT,
        SUBJECT VARCHAR(1024),
        DELIVERYKIND BIGINT,
        NOMENCLATURE BIGINT,
        REGISTRATOR BIGINT,
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        NEEDAGREEMENT SMALLINT,
        SIGNER BIGINT,
        ARCHIVE SMALLINT,
        OUTDATE TIMESTAMP,
        ORIGINAL SMALLINT,
        STORAGE BIGINT,
        TRANSFERDATE TIMESTAMP,
        CLERKNOTE VARCHAR(1024),
        CREATEDATE TIMESTAMP,
        SUPERVISOR BIGINT,
CONSTRAINT PK_ERM_DOCUMENT PRIMARY KEY (ID));

/* Table: ERM_DOCUSER, Owner: SYSDBA */
CREATE TABLE ERM_DOCUSER (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCUSER BIGINT,
CONSTRAINT PK_ERM_DOCUSER PRIMARY KEY (ID));

/* Table: ERM_ENTITYEVENT, Owner: SYSDBA */
CREATE TABLE ERM_ENTITYEVENT (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        EVENTDATE TIMESTAMP,
        EVENTTYPE VARCHAR(80),
        ANAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        EVENTUSER BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
CONSTRAINT PK_ERM_ENTITYEVENT PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ANAME VARCHAR(255),
        TEMPLATEOWNER BIGINT,
        COMMON SMALLINT,
        TEMPLATELEVEL BIGINT,
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATEITEM, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATEITEM (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EXECUTANT BIGINT,
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATEITEM PRIMARY KEY (ID));

/* Table: ERM_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERM_EXTLINK (ID BIGINT NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID BIGINT NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_EXTLINK PRIMARY KEY (ID));

/* Table: ERM_FAVORITES, Owner: SYSDBA */
CREATE TABLE ERM_FAVORITES (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        FAVORITE BIGINT,
CONSTRAINT PK_ERM_FAVORITES PRIMARY KEY (ID));

/* Table: ERM_FILE, Owner: SYSDBA */
CREATE TABLE ERM_FILE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        file BIGINT,
        FILETYPE BIGINT,
        NOTE VARCHAR(255),
        USERREF BIGINT,
        DOCUMENT BIGINT,
CONSTRAINT PK_ERM_FILE PRIMARY KEY (ID));

/* Table: ERM_FILETYPE, Owner: SYSDBA */
CREATE TABLE ERM_FILETYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ANAME VARCHAR(255),
        DEFAULTFILE SMALLINT,
CONSTRAINT PK_ERM_FILETYPE PRIMARY KEY (ID));

/* Table: ERM_FOLDER, Owner: SYSDBA */
CREATE TABLE ERM_FOLDER (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ENTITY_TYPE VARCHAR(80),
        TENANT_ID BIGINT,
        PARENT_ID BIGINT,
        SORT_INDEX INTEGER,
        LBORDER BIGINT,
        RBORDER BIGINT,
        QUERY_DESC BIGINT,
CONSTRAINT PK_ERM_FOLDER PRIMARY KEY (ID));

/* Table: ERM_LINKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_LINKTYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_LINKTYPE PRIMARY KEY (ID));

/* Table: ERM_LISTNUMBER, Owner: SYSDBA */
CREATE TABLE ERM_LISTNUMBER (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCID BIGINT,
        REGNUMBER VARCHAR(255),
        REF BIGINT,
CONSTRAINT PK_ERM_LISTNUMBER PRIMARY KEY (ID));

/* Table: ERM_NOMENCLATURE, Owner: SYSDBA */
CREATE TABLE ERM_NOMENCLATURE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PARENTNOMENCLATURE BIGINT,
        INDEXFIELD VARCHAR(255),
        TITLE VARCHAR(255),
        AMOUNT BIGINT,
        LIFESTORAGE VARCHAR(255),
        ORGUNIT BIGINT,
        COMMENT VARCHAR(255),
        active SMALLINT,
        ARTICLE VARCHAR(255),
        CHILDACCESS SMALLINT,
CONSTRAINT PK_ERM_NOMENCLATURE PRIMARY KEY (ID));

/* Table: ERM_NOTE, Owner: SYSDBA */
CREATE TABLE ERM_NOTE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        NOTEINDEX BIGINT,
        REPLYTO BIGINT,
        TEXT VARCHAR(2048),
        CREATEDATE TIMESTAMP,
        USERNOTE BIGINT,
        STATUS VARCHAR(255),
CONSTRAINT PK_ERM_NOTE PRIMARY KEY (ID));

/* Table: ERM_ORGTYPE, Owner: SYSDBA */
CREATE TABLE ERM_ORGTYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ORGTYPE PRIMARY KEY (ID));

/* Table: ERM_ORGUNIT, Owner: SYSDBA */
CREATE TABLE ERM_ORGUNIT (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(10),
        ANAME VARCHAR(255),
        PARENTUNIT BIGINT,
        DESCRIPTION VARCHAR(255),
        active SMALLINT,
        SHORTNAME VARCHAR(25),
        INDEXCASE VARCHAR(255),
        ORGTYPE BIGINT,
        MANAGER BIGINT,
        UNITPATH VARCHAR(255),
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        CFO BIGINT,
CONSTRAINT PK_ERM_ORGUNIT PRIMARY KEY (ID));

/* Table: ERM_PERIOD, Owner: SYSDBA */
CREATE TABLE ERM_PERIOD (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_PERIOD PRIMARY KEY (ID));

/* Table: ERM_PERIODICTASK, Owner: SYSDBA */
CREATE TABLE ERM_PERIODICTASK (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODTEXT VARCHAR(255),
        PERIODTYPE BIGINT,
        DAYNUMBER BIGINT,
        DOCUMENT BIGINT,
        TASKOWNER BIGINT,
        AUTHOR BIGINT,
        CONTROLDAYS BIGINT,
        TASK VARCHAR(1024),
        EXECUTOR BIGINT,
        STARTDATE TIMESTAMP,
        FINISHDATE TIMESTAMP,
        NEXTSTART TIMESTAMP,
        LASTSTART TIMESTAMP,
        ISACTIVE SMALLINT,
CONSTRAINT PK_ERM_PERIODICTASK PRIMARY KEY (ID));

/* Table: ERM_PERM, Owner: SYSDBA */
CREATE TABLE ERM_PERM (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT NOT NULL,
        PERM_ACTION VARCHAR(80) NOT NULL,
        PRINCIPAL_UID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_PERM PRIMARY KEY (ID));

/* Table: ERM_PFM, Owner: SYSDBA */
CREATE TABLE ERM_PFM (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        PARENTUNIT BIGINT,
        BE BIGINT,
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
CONSTRAINT PK_ERM_PFM PRIMARY KEY (ID));

/* Table: ERM_PROCESS, Owner: SYSDBA */
CREATE TABLE ERM_PROCESS (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        PROCESSKEY VARCHAR(80),
        ANAME VARCHAR(256),
CONSTRAINT PK_ERM_PROCESS PRIMARY KEY (ID));

/* Table: ERM_ROLE, Owner: SYSDBA */
CREATE TABLE ERM_ROLE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ROLE PRIMARY KEY (ID));

/* Table: ERM_STAGE, Owner: SYSDBA */
CREATE TABLE ERM_STAGE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE BIGINT,
        ANAME VARCHAR(15),
CONSTRAINT PK_ERM_STAGE PRIMARY KEY (ID));

/* Table: ERM_TASK, Owner: SYSDBA */
CREATE TABLE ERM_TASK (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASKSUBJECT VARCHAR(255),
        TASK VARCHAR(2048),
        EXECUTOR BIGINT,
        STATUS BIGINT,
        AUTHOR BIGINT,
        SUPERVISOR BIGINT,
        CREATEDATE TIMESTAMP,
        CANCELREASON VARCHAR(255),
        CONTROLDATE TIMESTAMP,
        TASKACTIVE SMALLINT,
        TASKACTUAL SMALLINT,
        REFTASK BIGINT,
        DOCBASE VARCHAR(255),
        file BIGINT,
        NEEDREPORT SMALLINT,
        ADATE TIMESTAMP,
        TASKTYPE BIGINT,
        FILES BIGINT,
        PARENTTASK BIGINT,
        ANUMBER VARCHAR(16),
        TASKTEXT VARCHAR(1024),
        ISDONE SMALLINT,
        DOCUMENT BIGINT,
        STAGE BIGINT,
        NOTE VARCHAR(1024),
        STARTDATE TIMESTAMP,
        RESULTDATE TIMESTAMP,
        GETDATE TIMESTAMP,
CONSTRAINT PK_ERM_TASK PRIMARY KEY (ID));

/* Table: ERM_TASKDELEGATED, Owner: SYSDBA */
CREATE TABLE ERM_TASKDELEGATED (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASK BIGINT,
CONSTRAINT PK_ERM_TASKDELEGATED PRIMARY KEY (ID));

/* Table: ERM_TASKREPORT, Owner: SYSDBA */
CREATE TABLE ERM_TASKREPORT (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        REPORT VARCHAR(2048),
        REPORTDATE TIMESTAMP,
        ACCEPTED SMALLINT,
        NOTE VARCHAR(1024),
        NOTEDATE TIMESTAMP,
        NOTEUSER BIGINT,
        DOCUMENT BIGINT,
CONSTRAINT PK_ERM_TASKREPORT PRIMARY KEY (ID));

/* Table: ERM_TASKSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_TASKSTATUS (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ANAME VARCHAR(255),
        CODE VARCHAR(16),
CONSTRAINT PK_ERM_TASKSTATUS PRIMARY KEY (ID));

/* Table: ERM_TASKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_TASKTYPE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        REPORT SMALLINT,
        PREF VARCHAR(16),
CONSTRAINT PK_ERM_TASKTYPE PRIMARY KEY (ID));

/* Table: ERM_USER, Owner: SYSDBA */
CREATE TABLE ERM_USER (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        SURNAME VARCHAR(255),
        FIRSTNAME VARCHAR(255),
        PATRONYMIC VARCHAR(255),
        LOGIN VARCHAR(255),
        ANAME VARCHAR(255),
        ORGUNIT BIGINT,
        JOBNAME VARCHAR(255),
        EMAIL VARCHAR(255),
        TABNUMBER VARCHAR(255),
        DISMISSED SMALLINT,
        DELEGAT BIGINT,
        USERREF BIGINT,
        INDEXUSER VARCHAR(16),
        PHONE VARCHAR(255),
        ALLOWEDDOCSOFUNIT BIGINT,
        ORGUNITNAME VARCHAR(255),
        SSOLOGIN VARCHAR(255),
        PARENTORGUNIT BIGINT,
        NOTE VARCHAR(255),
CONSTRAINT PK_ERM_USER PRIMARY KEY (ID));

/* Table: ERM_USERROLE, Owner: SYSDBA */
CREATE TABLE ERM_USERROLE (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ROLE BIGINT,
CONSTRAINT PK_ERM_USERROLE PRIMARY KEY (ID));

/* Table: ERM_USERTASK, Owner: SYSDBA */
CREATE TABLE ERM_USERTASK (ID BIGINT NOT NULL,
        FOLDER_ID BIGINT,
        ERM_OWNER BIGINT,
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ANAME VARCHAR(256),
        PROCESS BIGINT,
CONSTRAINT PK_ERM_USERTASK PRIMARY KEY (ID));

/* Table: EVENTTYPES, Owner: SYSDBA */
CREATE TABLE EVENTTYPES (INSTANCEID BIGINT NOT NULL,
        ELEMENT VARCHAR(255));

/* Table: JBPM4_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYMENT (DBID_ BIGINT NOT NULL,
        NAME_ text,
        TIMESTAMP_ BIGINT,
        STATE_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_DEPLOYPROP, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYPROP (DBID_ BIGINT NOT NULL,
        DEPLOYMENT_ BIGINT,
        OBJNAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        STRINGVAL_ VARCHAR(255),
        LONGVAL_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_EXECUTION, Owner: SYSDBA */
CREATE TABLE JBPM4_EXECUTION (DBID_ BIGINT NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ACTIVITYNAME_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        HASVARS_ SMALLINT,
        NAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        ID_ VARCHAR(255),
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        HISACTINST_ BIGINT,
        PARENT_ BIGINT,
        INSTANCE_ BIGINT,
        SUPEREXEC_ BIGINT,
        SUBPROCINST_ BIGINT,
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_),
UNIQUE (ID_));

/* Table: JBPM4_HIST_ACTINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_ACTINST (DBID_ BIGINT NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        HPROCI_ BIGINT,
        TYPE_ VARCHAR(255),
        EXECUTION_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ BIGINT,
        TRANSITION_ VARCHAR(255),
        NEXTIDX_ INTEGER,
        HTASK_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_DETAIL, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_DETAIL (DBID_ BIGINT NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USERID_ VARCHAR(255),
        TIME_ TIMESTAMP,
        HPROCI_ BIGINT,
        HPROCIIDX_ INTEGER,
        HACTI_ BIGINT,
        HACTIIDX_ INTEGER,
        HTASK_ BIGINT,
        HTASKIDX_ INTEGER,
        HVAR_ BIGINT,
        HVARIDX_ INTEGER,
        MESSAGE_ text,
        OLD_STR_ VARCHAR(255),
        NEW_STR_ VARCHAR(255),
        OLD_INT_ INTEGER,
        NEW_INT_ INTEGER,
        OLD_TIME_ TIMESTAMP,
        NEW_TIME_ TIMESTAMP,
        PARENT_ BIGINT,
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_PROCINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_PROCINST (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        KEY_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ BIGINT,
        STATE_ VARCHAR(255),
        ENDACTIVITY_ VARCHAR(255),
        NEXTIDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_TASK (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        EXECUTION_ VARCHAR(255),
        OUTCOME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        STATE_ VARCHAR(255),
        CREATE_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ BIGINT,
        NEXTIDX_ INTEGER,
        SUPERTASK_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_VAR, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_VAR (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        PROCINSTID_ VARCHAR(255),
        EXECUTIONID_ VARCHAR(255),
        VARNAME_ VARCHAR(255),
        VALUE_ VARCHAR(255),
        HPROCI_ BIGINT,
        HTASK_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_GROUP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_GROUP (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        NAME_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        PARENT_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_MEMBERSHIP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_MEMBERSHIP (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USER_ BIGINT,
        GROUP_ BIGINT,
        NAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_USER, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_USER (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PASSWORD_ VARCHAR(255),
        GIVENNAME_ VARCHAR(255),
        FAMILYNAME_ VARCHAR(255),
        BUSINESSEMAIL_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_JOB, Owner: SYSDBA */
CREATE TABLE JBPM4_JOB (DBID_ BIGINT NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        DUEDATE_ TIMESTAMP,
        STATE_ VARCHAR(255),
        ISEXCLUSIVE_ SMALLINT,
        LOCKOWNER_ VARCHAR(255),
        LOCKEXPTIME_ TIMESTAMP,
        EXCEPTION_ text,
        RETRIES_ INTEGER,
        PROCESSINSTANCE_ BIGINT,
        EXECUTION_ BIGINT,
        CFG_ BIGINT,
        SIGNAL_ VARCHAR(255),
        EVENT_ VARCHAR(255),
        REPEAT_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_LOB, Owner: SYSDBA */
CREATE TABLE JBPM4_LOB (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        BLOB_VALUE_ oid,
        DEPLOYMENT_ BIGINT,
        NAME_ text,
PRIMARY KEY (DBID_));

/* Table: JBPM4_PARTICIPATION, Owner: SYSDBA */
CREATE TABLE JBPM4_PARTICIPATION (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        GROUPID_ VARCHAR(255),
        USERID_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        TASK_ BIGINT,
        SWIMLANE_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_PROPERTY, Owner: SYSDBA */
CREATE TABLE JBPM4_PROPERTY (KEY_ VARCHAR(255) NOT NULL,
        VERSION_ INTEGER NOT NULL,
        VALUE_ VARCHAR(255),
PRIMARY KEY (KEY_));

/* Table: JBPM4_SWIMLANE, Owner: SYSDBA */
CREATE TABLE JBPM4_SWIMLANE (DBID_ BIGINT NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        EXECUTION_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_TASK (DBID_ BIGINT NOT NULL,
        CLASS_ CHAR(1) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        DESCR_ text,
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        FORM_ VARCHAR(255),
        PRIORITY_ INTEGER,
        CREATE_ TIMESTAMP,
        DUEDATE_ TIMESTAMP,
        PROGRESS_ INTEGER,
        SIGNALLING_ SMALLINT,
        EXECUTION_ID_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        HASVARS_ SMALLINT,
        SUPERTASK_ BIGINT,
        EXECUTION_ BIGINT,
        PROCINST_ BIGINT,
        SWIMLANE_ BIGINT,
        TASKDEFNAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_VARIABLE, Owner: SYSDBA */
CREATE TABLE JBPM4_VARIABLE (DBID_ BIGINT NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        KEY_ VARCHAR(255),
        CONVERTER_ VARCHAR(255),
        HIST_ SMALLINT,
        EXECUTION_ BIGINT,
        TASK_ BIGINT,
        LOB_ BIGINT,
        DATE_VALUE_ TIMESTAMP,
        DOUBLE_VALUE_ DOUBLE PRECISION,
        CLASSNAME_ VARCHAR(255),
        LONG_VALUE_ BIGINT,
        STRING_VALUE_ VARCHAR(255),
        TEXT_VALUE_ text,
        EXESYS_ BIGINT,
PRIMARY KEY (DBID_));

/* Table: JBPM5_HT_ATTACHMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ATTACHMENT (ID BIGINT NOT NULL,
        NAME VARCHAR(255),
        ACCESSTYPE INTEGER,
        CONTENTTYPE VARCHAR(255),
        ATTACHEDAT TIMESTAMP,
        ATTACHMENT_SIZE INTEGER,
        ATTACHMENTCONTENTID BIGINT NOT NULL,
        ATTACHEDBY_ID VARCHAR(255),
        TASKDATA_ATTACHMENTS_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_BOOL_EXPR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_BOOL_EXPR (ID BIGINT NOT NULL,
        TYPE VARCHAR(255),
        EXPRESSION text,
        ESCALATION_CONSTRAINTS_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_COMMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_COMMENT (ID BIGINT NOT NULL,
        TEXT text,
        ADDEDAT TIMESTAMP,
        ADDEDBY_ID VARCHAR(255),
        TASKDATA_COMMENTS_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_CONTENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_CONTENT (ID BIGINT NOT NULL,
        CONTENT oid,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_DEADLINE, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_DEADLINE (ID BIGINT NOT NULL,
        DEADLINE_DATE TIMESTAMP,
        ESCALATED SMALLINT NOT NULL,
        DEADLINES_ENDDEADLINE_ID BIGINT,
        DEADLINES_STARTDEADLINE_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_ESCALATION, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ESCALATION (ID BIGINT NOT NULL,
        NAME VARCHAR(255),
        DEADLINE_ESCALATION_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_I18N_TEXT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_I18N_TEXT (ID BIGINT NOT NULL,
        LANGUAGE VARCHAR(255),
        TEXT text,
        TASK_DESCRIPTIONS_ID BIGINT,
        TASK_SUBJECTS_ID BIGINT,
        TASK_NAMES_ID BIGINT,
        REASSIGNMENT_DOCUMENTATION_ID BIGINT,
        NOTIFICATION_DESCRIPTIONS_ID BIGINT,
        NOTIFICATION_SUBJECTS_ID BIGINT,
        NOTIFICATION_NAMES_ID BIGINT,
        NOTIFICATION_DOCUMENTATION_ID BIGINT,
        DEADLINE_DOCUMENTATION_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_MAILNHDR (ID BIGINT NOT NULL,
        LANGUAGE VARCHAR(255),
        REPLYTOADDRESS VARCHAR(255),
        FROMADDRESS VARCHAR(255),
        SUBJECT VARCHAR(255),
        BODY text,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N (DTYPE VARCHAR(31) NOT NULL,
        ID BIGINT NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ESCALATION_NOTIFICATIONS_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N_JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR (JBPM5_HT_N10N_ID BIGINT NOT NULL,
        EMAILHEADERS_ID BIGINT NOT NULL,
        MAPKEY VARCHAR(255) NOT NULL,
PRIMARY KEY (JBPM5_HT_N10N_ID, MAPKEY),
UNIQUE (EMAILHEADERS_ID));

/* Table: JBPM5_HT_ORG_ENTITY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ORG_ENTITY (DTYPE VARCHAR(31) NOT NULL,
        ID VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_REASSIGNMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_REASSIGNMENT (ID BIGINT NOT NULL,
        ESCALATION_REASSIGNMENTS_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_SUBTASK_STRATEGY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_SUBTASK_STRATEGY (DTYPE VARCHAR(100) NOT NULL,
        ID BIGINT NOT NULL,
        NAME VARCHAR(255),
        TASK_ID BIGINT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_TASK, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_TASK (ID BIGINT NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ALLOWEDTODELEGATE VARCHAR(255),
        STATUS VARCHAR(255),
        PREVIOUSSTATUS INTEGER,
        CREATEDON TIMESTAMP,
        ACTIVATIONTIME TIMESTAMP,
        EXPIRATIONTIME TIMESTAMP,
        SKIPABLE SMALLINT NOT NULL,
        WORKITEMID BIGINT NOT NULL,
        PROCESSINSTANCEID BIGINT NOT NULL,
        DOCUMENTACCESSTYPE INTEGER,
        DOCUMENTTYPE VARCHAR(255),
        DOCUMENTCONTENTID BIGINT NOT NULL,
        OUTPUTACCESSTYPE INTEGER,
        OUTPUTTYPE VARCHAR(255),
        OUTPUTCONTENTID BIGINT NOT NULL,
        FAULTNAME VARCHAR(255),
        FAULTACCESSTYPE INTEGER,
        FAULTTYPE VARCHAR(255),
        FAULTCONTENTID BIGINT NOT NULL,
        PARENTID BIGINT NOT NULL,
        PROCESSID VARCHAR(255),
        PROCESSKEY VARCHAR(255),
        PROCESSSESSIONID INTEGER NOT NULL,
        TASKINITIATOR_ID VARCHAR(255),
        CREATEDBY_ID VARCHAR(255),
        ACTUALOWNER_ID VARCHAR(255),
        OPTLOCK INTEGER,
        ARCHIVED SMALLINT,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (ID));

/* Table: JBPM5_PROCINST_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_PROCINST_INFO (INSTANCEID BIGINT NOT NULL,
        OPTLOCK INTEGER,
        PROCESSID VARCHAR(255),
        STARTDATE TIMESTAMP,
        LASTREADDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        STATE INTEGER NOT NULL,
        PROCESSINSTANCEBYTEARRAY oid,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (INSTANCEID));

/* Table: JBPM5_SESSION_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO (ID INTEGER NOT NULL,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY oid,
        CLUSTERNODENAME VARCHAR(80),
PRIMARY KEY (ID));

/* Table: JBPM5_SESSION_INFO_SAVED, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO_SAVED (ID INTEGER,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY oid,
        CLUSTERNODENAME VARCHAR(80));

/* Table: JBPM5_WORKITEM_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_WORKITEM_INFO (WORKITEMID BIGINT NOT NULL,
        OPTLOCK INTEGER,
        NAME VARCHAR(255),
        CREATIONDATE TIMESTAMP,
        PROCESSINSTANCEID BIGINT NOT NULL,
        STATE BIGINT NOT NULL,
        WORKITEMBYTEARRAY oid,
PRIMARY KEY (WORKITEMID));

/* Table: JB_JOB_TYPE, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ACTION VARCHAR(255) NOT NULL,
        FIRST_DATE_EXPRESSION VARCHAR(255) NOT NULL,
        PERIOD_EXPRESSION VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: JB_JOB_TYPE_PARAM, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE_PARAM (ID BIGINT NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        VALUE_EXPRESSION VARCHAR(255),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB (ID BIGINT NOT NULL,
        START_DATE TIMESTAMP,
        ACTION VARCHAR(255) NOT NULL,
        JOB_KEY VARCHAR(255) NOT NULL,
        PERIOD_VALUE BIGINT,
        LAST_ERROR VARCHAR(1024),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB_PARAM, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB_PARAM (ID BIGINT NOT NULL,
        STRING_VALUE VARCHAR(255),
        CODE VARCHAR(255) NOT NULL,
        DOUBLE_VALUE DOUBLE PRECISION,
        DATE_VALUE TIMESTAMP,
        SCHEDULED_JOB BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: MSG_USER_MESSAGE, Owner: SYSDBA */
CREATE TABLE MSG_USER_MESSAGE (ID BIGINT NOT NULL,
        PRIORITY BIGINT,
        SUBJECT VARCHAR(255),
        BODY text,
        read SMALLINT,
        DRAFT SMALLINT,
        ARCHIVE SMALLINT,
        MESSAGE_DATE TIMESTAMP,
        USER_FROM BIGINT,
        USER_TO BIGINT NOT NULL,
        TENANT BIGINT NOT NULL,
        IS_READ SMALLINT,
PRIMARY KEY (ID));

/* Table: NOTIFICATION_BAS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_BAS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: NOTIFICATION_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_RECIPIENTS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: OC_CLUSTER_NODE, Owner: SYSDBA */
CREATE TABLE OC_CLUSTER_NODE (ID BIGINT NOT NULL,
        LATEST_PING_TIME TIMESTAMP NOT NULL,
        MASTER_NODE SMALLINT NOT NULL,
        NODE_HTTP_PORT BIGINT NOT NULL,
        NODE_IP_ADDRESS VARCHAR(255) NOT NULL,
        NODE_IS_STOPPED SMALLINT,
        NODE_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_COMMON_USER, Owner: SYSDBA */
CREATE TABLE OC_COMMON_USER (ID BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_CUSTOM_PAGE, Owner: SYSDBA */
CREATE TABLE OC_CUSTOM_PAGE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(254) NOT NULL,
        PAGE_TEXT text,
        PAGE_TYPE VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: OC_ENTITY_LOCK, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_LOCK (ID BIGINT NOT NULL,
        LOCK_DATE DATE,
        LOCKED_ENTITY_NAME VARCHAR(255),
        LOCKED_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_ENTITY_WORD, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_WORD (ID BIGINT NOT NULL,
        ENTITY_CLASS VARCHAR(80) NOT NULL,
        ENTITY_ID_STRING VARCHAR(80),
        ENTITY_ID_LONG BIGINT,
        THEWORD VARCHAR(80),
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT2ENT_FLD_EXPR, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT2ENT_FLD_EXPR (ID BIGINT NOT NULL,
        FIELD_NAME VARCHAR(255),
        EXPRESSION VARCHAR(255),
        EXTERNAL_ENTITY2ENTITY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        PROCESS_ENTITY_CHECK_EXPR VARCHAR(255),
        PROCESS_ORDER BIGINT,
        IS_ACTIVE SMALLINT,
        EXTERNAL_SYSTEM BIGINT NOT NULL,
        CHECK_DUPLICATE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_EXT_ENTITY2ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY2ENTITY (ID BIGINT NOT NULL,
        ENTITY_CLASS VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY_FIELD (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FIELD_TYPE VARCHAR(255),
        CODE VARCHAR(30) NOT NULL,
        FIELD_POSITION BIGINT,
        KEY_POSITION BIGINT,
        EXTERNAL_ENTITY_REFERENCE BIGINT,
        EXTERNAL_ENTITY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_FLD2FLD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_FLD2FLD (ID BIGINT NOT NULL,
        FIELD_NAME VARCHAR(255) NOT NULL,
        REFERENCED_ENTITY_FIELD_NAME VARCHAR(255),
        EXTERNAL_ENTITY_FIELD BIGINT NOT NULL,
        EXTERNAL_ENTITY2ENTITY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_ID2ID, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_ID2ID (ID BIGINT NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(255) NOT NULL,
        PK_VALUE VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY2ENTITY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_PROCESSED_KEYS, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_PROCESSED_KEYS (ID BIGINT NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(30) NOT NULL,
        GUID VARCHAR(255) NOT NULL,
        COUNTER BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_SYSTEM, Owner: SYSDBA */
CREATE TABLE OC_EXT_SYSTEM (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255) NOT NULL,
        IS_ACTIVE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_GROUP_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_GROUP_PERMISSION (ID BIGINT NOT NULL,
        PERMISSION BIGINT NOT NULL,
        SECURITY_GROUP BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_GROUP_ROLE, Owner: SYSDBA */
CREATE TABLE OC_GROUP_ROLE (ID BIGINT NOT NULL,
        SECURITY_GROUP BIGINT NOT NULL,
        SECURITY_ROLE BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_HELP_BIN_OBJECT, Owner: SYSDBA */
CREATE TABLE OC_HELP_BIN_OBJECT (ID BIGINT NOT NULL,
        BIN_CONTENT oid,
        MIME_TYPE VARCHAR(80),
        NAME VARCHAR(255),
        HELP_TOPIC VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_HELP_SECTION, Owner: SYSDBA */
CREATE TABLE OC_HELP_SECTION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(250),
PRIMARY KEY (CODE));

/* Table: OC_HELP_TOPIC, Owner: SYSDBA */
CREATE TABLE OC_HELP_TOPIC (CODE VARCHAR(255) NOT NULL,
        CONTENT_TEXT text,
        LINK_URL VARCHAR(250),
        NAME VARCHAR(250) NOT NULL,
        SECTION VARCHAR(80) NOT NULL,
CONSTRAINT PK_OC_HELP_TOPIC PRIMARY KEY (CODE));

/* Table: OC_JBPM5EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_ATTRIBUTE (ID BIGINT NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCDEF_EXTENSION (ID BIGINT NOT NULL,
        PROCESS_ID VARCHAR(255),
        PROCESS_KEY VARCHAR(255),
        LATEST SMALLINT,
        EXTENSION_VERSION BIGINT NOT NULL,
        LATEST_FOR_PROCESS_ID SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCESS_VARIABLE (ID BIGINT NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SEL_CRITERIA_CLASS VARCHAR(255),
        SEL_CRITERIA_EXPR VARCHAR(255),
        SEL_CRITERIA_PARAMS_EXPR VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VALIDATION (ID BIGINT NOT NULL,
        TASK VARCHAR(255),
        CONDITION VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VARIABLE (ID BIGINT NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
        PROCESS_VARIABLE BIGINT NOT NULL,
        VAR VARCHAR(255),
        VAR_POSITION BIGINT,
        HIDDEN SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_DEPLOYMENT (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DEPLOYMENT_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCEXT_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCEXT_RSRC (ID BIGINT NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        EXTENSION_VERSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCIMG_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCIMG_RSRC (PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        PROCESS_VERSION BIGINT NOT NULL,
        ID BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROC_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROC_RESOURCE (ID BIGINT NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_NAME VARCHAR(255),
        PROCESS_KEY VARCHAR(255) NOT NULL,
        LATEST SMALLINT,
        PROCESS_VERSION BIGINT NOT NULL,
        DISABLED SMALLINT,
        PACKAGE_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_RESOURCE (ID BIGINT NOT NULL,
        RESOURCE_NAME VARCHAR(1024) NOT NULL,
        RESOURCE_CONTENT oid NOT NULL,
        DEPLOYMENT BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_PROC_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_PROC_VAR (ID BIGINT NOT NULL,
        BOOLEAN_VALUE SMALLINT,
        CONVERTER_TYPE_CODE VARCHAR(30),
        INTEGER_VALUE INTEGER,
        LONG_STRING_VALUE text,
        LONG_VALUE BIGINT,
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        STRING_VALUE VARCHAR(255),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        PROC_INST_ID BIGINT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (PROC_INST_ID, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_SHORTLIVE_EVENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_SHORTLIVE_EVENT (ID BIGINT NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        EVENT_TYPE VARCHAR(255) NOT NULL,
        TASK_ID BIGINT NOT NULL,
        USER_ID VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TASK_TX, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX (TASK_ID BIGINT NOT NULL,
        TX_ID BIGINT NOT NULL,
        WAS_OPENED SMALLINT NOT NULL,
PRIMARY KEY (TASK_ID, TX_ID));

/* Table: OC_JBPM5_TASK_TX_SEQGEN, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX_SEQGEN (TX_ID BIGINT NOT NULL,
PRIMARY KEY (TX_ID));

/* Table: OC_JBPM5_TASK_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_VAR (ID BIGINT NOT NULL,
        OPT_LOCK BIGINT,
        STRING_VALUE VARCHAR(1024),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        LONG_VALUE BIGINT,
        INTEGER_VALUE INTEGER,
        BOOLEAN_VALUE SMALLINT,
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        CONVERTER_TYPE_CODE VARCHAR(30),
        LONG_STRING_VALUE text,
        TASK BIGINT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (TASK, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_WAS_OPENED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_WAS_OPENED (ID BIGINT NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        USER_ID VARCHAR(255),
        TASK BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO (ID BIGINT NOT NULL,
        BYTEARRAYSIZE BIGINT,
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY oid,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO_SEVED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO_SEVED (ID BIGINT NOT NULL,
        BYTEARRAYSIZE BIGINT,
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY oid);

/* Table: OC_JPDL4EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_ATTRIBUTE (ID BIGINT NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCDEF_EXTENSION (ID BIGINT NOT NULL,
        RESOURCE_NAME VARCHAR(255),
        PROCESS_DEFINITION_KEY VARCHAR(255),
        PROCESS_DEFINITION_VERSION BIGINT,
        LATEST SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCESS_VARIABLE (ID BIGINT NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SELECTION_CRITERIA_CLASS VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VALIDATION (ID BIGINT NOT NULL,
        TASK VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        CONDITION VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VARIABLE (ID BIGINT NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION BIGINT NOT NULL,
        PROCESS_VARIABLE BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_MAIL_MSGTEMPLATE, Owner: SYSDBA */
CREATE TABLE OC_MAIL_MSGTEMPLATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TEMPLATE_TEXT text NOT NULL,
PRIMARY KEY (CODE),
UNIQUE (NAME));

/* Table: OC_PAGE_TYPE, Owner: SYSDBA */
CREATE TABLE OC_PAGE_TYPE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: OC_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION (ID BIGINT NOT NULL,
        PERMISSION_TARGET VARCHAR(255) NOT NULL,
        PERMISSION_ACTION VARCHAR(255) NOT NULL,
        PERMISSION_DESCRIPTION VARCHAR(1024),
        PERMISSION_CATEGORY BIGINT,
PRIMARY KEY (ID));

/* Table: OC_PERMISSION_CATEGORY, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION_CATEGORY (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY, Owner: SYSDBA */
CREATE TABLE OC_QUERY (ID BIGINT NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
        QUERY_TEXT text,
        QUERY_TYPE BIGINT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_QUERY_FIELD (ID BIGINT NOT NULL,
        FLD_LENGTH BIGINT,
        FIELD_NAME VARCHAR(255),
        POS BIGINT NOT NULL,
        FIELD_TYPE VARCHAR(255) NOT NULL,
        EXPRESSION VARCHAR(1024),
        FIELD_DESCRIPTION VARCHAR(255),
        QUERY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_PARAM, Owner: SYSDBA */
CREATE TABLE OC_QUERY_PARAM (ID BIGINT NOT NULL,
        POS BIGINT NOT NULL,
        REQUIRED SMALLINT,
        EXPRESSION VARCHAR(1024),
        PARAM_TYPE VARCHAR(255),
        CAPTION VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        MANUAL_INPUT SMALLINT,
        QUERY BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_TYPE, Owner: SYSDBA */
CREATE TABLE OC_QUERY_TYPE (ID BIGINT NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_DESC, Owner: SYSDBA */
CREATE TABLE OC_REPORT_DESC (ID BIGINT NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        ENTITY_CLASS VARCHAR(255),
        TEMPLATE_FILE_NAME VARCHAR(255),
        DEFAULT_OUTPUT_FORMAT VARCHAR(255),
        ENGINE BIGINT NOT NULL,
        MASTER_QUERY BIGINT,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_ENGINE, Owner: SYSDBA */
CREATE TABLE OC_REPORT_ENGINE (ID BIGINT NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_ROLE_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_ROLE_PERMISSION (ID BIGINT NOT NULL,
        SECURITY_ROLE BIGINT NOT NULL,
        PERMISSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_SCRIPT, Owner: SYSDBA */
CREATE TABLE OC_SCRIPT (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255),
        FULL_NAME VARCHAR(255),
        SCRIPT_TEXT text,
        SCRIPT_POSITION BIGINT,
        SCRIPT_ACTIVE SMALLINT,
PRIMARY KEY (CODE));

/* Table: OC_SECURITY_GROUP, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_GROUP (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        TENANT BIGINT,
PRIMARY KEY (ID));

/* Table: OC_SECURITY_ROLE, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_ROLE (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_SECURITY_USER, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_USER (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        USER_PASSWORD VARCHAR(80) NOT NULL,
        USER_LOGIN VARCHAR(30) NOT NULL,
        X509CERTIFICATE_COMMON_NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        USER_DISABLED SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_TENANT, Owner: SYSDBA */
CREATE TABLE OC_TENANT (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        HOST_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_TENANT_USER, Owner: SYSDBA */
CREATE TABLE OC_TENANT_USER (ID BIGINT NOT NULL,
        TENANT BIGINT,
PRIMARY KEY (ID));

/* Table: OC_TYPED_PRINCIPAL_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_TYPED_PRINCIPAL_PERMISSION (ID BIGINT NOT NULL,
        PRINCIPAL_UUID VARCHAR(255),
        PERMISSION BIGINT,
PRIMARY KEY (ID));

/* Table: OC_USERPROFILE_PARAM, Owner: SYSDBA */
CREATE TABLE OC_USERPROFILE_PARAM (ID BIGINT NOT NULL,
        PARAM_VALUE VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SECURITY_USER BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GRANTED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_GRANTED_PERMISSION (ID BIGINT NOT NULL,
        PERMISSION BIGINT NOT NULL,
        SECURITY_USER BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GROUP, Owner: SYSDBA */
CREATE TABLE OC_USER_GROUP (ID BIGINT NOT NULL,
        TENANT_USER BIGINT NOT NULL,
        SECURITY_GROUP BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_REVOKED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_REVOKED_PERMISSION (ID BIGINT NOT NULL,
        SECURITY_USER BIGINT NOT NULL,
        PERMISSION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_ROLE, Owner: SYSDBA */
CREATE TABLE OC_USER_ROLE (ID BIGINT NOT NULL,
        SECURITY_USER BIGINT NOT NULL,
        SECURITY_ROLE BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_SETTING, Owner: SYSDBA */
CREATE TABLE OC_USER_SETTING (ID BIGINT NOT NULL,
        CODE VARCHAR(250) NOT NULL,
        SETTING_VALUES text,
        SETTING_USER BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_ZERO_STATE, Owner: SYSDBA */
CREATE TABLE OC_ZERO_STATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        APOSITION BIGINT NOT NULL,
        SELECT_HQL VARCHAR(1024),
        PROCESS_COLLECTIONS SMALLINT,
        BEFORE_IMPORT text,
        AFTER_IMPORT text,
        PERSIST_REFERENCES SMALLINT,
PRIMARY KEY (CODE),
UNIQUE (APOSITION));

/* Table: PEOPLEASSIGNMENTS_BAS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_BAS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_EXCLOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_EXCLOWNERS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_POTOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_POTOWNERS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_RECIPIENTS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_STAKEHOLDERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: REASSIGNMENT_POTENTIALOWNERS, Owner: SYSDBA */
CREATE TABLE REASSIGNMENT_POTENTIALOWNERS (TASK_ID BIGINT NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: RTM_ENTITY_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME_EXPRESSION VARCHAR(255),
        TO_STRING_EXPRESSION VARCHAR(255),
        QUICK_FILTER_EXPRESSION VARCHAR(255),
        DEFAULT_ORDER VARCHAR(255),
        PATH_EXPRESSION VARCHAR(255),
        DEFAULT_FOLDER VARCHAR(255),
        SUBENTITY_ONLY SMALLINT,
        RM_PROVIDER VARCHAR(50),
        TO_STRING_QUERY VARCHAR(1024),
        CUSTOM_LIST_COMPONENT VARCHAR(255),
        CUSTOM_HOME_COMPONENT VARCHAR(255),
        CUSTOM_ENTITY_FRAME VARCHAR(255),
        CUSTOM_LIST_FRAME VARCHAR(255),
        QUICK_SEARCH_FIELDS VARCHAR(1024),
PRIMARY KEY (CODE));

/* Table: RTM_ENTITY_FILTER, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FILTER (ID BIGINT NOT NULL,
        FILTER_PROPERTY VARCHAR(80) NOT NULL,
        CAPTION VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        FILTER_JOIN_STRING VARCHAR(4000),
        FILTER_WHERE_STRING VARCHAR(4000),
        FILTER_PARAM_EXPRESSION VARCHAR(4000),
        FILTER_POS BIGINT,
        FILTER_VALUE_TYPE VARCHAR(80),
        FILTER_HANDLER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_FORM_PANEL, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FORM_PANEL (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CAPTION VARCHAR(255),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        PANEL_POS BIGINT,
        PANEL_TYPE VARCHAR(80) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PARENT_PANEL BIGINT,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_OPERATION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_OPERATION (ID BIGINT NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        OPERATION_EXPRESSION VARCHAR(1024) NOT NULL,
        ENABLED_EXPRESSION VARCHAR(1024) NOT NULL,
        OPERATION_POS BIGINT NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        HIDE_NAME SMALLINT,
        OPERATION_DESCRIPTION VARCHAR(255),
        OPERATION_ICON VARCHAR(1024),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_PROPERTY_VALUE (ID BIGINT NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PROPERTY VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_VALIDATOR, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_VALIDATOR (ID BIGINT NOT NULL,
        VALID_EXPRESSION VARCHAR(1024) NOT NULL,
        INVALID_MESSAGE VARCHAR(255) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        CODE VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_DEFINITION (ID BIGINT NOT NULL,
        FORMAT VARCHAR(255),
        FIELD_NAME VARCHAR(255),
        DEFAULT_EXPRESSION VARCHAR(255),
        CAPTION VARCHAR(255),
        DATA_LEN BIGINT,
        FIELD_POS BIGINT,
        IS_COLLECTION SMALLINT,
        CALC_EXPRESSION VARCHAR(1024),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        REQUIRED_EXPRESSION VARCHAR(255),
        SHOW_IN_LIST SMALLINT,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        DATA_TYPE VARCHAR(80) NOT NULL,
        ENTITY_PARENT_FIELD BIGINT,
        PANEL BIGINT,
        ENTITY_FILTER VARCHAR(1024),
        EMBEDDED_ENTITY SMALLINT,
        VISUALIZER VARCHAR(255),
        FIELD_HINT VARCHAR(1024),
        SERIALIZER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_PROPERTY_VALUE (ID BIGINT NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        PROPERTY VARCHAR(30) NOT NULL,
        FIELD_DEFINITION BIGINT NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_MENU_ITEM, Owner: SYSDBA */
CREATE TABLE RTM_MENU_ITEM (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        WINDOW_NAME VARCHAR(255),
        ITEMPOSITION BIGINT,
        PARENT VARCHAR(30),
        PERMISSION_TARGET VARCHAR(255),
        PERMISSION_ACTION VARCHAR(255),
        EXTERNAL_LINK SMALLINT,
        TARGET_NAME VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: RTM_MODEL_PROPERTY, Owner: SYSDBA */
CREATE TABLE RTM_MODEL_PROPERTY (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: RTM_TYPE_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_TYPE_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TYPE_NAME VARCHAR(80) NOT NULL,
        SERIALIZER VARCHAR(255),
        VER BIGINT,
        INLINE SMALLINT,
        VISUALIZER VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: TESTTABLE1, Owner: SYSDBA */
CREATE TABLE TESTTABLE1 (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: TMP_OLDTABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_OLDTABNUMS (USER_ID BIGINT,
        TABNO VARCHAR(255));

/* Table: TMP_SAVED_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_SAVED_UNIT_CODES (ID BIGINT,
        CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT_CODES (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_TABNUMS (TABNO INTEGER,
        FIO VARCHAR(255),
        BE VARCHAR(255),
        BENAME VARCHAR(255),
        DEP1 VARCHAR(255),
        DEP1NAME VARCHAR(255),
        DEP2 VARCHAR(255),
        DEP2NAME VARCHAR(255),
        USERSFOUND BIGINT,
        USERID BIGINT,
        CNT INTEGER);

/* Table: TMP_USERS, Owner: SYSDBA */
CREATE TABLE TMP_USERS (LOGIN VARCHAR(80),
        PNAME VARCHAR(255),
        CNT INTEGER,
        UNITPATH VARCHAR(80));
