/*  Generators or sequences */
CREATE SEQUENCE ATTACHMENT_ID_SEQ;
CREATE SEQUENCE BOOLEANEXPR_ID_SEQ;
CREATE SEQUENCE COMMENT_ID_SEQ;
CREATE SEQUENCE CONTENT_ID_SEQ;
CREATE SEQUENCE DEADLINE_ID_SEQ;
CREATE SEQUENCE EMAILNOTIFHEAD_ID_SEQ;
CREATE SEQUENCE ERM_SEQUENCE start 169949;
CREATE SEQUENCE ESCALATION_ID_SEQ;
CREATE SEQUENCE HIBERNATE_SEQUENCE start 320328;
CREATE SEQUENCE I18NTEXT_ID_SEQ start 29107;
CREATE SEQUENCE NOTIFICATION_ID_SEQ;
CREATE SEQUENCE OC_JBPM5_TASK_TX_TXID_SEQ start 113;
CREATE SEQUENCE OC_JBPM5_TIMER_INFO_SEQ start 19187;
CREATE SEQUENCE REASSIGNMENT_ID_SEQ;
CREATE SEQUENCE SESSIONINFO_ID_SEQ start 8;
CREATE SEQUENCE WORKITEMINFO_ID_SEQ start 29107;


/* Table: CFG_ARTIFACT, Owner: SYSDBA */
CREATE TABLE CFG_ARTIFACT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        VERSION NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLED boolean,
        INSTALL_LOG text,
PRIMARY KEY (ID));

/* Table: CFG_DEPENDENCY, Owner: SYSDBA */
CREATE TABLE CFG_DEPENDENCY (ID NUMERIC(18, 0) NOT NULL,
        DEPENDENCY_CODE VARCHAR(255) NOT NULL,
        DEPENDENCY_VERSION NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PATH VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        INSTALL_ORDER NUMERIC(18, 0) NOT NULL,
        RESOURCE_TYPE NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_PARAM, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255) NOT NULL,
        PARAM_NAME VARCHAR(255) NOT NULL,
        RESOURCE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_TYPE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLER VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: DELEGATION_DELEGATES, Owner: SYSDBA */
CREATE TABLE DELEGATION_DELEGATES (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: ERMS_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERMS_EXTLINK (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERMS_EXTLINK PRIMARY KEY (ID));

/* Table: ERMS_FILTERED, Owner: SYSDBA */
CREATE TABLE ERMS_FILTERED (ID NUMERIC(18, 0) NOT NULL,
        SEARCHID NUMERIC(18, 0));

/* Table: ERMS_SAVED_FILTER, Owner: SYSDBA */
CREATE TABLE ERMS_SAVED_FILTER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0) NOT NULL,
        USER_ID NUMERIC(18, 0),
        NAME VARCHAR(250) NOT NULL,
        XMLDATA oid NOT NULL,
CONSTRAINT PK_ERMS_SAVED_FILTER PRIMARY KEY (ID));

/* Table: ERM_ADDRESSEEDOC, Owner: SYSDBA */
CREATE TABLE ERM_ADDRESSEEDOC (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        INTCONTRAGENT boolean,
        ADDRESSEE NUMERIC(18, 0),
        INTADDRESSEE NUMERIC(18, 0),
        RECIPIENT VARCHAR(255),
        INTRECIPIENT NUMERIC(18, 0),
        DELIVERYKIND NUMERIC(18, 0),
        DATEDELIVERY TIMESTAMP,
CONSTRAINT PK_ERM_ADDRESSEEDOC PRIMARY KEY (ID));

/* Table: ERM_AGENTREQUEST, Owner: SYSDBA */
CREATE TABLE ERM_AGENTREQUEST (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        AGENTTYPE NUMERIC(18, 0),
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN NUMERIC(18, 0),
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        DOCDATE TIMESTAMP,
        COMMENTS VARCHAR(255),
        RESULT NUMERIC(18, 0),
        USERREQUEST NUMERIC(18, 0),
        SHORTTITLE VARCHAR(255),
        KPP NUMERIC(18, 0),
CONSTRAINT PK_ERM_AGENTREQUEST PRIMARY KEY (ID));

/* Table: ERM_AGENTTYPE, Owner: SYSDBA */
CREATE TABLE ERM_AGENTTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_AGENTTYPE PRIMARY KEY (ID));

/* Table: ERM_ASUDINTEGRATIONRULE, Owner: SYSDBA */
CREATE TABLE ERM_ASUDINTEGRATIONRULE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        TASKPROCESSORNAME VARCHAR(255),
        TASKNAME VARCHAR(255),
        JBPMPROCESS NUMERIC(18, 0),
        COMMANDELEXPRESSION VARCHAR(1024),
        TASKTYPE NUMERIC(18, 0),
        SKIPEXPRESSION VARCHAR(1024),
CONSTRAINT PK_ERM_ASUDINTEGRATIONRULE PRIMARY KEY (ID));

/* Table: ERM_BIN_CONTENT, Owner: SYSDBA */
CREATE TABLE ERM_BIN_CONTENT (ID NUMERIC(18, 0) NOT NULL,
        CONTENT_ID NUMERIC(18, 0) NOT NULL,
        CONTENT_VER INTEGER NOT NULL,
        MODIFIED_BY VARCHAR(255),
        LAST_MODIFIED TIMESTAMP,
        IS_ACTUAL boolean,
        SIGNED boolean,
        SIGN_DATE TIMESTAMP,
        SIGN_AUTHOR VARCHAR(255),
        MIMETYPE VARCHAR(255),
        ENCODING VARCHAR(255),
        FILENAME VARCHAR(255),
        SIGN_ALGORITHM VARCHAR(255),
CONSTRAINT PK_ERM_BIN_CONTENT PRIMARY KEY (ID));

/* Table: ERM_BOARD, Owner: SYSDBA */
CREATE TABLE ERM_BOARD (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CHAIRMAN NUMERIC(18, 0),
        SECRETARY NUMERIC(18, 0),
        ANAME VARCHAR(255),
        CODE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
CONSTRAINT PK_ERM_BOARD PRIMARY KEY (ID));

/* Table: ERM_CONTRAGENT, Owner: SYSDBA */
CREATE TABLE ERM_CONTRAGENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        AGENTTYPE NUMERIC(18, 0),
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN NUMERIC(18, 0),
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        active boolean,
        SHORTTITLE VARCHAR(255),
        KPP NUMERIC(18, 0),
CONSTRAINT PK_ERM_CONTRAGENT PRIMARY KEY (ID));

/* Table: ERM_DELEGATION, Owner: SYSDBA */
CREATE TABLE ERM_DELEGATION (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EMPLOYER NUMERIC(18, 0),
        DELEGAT NUMERIC(18, 0),
        PROCESS NUMERIC(18, 0),
        USERTASK NUMERIC(18, 0),
        ADDTASK boolean,
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        active boolean,
CONSTRAINT PK_ERM_DELEGATION PRIMARY KEY (ID));

/* Table: ERM_DELIVERYKIND, Owner: SYSDBA */
CREATE TABLE ERM_DELIVERYKIND (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DELIVERYKIND PRIMARY KEY (ID));

/* Table: ERM_DOCKIND, Owner: SYSDBA */
CREATE TABLE ERM_DOCKIND (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
        INDEXKIND VARCHAR(16),
        APPROVAL boolean,
        BOARD boolean,
        active boolean,
CONSTRAINT PK_ERM_DOCKIND PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERING, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERING (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ORGUNIT NUMERIC(18, 0),
        BOARD NUMERIC(18, 0),
        DOCTYPE NUMERIC(18, 0),
        DOCKIND NUMERIC(18, 0),
        PERIOD NUMERIC(18, 0),
        PREFIX VARCHAR(255),
        POSTFIX VARCHAR(255),
CONSTRAINT PK_ERM_DOCNUMBERING PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERSEQ, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERSEQ (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODCODE VARCHAR(10),
        NEXTNUMBER NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCNUMBERSEQ PRIMARY KEY (ID));

/* Table: ERM_DOCRELATED, Owner: SYSDBA */
CREATE TABLE ERM_DOCRELATED (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOC NUMERIC(18, 0),
        ANAME NUMERIC(18, 0),
        SOURCEDOC NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCRELATED PRIMARY KEY (ID));

/* Table: ERM_DOCSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_DOCSTATUS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DOCSTATUS PRIMARY KEY (ID));

/* Table: ERM_DOCTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTEMPLATE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        DOCKIND NUMERIC(18, 0),
        ORGUNIT NUMERIC(18, 0),
        file NUMERIC(18, 0),
        LINK VARCHAR(255),
CONSTRAINT PK_ERM_DOCTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_DOCTYPE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(5),
        ANAME VARCHAR(255),
        INDEXTYPE VARCHAR(16),
CONSTRAINT PK_ERM_DOCTYPE PRIMARY KEY (ID));

/* Table: ERM_DOCUMENT, Owner: SYSDBA */
CREATE TABLE ERM_DOCUMENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        BRANCH NUMERIC(18, 0),
        STATUS NUMERIC(18, 0),
        DOCTYPE NUMERIC(18, 0),
        DOCKIND NUMERIC(18, 0),
        NUMBER VARCHAR(255),
        REGDATE TIMESTAMP,
        OUTNUMBER VARCHAR(255),
        INTCONTRAGENT boolean,
        ASUD VARCHAR(255),
        AGENT NUMERIC(18, 0),
        AGENTREQUEST NUMERIC(18, 0),
        INAUTHOR VARCHAR(255),
        INTCORRESPONDENT NUMERIC(18, 0),
        BOARD NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        SUBJECT VARCHAR(1024),
        DELIVERYKIND NUMERIC(18, 0),
        NOMENCLATURE NUMERIC(18, 0),
        REGISTRATOR NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        NEEDAGREEMENT boolean,
        SIGNER NUMERIC(18, 0),
        ARCHIVE boolean,
        OUTDATE TIMESTAMP,
        ORIGINAL boolean,
        STORAGE NUMERIC(18, 0),
        TRANSFERDATE TIMESTAMP,
        CLERKNOTE VARCHAR(1024),
        CREATEDATE TIMESTAMP,
        SUPERVISOR NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCUMENT PRIMARY KEY (ID));

/* Table: ERM_DOCUSER, Owner: SYSDBA */
CREATE TABLE ERM_DOCUSER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCUSER NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCUSER PRIMARY KEY (ID));

/* Table: ERM_ENTITYEVENT, Owner: SYSDBA */
CREATE TABLE ERM_ENTITYEVENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        EVENTDATE TIMESTAMP,
        EVENTTYPE VARCHAR(80),
        ANAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        EVENTUSER NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
CONSTRAINT PK_ERM_ENTITYEVENT PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        TEMPLATEOWNER NUMERIC(18, 0),
        COMMON boolean,
        TEMPLATELEVEL NUMERIC(18, 0),
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATEITEM, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATEITEM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EXECUTANT NUMERIC(18, 0),
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATEITEM PRIMARY KEY (ID));

/* Table: ERM_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERM_EXTLINK (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_EXTLINK PRIMARY KEY (ID));

/* Table: ERM_FAVORITES, Owner: SYSDBA */
CREATE TABLE ERM_FAVORITES (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        FAVORITE NUMERIC(18, 0),
CONSTRAINT PK_ERM_FAVORITES PRIMARY KEY (ID));

/* Table: ERM_FILE, Owner: SYSDBA */
CREATE TABLE ERM_FILE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        file NUMERIC(18, 0),
        FILETYPE NUMERIC(18, 0),
        NOTE VARCHAR(255),
        USERREF NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
CONSTRAINT PK_ERM_FILE PRIMARY KEY (ID));

/* Table: ERM_FILETYPE, Owner: SYSDBA */
CREATE TABLE ERM_FILETYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        DEFAULTFILE boolean,
CONSTRAINT PK_ERM_FILETYPE PRIMARY KEY (ID));

/* Table: ERM_FOLDER, Owner: SYSDBA */
CREATE TABLE ERM_FOLDER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ENTITY_TYPE VARCHAR(80),
        TENANT_ID NUMERIC(18, 0),
        PARENT_ID NUMERIC(18, 0),
        SORT_INDEX INTEGER,
        LBORDER NUMERIC(18, 0),
        RBORDER NUMERIC(18, 0),
        QUERY_DESC NUMERIC(18, 0),
CONSTRAINT PK_ERM_FOLDER PRIMARY KEY (ID));

/* Table: ERM_LINKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_LINKTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_LINKTYPE PRIMARY KEY (ID));

/* Table: ERM_LISTNUMBER, Owner: SYSDBA */
CREATE TABLE ERM_LISTNUMBER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCID NUMERIC(18, 0),
        REGNUMBER VARCHAR(255),
        REF NUMERIC(18, 0),
CONSTRAINT PK_ERM_LISTNUMBER PRIMARY KEY (ID));

/* Table: ERM_NOMENCLATURE, Owner: SYSDBA */
CREATE TABLE ERM_NOMENCLATURE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PARENTNOMENCLATURE NUMERIC(18, 0),
        INDEXFIELD VARCHAR(255),
        TITLE VARCHAR(255),
        AMOUNT NUMERIC(18, 0),
        LIFESTORAGE VARCHAR(255),
        ORGUNIT NUMERIC(18, 0),
        COMMENT VARCHAR(255),
        active boolean,
        ARTICLE VARCHAR(255),
        CHILDACCESS boolean,
CONSTRAINT PK_ERM_NOMENCLATURE PRIMARY KEY (ID));

/* Table: ERM_NOTE, Owner: SYSDBA */
CREATE TABLE ERM_NOTE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        NOTEINDEX NUMERIC(18, 0),
        REPLYTO NUMERIC(18, 0),
        TEXT VARCHAR(2048),
        CREATEDATE TIMESTAMP,
        USERNOTE NUMERIC(18, 0),
        STATUS VARCHAR(255),
CONSTRAINT PK_ERM_NOTE PRIMARY KEY (ID));

/* Table: ERM_ORGTYPE, Owner: SYSDBA */
CREATE TABLE ERM_ORGTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ORGTYPE PRIMARY KEY (ID));

/* Table: ERM_ORGUNIT, Owner: SYSDBA */
CREATE TABLE ERM_ORGUNIT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(10),
        ANAME VARCHAR(255),
        PARENTUNIT NUMERIC(18, 0),
        DESCRIPTION VARCHAR(255),
        active boolean,
        SHORTNAME VARCHAR(25),
        INDEXCASE VARCHAR(255),
        ORGTYPE NUMERIC(18, 0),
        MANAGER NUMERIC(18, 0),
        UNITPATH VARCHAR(255),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        CFO NUMERIC(18, 0),
CONSTRAINT PK_ERM_ORGUNIT PRIMARY KEY (ID));

/* Table: ERM_PERIOD, Owner: SYSDBA */
CREATE TABLE ERM_PERIOD (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_PERIOD PRIMARY KEY (ID));

/* Table: ERM_PERIODICTASK, Owner: SYSDBA */
CREATE TABLE ERM_PERIODICTASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODTEXT VARCHAR(255),
        PERIODTYPE NUMERIC(18, 0),
        DAYNUMBER NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
        TASKOWNER NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        CONTROLDAYS NUMERIC(18, 0),
        TASK VARCHAR(1024),
        EXECUTOR NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        FINISHDATE TIMESTAMP,
        NEXTSTART TIMESTAMP,
        LASTSTART TIMESTAMP,
        ISACTIVE boolean,
CONSTRAINT PK_ERM_PERIODICTASK PRIMARY KEY (ID));

/* Table: ERM_PERM, Owner: SYSDBA */
CREATE TABLE ERM_PERM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0) NOT NULL,
        PERM_ACTION VARCHAR(80) NOT NULL,
        PRINCIPAL_UID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_PERM PRIMARY KEY (ID));

/* Table: ERM_PFM, Owner: SYSDBA */
CREATE TABLE ERM_PFM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        PARENTUNIT NUMERIC(18, 0),
        BE NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
CONSTRAINT PK_ERM_PFM PRIMARY KEY (ID));

/* Table: ERM_PROCESS, Owner: SYSDBA */
CREATE TABLE ERM_PROCESS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        PROCESSKEY VARCHAR(80),
        ANAME VARCHAR(256),
CONSTRAINT PK_ERM_PROCESS PRIMARY KEY (ID));

/* Table: ERM_ROLE, Owner: SYSDBA */
CREATE TABLE ERM_ROLE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ROLE PRIMARY KEY (ID));

/* Table: ERM_STAGE, Owner: SYSDBA */
CREATE TABLE ERM_STAGE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE NUMERIC(18, 0),
        ANAME VARCHAR(15),
CONSTRAINT PK_ERM_STAGE PRIMARY KEY (ID));

/* Table: ERM_TASK, Owner: SYSDBA */
CREATE TABLE ERM_TASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASKSUBJECT VARCHAR(255),
        TASK VARCHAR(2048),
        EXECUTOR NUMERIC(18, 0),
        STATUS NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        SUPERVISOR NUMERIC(18, 0),
        CREATEDATE TIMESTAMP,
        CANCELREASON VARCHAR(255),
        CONTROLDATE TIMESTAMP,
        TASKACTIVE boolean,
        TASKACTUAL boolean,
        REFTASK NUMERIC(18, 0),
        DOCBASE VARCHAR(255),
        file NUMERIC(18, 0),
        NEEDREPORT boolean,
        ADATE TIMESTAMP,
        TASKTYPE NUMERIC(18, 0),
        FILES NUMERIC(18, 0),
        PARENTTASK NUMERIC(18, 0),
        ANUMBER VARCHAR(16),
        TASKTEXT VARCHAR(1024),
        ISDONE boolean,
        DOCUMENT NUMERIC(18, 0),
        STAGE NUMERIC(18, 0),
        NOTE VARCHAR(1024),
        STARTDATE TIMESTAMP,
        RESULTDATE TIMESTAMP,
        GETDATE TIMESTAMP,
CONSTRAINT PK_ERM_TASK PRIMARY KEY (ID));

/* Table: ERM_TASKDELEGATED, Owner: SYSDBA */
CREATE TABLE ERM_TASKDELEGATED (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASK NUMERIC(18, 0),
CONSTRAINT PK_ERM_TASKDELEGATED PRIMARY KEY (ID));

/* Table: ERM_TASKREPORT, Owner: SYSDBA */
CREATE TABLE ERM_TASKREPORT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        REPORT VARCHAR(2048),
        REPORTDATE TIMESTAMP,
        ACCEPTED boolean,
        NOTE VARCHAR(1024),
        NOTEDATE TIMESTAMP,
        NOTEUSER NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
CONSTRAINT PK_ERM_TASKREPORT PRIMARY KEY (ID));

/* Table: ERM_TASKSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_TASKSTATUS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        CODE VARCHAR(16),
CONSTRAINT PK_ERM_TASKSTATUS PRIMARY KEY (ID));

/* Table: ERM_TASKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_TASKTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        REPORT boolean,
        PREF VARCHAR(16),
CONSTRAINT PK_ERM_TASKTYPE PRIMARY KEY (ID));

/* Table: ERM_USER, Owner: SYSDBA */
CREATE TABLE ERM_USER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        SURNAME VARCHAR(255),
        FIRSTNAME VARCHAR(255),
        PATRONYMIC VARCHAR(255),
        LOGIN VARCHAR(255),
        ANAME VARCHAR(255),
        ORGUNIT NUMERIC(18, 0),
        JOBNAME VARCHAR(255),
        EMAIL VARCHAR(255),
        TABNUMBER VARCHAR(255),
        DISMISSED boolean,
        DELEGAT NUMERIC(18, 0),
        USERREF NUMERIC(18, 0),
        INDEXUSER VARCHAR(16),
        PHONE VARCHAR(255),
        ALLOWEDDOCSOFUNIT NUMERIC(18, 0),
        ORGUNITNAME VARCHAR(255),
        SSOLOGIN VARCHAR(255),
        PARENTORGUNIT NUMERIC(18, 0),
        NOTE VARCHAR(255),
CONSTRAINT PK_ERM_USER PRIMARY KEY (ID));

/* Table: ERM_USERROLE, Owner: SYSDBA */
CREATE TABLE ERM_USERROLE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ROLE NUMERIC(18, 0),
CONSTRAINT PK_ERM_USERROLE PRIMARY KEY (ID));

/* Table: ERM_USERTASK, Owner: SYSDBA */
CREATE TABLE ERM_USERTASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ANAME VARCHAR(256),
        PROCESS NUMERIC(18, 0),
CONSTRAINT PK_ERM_USERTASK PRIMARY KEY (ID));

/* Table: EVENTTYPES, Owner: SYSDBA */
CREATE TABLE EVENTTYPES (INSTANCEID NUMERIC(18, 0) NOT NULL,
        ELEMENT VARCHAR(255));

/* Table: JBPM4_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYMENT (DBID_ NUMERIC(18, 0) NOT NULL,
        NAME_ text,
        TIMESTAMP_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_DEPLOYPROP, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYPROP (DBID_ NUMERIC(18, 0) NOT NULL,
        DEPLOYMENT_ NUMERIC(18, 0),
        OBJNAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        STRINGVAL_ VARCHAR(255),
        LONGVAL_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_EXECUTION, Owner: SYSDBA */
CREATE TABLE JBPM4_EXECUTION (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ACTIVITYNAME_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        HASVARS_ boolean,
        NAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        ID_ VARCHAR(255),
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        HISACTINST_ NUMERIC(18, 0),
        PARENT_ NUMERIC(18, 0),
        INSTANCE_ NUMERIC(18, 0),
        SUPEREXEC_ NUMERIC(18, 0),
        SUBPROCINST_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_),
UNIQUE (ID_));

/* Table: JBPM4_HIST_ACTINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_ACTINST (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        HPROCI_ NUMERIC(18, 0),
        TYPE_ VARCHAR(255),
        EXECUTION_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        TRANSITION_ VARCHAR(255),
        NEXTIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_DETAIL, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_DETAIL (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USERID_ VARCHAR(255),
        TIME_ TIMESTAMP,
        HPROCI_ NUMERIC(18, 0),
        HPROCIIDX_ INTEGER,
        HACTI_ NUMERIC(18, 0),
        HACTIIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
        HTASKIDX_ INTEGER,
        HVAR_ NUMERIC(18, 0),
        HVARIDX_ INTEGER,
        MESSAGE_ text,
        OLD_STR_ VARCHAR(255),
        NEW_STR_ VARCHAR(255),
        OLD_INT_ INTEGER,
        NEW_INT_ INTEGER,
        OLD_TIME_ TIMESTAMP,
        NEW_TIME_ TIMESTAMP,
        PARENT_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_PROCINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_PROCINST (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        KEY_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
        ENDACTIVITY_ VARCHAR(255),
        NEXTIDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        EXECUTION_ VARCHAR(255),
        OUTCOME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        STATE_ VARCHAR(255),
        CREATE_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        NEXTIDX_ INTEGER,
        SUPERTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_VAR, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_VAR (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        PROCINSTID_ VARCHAR(255),
        EXECUTIONID_ VARCHAR(255),
        VARNAME_ VARCHAR(255),
        VALUE_ VARCHAR(255),
        HPROCI_ NUMERIC(18, 0),
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_GROUP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_GROUP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        NAME_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        PARENT_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_MEMBERSHIP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_MEMBERSHIP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USER_ NUMERIC(18, 0),
        GROUP_ NUMERIC(18, 0),
        NAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_USER, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_USER (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PASSWORD_ VARCHAR(255),
        GIVENNAME_ VARCHAR(255),
        FAMILYNAME_ VARCHAR(255),
        BUSINESSEMAIL_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_JOB, Owner: SYSDBA */
CREATE TABLE JBPM4_JOB (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        DUEDATE_ TIMESTAMP,
        STATE_ VARCHAR(255),
        ISEXCLUSIVE_ boolean,
        LOCKOWNER_ VARCHAR(255),
        LOCKEXPTIME_ TIMESTAMP,
        EXCEPTION_ text,
        RETRIES_ INTEGER,
        PROCESSINSTANCE_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        CFG_ NUMERIC(18, 0),
        SIGNAL_ VARCHAR(255),
        EVENT_ VARCHAR(255),
        REPEAT_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_LOB, Owner: SYSDBA */
CREATE TABLE JBPM4_LOB (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        BLOB_VALUE_ oid,
        DEPLOYMENT_ NUMERIC(18, 0),
        NAME_ text,
PRIMARY KEY (DBID_));

/* Table: JBPM4_PARTICIPATION, Owner: SYSDBA */
CREATE TABLE JBPM4_PARTICIPATION (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        GROUPID_ VARCHAR(255),
        USERID_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        TASK_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_PROPERTY, Owner: SYSDBA */
CREATE TABLE JBPM4_PROPERTY (KEY_ VARCHAR(255) NOT NULL,
        VERSION_ INTEGER NOT NULL,
        VALUE_ VARCHAR(255),
PRIMARY KEY (KEY_));

/* Table: JBPM4_SWIMLANE, Owner: SYSDBA */
CREATE TABLE JBPM4_SWIMLANE (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        EXECUTION_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ CHAR(1) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        DESCR_ text,
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        FORM_ VARCHAR(255),
        PRIORITY_ INTEGER,
        CREATE_ TIMESTAMP,
        DUEDATE_ TIMESTAMP,
        PROGRESS_ INTEGER,
        SIGNALLING_ boolean,
        EXECUTION_ID_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        HASVARS_ boolean,
        SUPERTASK_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        PROCINST_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
        TASKDEFNAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_VARIABLE, Owner: SYSDBA */
CREATE TABLE JBPM4_VARIABLE (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        KEY_ VARCHAR(255),
        CONVERTER_ VARCHAR(255),
        HIST_ boolean,
        EXECUTION_ NUMERIC(18, 0),
        TASK_ NUMERIC(18, 0),
        LOB_ NUMERIC(18, 0),
        DATE_VALUE_ TIMESTAMP,
        DOUBLE_VALUE_ DOUBLE PRECISION,
        CLASSNAME_ VARCHAR(255),
        LONG_VALUE_ NUMERIC(18, 0),
        STRING_VALUE_ VARCHAR(255),
        TEXT_VALUE_ text,
        EXESYS_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM5_HT_ATTACHMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ATTACHMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        ACCESSTYPE INTEGER,
        CONTENTTYPE VARCHAR(255),
        ATTACHEDAT TIMESTAMP,
        ATTACHMENT_SIZE INTEGER,
        ATTACHMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        ATTACHEDBY_ID VARCHAR(255),
        TASKDATA_ATTACHMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_BOOL_EXPR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_BOOL_EXPR (ID NUMERIC(18, 0) NOT NULL,
        TYPE VARCHAR(255),
        EXPRESSION text,
        ESCALATION_CONSTRAINTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_COMMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_COMMENT (ID NUMERIC(18, 0) NOT NULL,
        TEXT text,
        ADDEDAT TIMESTAMP,
        ADDEDBY_ID VARCHAR(255),
        TASKDATA_COMMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_CONTENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_CONTENT (ID NUMERIC(18, 0) NOT NULL,
        CONTENT oid,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_DEADLINE, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_DEADLINE (ID NUMERIC(18, 0) NOT NULL,
        DEADLINE_DATE TIMESTAMP,
        ESCALATED boolean NOT NULL,
        DEADLINES_ENDDEADLINE_ID NUMERIC(18, 0),
        DEADLINES_STARTDEADLINE_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_ESCALATION, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ESCALATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        DEADLINE_ESCALATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_I18N_TEXT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_I18N_TEXT (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        TEXT text,
        TASK_DESCRIPTIONS_ID NUMERIC(18, 0),
        TASK_SUBJECTS_ID NUMERIC(18, 0),
        TASK_NAMES_ID NUMERIC(18, 0),
        REASSIGNMENT_DOCUMENTATION_ID NUMERIC(18, 0),
        NOTIFICATION_DESCRIPTIONS_ID NUMERIC(18, 0),
        NOTIFICATION_SUBJECTS_ID NUMERIC(18, 0),
        NOTIFICATION_NAMES_ID NUMERIC(18, 0),
        NOTIFICATION_DOCUMENTATION_ID NUMERIC(18, 0),
        DEADLINE_DOCUMENTATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_MAILNHDR (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        REPLYTOADDRESS VARCHAR(255),
        FROMADDRESS VARCHAR(255),
        SUBJECT VARCHAR(255),
        BODY text,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N (DTYPE VARCHAR(31) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ESCALATION_NOTIFICATIONS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N_JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR (JBPM5_HT_N10N_ID NUMERIC(18, 0) NOT NULL,
        EMAILHEADERS_ID NUMERIC(18, 0) NOT NULL,
        MAPKEY VARCHAR(255) NOT NULL,
PRIMARY KEY (JBPM5_HT_N10N_ID, MAPKEY),
UNIQUE (EMAILHEADERS_ID));

/* Table: JBPM5_HT_ORG_ENTITY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ORG_ENTITY (DTYPE VARCHAR(31) NOT NULL,
        ID VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_REASSIGNMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_REASSIGNMENT (ID NUMERIC(18, 0) NOT NULL,
        ESCALATION_REASSIGNMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_SUBTASK_STRATEGY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_SUBTASK_STRATEGY (DTYPE VARCHAR(100) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TASK_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_TASK, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_TASK (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ALLOWEDTODELEGATE VARCHAR(255),
        STATUS VARCHAR(255),
        PREVIOUSSTATUS INTEGER,
        CREATEDON TIMESTAMP,
        ACTIVATIONTIME TIMESTAMP,
        EXPIRATIONTIME TIMESTAMP,
        SKIPABLE boolean NOT NULL,
        WORKITEMID NUMERIC(18, 0) NOT NULL,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        DOCUMENTACCESSTYPE INTEGER,
        DOCUMENTTYPE VARCHAR(255),
        DOCUMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        OUTPUTACCESSTYPE INTEGER,
        OUTPUTTYPE VARCHAR(255),
        OUTPUTCONTENTID NUMERIC(18, 0) NOT NULL,
        FAULTNAME VARCHAR(255),
        FAULTACCESSTYPE INTEGER,
        FAULTTYPE VARCHAR(255),
        FAULTCONTENTID NUMERIC(18, 0) NOT NULL,
        PARENTID NUMERIC(18, 0) NOT NULL,
        PROCESSID VARCHAR(255),
        PROCESSKEY VARCHAR(255),
        PROCESSSESSIONID INTEGER NOT NULL,
        TASKINITIATOR_ID VARCHAR(255),
        CREATEDBY_ID VARCHAR(255),
        ACTUALOWNER_ID VARCHAR(255),
        OPTLOCK INTEGER,
        ARCHIVED boolean,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (ID));

/* Table: JBPM5_PROCINST_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_PROCINST_INFO (INSTANCEID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        PROCESSID VARCHAR(255),
        STARTDATE TIMESTAMP,
        LASTREADDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        STATE INTEGER NOT NULL,
        PROCESSINSTANCEBYTEARRAY oid,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (INSTANCEID));

/* Table: JBPM5_SESSION_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO (ID INTEGER NOT NULL,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY oid,
        CLUSTERNODENAME VARCHAR(80),
PRIMARY KEY (ID));

/* Table: JBPM5_SESSION_INFO_SAVED, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO_SAVED (ID INTEGER,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY oid,
        CLUSTERNODENAME VARCHAR(80));

/* Table: JBPM5_WORKITEM_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_WORKITEM_INFO (WORKITEMID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        NAME VARCHAR(255),
        CREATIONDATE TIMESTAMP,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        STATE NUMERIC(18, 0) NOT NULL,
        WORKITEMBYTEARRAY oid,
PRIMARY KEY (WORKITEMID));

/* Table: JB_JOB_TYPE, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ACTION VARCHAR(255) NOT NULL,
        FIRST_DATE_EXPRESSION VARCHAR(255) NOT NULL,
        PERIOD_EXPRESSION VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: JB_JOB_TYPE_PARAM, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        VALUE_EXPRESSION VARCHAR(255),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB (ID NUMERIC(18, 0) NOT NULL,
        START_DATE TIMESTAMP,
        ACTION VARCHAR(255) NOT NULL,
        JOB_KEY VARCHAR(255) NOT NULL,
        PERIOD_VALUE NUMERIC(18, 0),
        LAST_ERROR VARCHAR(1024),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB_PARAM, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB_PARAM (ID NUMERIC(18, 0) NOT NULL,
        STRING_VALUE VARCHAR(255),
        CODE VARCHAR(255) NOT NULL,
        DOUBLE_VALUE DOUBLE PRECISION,
        DATE_VALUE TIMESTAMP,
        SCHEDULED_JOB NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: MSG_USER_MESSAGE, Owner: SYSDBA */
CREATE TABLE MSG_USER_MESSAGE (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY NUMERIC(18, 0),
        SUBJECT VARCHAR(255),
        BODY text,
        read boolean,
        DRAFT boolean,
        ARCHIVE boolean,
        MESSAGE_DATE TIMESTAMP,
        USER_FROM NUMERIC(18, 0),
        USER_TO NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0) NOT NULL,
        IS_READ boolean,
PRIMARY KEY (ID));

/* Table: NOTIFICATION_BAS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: NOTIFICATION_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: OC_CLUSTER_NODE, Owner: SYSDBA */
CREATE TABLE OC_CLUSTER_NODE (ID NUMERIC(18, 0) NOT NULL,
        LATEST_PING_TIME TIMESTAMP NOT NULL,
        MASTER_NODE boolean NOT NULL,
        NODE_HTTP_PORT NUMERIC(18, 0) NOT NULL,
        NODE_IP_ADDRESS VARCHAR(255) NOT NULL,
        NODE_IS_STOPPED boolean,
        NODE_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_COMMON_USER, Owner: SYSDBA */
CREATE TABLE OC_COMMON_USER (ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_CUSTOM_PAGE, Owner: SYSDBA */
CREATE TABLE OC_CUSTOM_PAGE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(254) NOT NULL,
        PAGE_TEXT text,
        PAGE_TYPE VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: OC_ENTITY_LOCK, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_LOCK (ID NUMERIC(18, 0) NOT NULL,
        LOCK_DATE DATE,
        LOCKED_ENTITY_NAME VARCHAR(255),
        LOCKED_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_ENTITY_WORD, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_WORD (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(80) NOT NULL,
        ENTITY_ID_STRING VARCHAR(80),
        ENTITY_ID_LONG NUMERIC(18, 0),
        THEWORD VARCHAR(80),
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT2ENT_FLD_EXPR, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT2ENT_FLD_EXPR (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255),
        EXPRESSION VARCHAR(255),
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        PROCESS_ENTITY_CHECK_EXPR VARCHAR(255),
        PROCESS_ORDER NUMERIC(18, 0),
        IS_ACTIVE boolean,
        EXTERNAL_SYSTEM NUMERIC(18, 0) NOT NULL,
        CHECK_DUPLICATE boolean,
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_EXT_ENTITY2ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY2ENTITY (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FIELD_TYPE VARCHAR(255),
        CODE VARCHAR(30) NOT NULL,
        FIELD_POSITION NUMERIC(18, 0),
        KEY_POSITION NUMERIC(18, 0),
        EXTERNAL_ENTITY_REFERENCE NUMERIC(18, 0),
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_FLD2FLD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_FLD2FLD (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255) NOT NULL,
        REFERENCED_ENTITY_FIELD_NAME VARCHAR(255),
        EXTERNAL_ENTITY_FIELD NUMERIC(18, 0) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_ID2ID, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_ID2ID (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(255) NOT NULL,
        PK_VALUE VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_PROCESSED_KEYS, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_PROCESSED_KEYS (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(30) NOT NULL,
        GUID VARCHAR(255) NOT NULL,
        COUNTER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_SYSTEM, Owner: SYSDBA */
CREATE TABLE OC_EXT_SYSTEM (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255) NOT NULL,
        IS_ACTIVE boolean,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_GROUP_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_GROUP_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_GROUP_ROLE, Owner: SYSDBA */
CREATE TABLE OC_GROUP_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_HELP_BIN_OBJECT, Owner: SYSDBA */
CREATE TABLE OC_HELP_BIN_OBJECT (ID NUMERIC(18, 0) NOT NULL,
        BIN_CONTENT oid,
        MIME_TYPE VARCHAR(80),
        NAME VARCHAR(255),
        HELP_TOPIC VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_HELP_SECTION, Owner: SYSDBA */
CREATE TABLE OC_HELP_SECTION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(250),
PRIMARY KEY (CODE));

/* Table: OC_HELP_TOPIC, Owner: SYSDBA */
CREATE TABLE OC_HELP_TOPIC (CODE VARCHAR(255) NOT NULL,
        CONTENT_TEXT text,
        LINK_URL VARCHAR(250),
        NAME VARCHAR(250) NOT NULL,
        SECTION VARCHAR(80) NOT NULL,
CONSTRAINT PK_OC_HELP_TOPIC PRIMARY KEY (CODE));

/* Table: OC_JBPM5EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255),
        PROCESS_KEY VARCHAR(255),
        LATEST boolean,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
        LATEST_FOR_PROCESS_ID boolean,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED boolean,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST boolean,
        SEL_CRITERIA_CLASS VARCHAR(255),
        SEL_CRITERIA_EXPR VARCHAR(255),
        SEL_CRITERIA_PARAMS_EXPR VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        CONDITION VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED boolean,
        READONLY boolean,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
        VAR VARCHAR(255),
        VAR_POSITION NUMERIC(18, 0),
        HIDDEN boolean,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_DEPLOYMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DEPLOYMENT_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCEXT_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCEXT_RSRC (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCIMG_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCIMG_RSRC (PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        PROCESS_VERSION NUMERIC(18, 0) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROC_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROC_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_NAME VARCHAR(255),
        PROCESS_KEY VARCHAR(255) NOT NULL,
        LATEST boolean,
        PROCESS_VERSION NUMERIC(18, 0) NOT NULL,
        DISABLED boolean,
        PACKAGE_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(1024) NOT NULL,
        RESOURCE_CONTENT oid NOT NULL,
        DEPLOYMENT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_PROC_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_PROC_VAR (ID NUMERIC(18, 0) NOT NULL,
        BOOLEAN_VALUE boolean,
        CONVERTER_TYPE_CODE VARCHAR(30),
        INTEGER_VALUE INTEGER,
        LONG_STRING_VALUE text,
        LONG_VALUE NUMERIC(18, 0),
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        STRING_VALUE VARCHAR(255),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        PROC_INST_ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (PROC_INST_ID, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_SHORTLIVE_EVENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_SHORTLIVE_EVENT (ID NUMERIC(18, 0) NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        EVENT_TYPE VARCHAR(255) NOT NULL,
        TASK_ID NUMERIC(18, 0) NOT NULL,
        USER_ID VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TASK_TX, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX (TASK_ID NUMERIC(18, 0) NOT NULL,
        TX_ID NUMERIC(18, 0) NOT NULL,
        WAS_OPENED boolean NOT NULL,
PRIMARY KEY (TASK_ID, TX_ID));

/* Table: OC_JBPM5_TASK_TX_SEQGEN, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX_SEQGEN (TX_ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (TX_ID));

/* Table: OC_JBPM5_TASK_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_VAR (ID NUMERIC(18, 0) NOT NULL,
        OPT_LOCK NUMERIC(18, 0),
        STRING_VALUE VARCHAR(1024),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        LONG_VALUE NUMERIC(18, 0),
        INTEGER_VALUE INTEGER,
        BOOLEAN_VALUE boolean,
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        CONVERTER_TYPE_CODE VARCHAR(30),
        LONG_STRING_VALUE text,
        TASK NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (TASK, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_WAS_OPENED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_WAS_OPENED (ID NUMERIC(18, 0) NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        USER_ID VARCHAR(255),
        TASK NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO (ID NUMERIC(18, 0) NOT NULL,
        BYTEARRAYSIZE NUMERIC(18, 0),
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY oid,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO_SEVED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO_SEVED (ID NUMERIC(18, 0) NOT NULL,
        BYTEARRAYSIZE NUMERIC(18, 0),
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY oid);

/* Table: OC_JPDL4EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(255),
        PROCESS_DEFINITION_KEY VARCHAR(255),
        PROCESS_DEFINITION_VERSION NUMERIC(18, 0),
        LATEST boolean,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED boolean,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST boolean,
        SELECTION_CRITERIA_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        CONDITION VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED boolean,
        READONLY boolean,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_MAIL_MSGTEMPLATE, Owner: SYSDBA */
CREATE TABLE OC_MAIL_MSGTEMPLATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TEMPLATE_TEXT text NOT NULL,
PRIMARY KEY (CODE),
UNIQUE (NAME));

/* Table: OC_PAGE_TYPE, Owner: SYSDBA */
CREATE TABLE OC_PAGE_TYPE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: OC_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION_TARGET VARCHAR(255) NOT NULL,
        PERMISSION_ACTION VARCHAR(255) NOT NULL,
        PERMISSION_DESCRIPTION VARCHAR(1024),
        PERMISSION_CATEGORY NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_PERMISSION_CATEGORY, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION_CATEGORY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY, Owner: SYSDBA */
CREATE TABLE OC_QUERY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
        QUERY_TEXT text,
        QUERY_TYPE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_QUERY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        FLD_LENGTH NUMERIC(18, 0),
        FIELD_NAME VARCHAR(255),
        POS NUMERIC(18, 0) NOT NULL,
        FIELD_TYPE VARCHAR(255) NOT NULL,
        EXPRESSION VARCHAR(1024),
        FIELD_DESCRIPTION VARCHAR(255),
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_PARAM, Owner: SYSDBA */
CREATE TABLE OC_QUERY_PARAM (ID NUMERIC(18, 0) NOT NULL,
        POS NUMERIC(18, 0) NOT NULL,
        REQUIRED boolean,
        EXPRESSION VARCHAR(1024),
        PARAM_TYPE VARCHAR(255),
        CAPTION VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        MANUAL_INPUT boolean,
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_TYPE, Owner: SYSDBA */
CREATE TABLE OC_QUERY_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_DESC, Owner: SYSDBA */
CREATE TABLE OC_REPORT_DESC (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        ENTITY_CLASS VARCHAR(255),
        TEMPLATE_FILE_NAME VARCHAR(255),
        DEFAULT_OUTPUT_FORMAT VARCHAR(255),
        ENGINE NUMERIC(18, 0) NOT NULL,
        MASTER_QUERY NUMERIC(18, 0),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_ENGINE, Owner: SYSDBA */
CREATE TABLE OC_REPORT_ENGINE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_ROLE_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_ROLE_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_SCRIPT, Owner: SYSDBA */
CREATE TABLE OC_SCRIPT (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255),
        FULL_NAME VARCHAR(255),
        SCRIPT_TEXT text,
        SCRIPT_POSITION NUMERIC(18, 0),
        SCRIPT_ACTIVE boolean,
PRIMARY KEY (CODE));

/* Table: OC_SECURITY_GROUP, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_GROUP (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_SECURITY_ROLE, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_ROLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_SECURITY_USER, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_USER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        USER_PASSWORD VARCHAR(80) NOT NULL,
        USER_LOGIN VARCHAR(30) NOT NULL,
        X509CERTIFICATE_COMMON_NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        USER_DISABLED boolean,
PRIMARY KEY (ID));

/* Table: OC_TENANT, Owner: SYSDBA */
CREATE TABLE OC_TENANT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        HOST_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_TENANT_USER, Owner: SYSDBA */
CREATE TABLE OC_TENANT_USER (ID NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_TYPED_PRINCIPAL_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_TYPED_PRINCIPAL_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PRINCIPAL_UUID VARCHAR(255),
        PERMISSION NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_USERPROFILE_PARAM, Owner: SYSDBA */
CREATE TABLE OC_USERPROFILE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GRANTED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_GRANTED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GROUP, Owner: SYSDBA */
CREATE TABLE OC_USER_GROUP (ID NUMERIC(18, 0) NOT NULL,
        TENANT_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_REVOKED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_REVOKED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_ROLE, Owner: SYSDBA */
CREATE TABLE OC_USER_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_SETTING, Owner: SYSDBA */
CREATE TABLE OC_USER_SETTING (ID NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(250) NOT NULL,
        SETTING_VALUES text,
        SETTING_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_ZERO_STATE, Owner: SYSDBA */
CREATE TABLE OC_ZERO_STATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        APOSITION NUMERIC(18, 0) NOT NULL,
        SELECT_HQL VARCHAR(1024),
        PROCESS_COLLECTIONS boolean,
        BEFORE_IMPORT text,
        AFTER_IMPORT text,
        PERSIST_REFERENCES boolean,
PRIMARY KEY (CODE),
UNIQUE (APOSITION));

/* Table: PEOPLEASSIGNMENTS_BAS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_EXCLOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_EXCLOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_POTOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_POTOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_STAKEHOLDERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: REASSIGNMENT_POTENTIALOWNERS, Owner: SYSDBA */
CREATE TABLE REASSIGNMENT_POTENTIALOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: RTM_ENTITY_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME_EXPRESSION VARCHAR(255),
        TO_STRING_EXPRESSION VARCHAR(255),
        QUICK_FILTER_EXPRESSION VARCHAR(255),
        DEFAULT_ORDER VARCHAR(255),
        PATH_EXPRESSION VARCHAR(255),
        DEFAULT_FOLDER VARCHAR(255),
        SUBENTITY_ONLY boolean,
        RM_PROVIDER VARCHAR(50),
        TO_STRING_QUERY VARCHAR(1024),
        CUSTOM_LIST_COMPONENT VARCHAR(255),
        CUSTOM_HOME_COMPONENT VARCHAR(255),
        CUSTOM_ENTITY_FRAME VARCHAR(255),
        CUSTOM_LIST_FRAME VARCHAR(255),
        QUICK_SEARCH_FIELDS VARCHAR(1024),
PRIMARY KEY (CODE));

/* Table: RTM_ENTITY_FILTER, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FILTER (ID NUMERIC(18, 0) NOT NULL,
        FILTER_PROPERTY VARCHAR(80) NOT NULL,
        CAPTION VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        FILTER_JOIN_STRING VARCHAR(4000),
        FILTER_WHERE_STRING VARCHAR(4000),
        FILTER_PARAM_EXPRESSION VARCHAR(4000),
        FILTER_POS NUMERIC(18, 0),
        FILTER_VALUE_TYPE VARCHAR(80),
        FILTER_HANDLER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_FORM_PANEL, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FORM_PANEL (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CAPTION VARCHAR(255),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        PANEL_POS NUMERIC(18, 0),
        PANEL_TYPE VARCHAR(80) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PARENT_PANEL NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_OPERATION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_OPERATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        OPERATION_EXPRESSION VARCHAR(1024) NOT NULL,
        ENABLED_EXPRESSION VARCHAR(1024) NOT NULL,
        OPERATION_POS NUMERIC(18, 0) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        HIDE_NAME boolean,
        OPERATION_DESCRIPTION VARCHAR(255),
        OPERATION_ICON VARCHAR(1024),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PROPERTY VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_VALIDATOR, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_VALIDATOR (ID NUMERIC(18, 0) NOT NULL,
        VALID_EXPRESSION VARCHAR(1024) NOT NULL,
        INVALID_MESSAGE VARCHAR(255) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        CODE VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_DEFINITION (ID NUMERIC(18, 0) NOT NULL,
        FORMAT VARCHAR(255),
        FIELD_NAME VARCHAR(255),
        DEFAULT_EXPRESSION VARCHAR(255),
        CAPTION VARCHAR(255),
        DATA_LEN NUMERIC(18, 0),
        FIELD_POS NUMERIC(18, 0),
        IS_COLLECTION boolean,
        CALC_EXPRESSION VARCHAR(1024),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        REQUIRED_EXPRESSION VARCHAR(255),
        SHOW_IN_LIST boolean,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        DATA_TYPE VARCHAR(80) NOT NULL,
        ENTITY_PARENT_FIELD NUMERIC(18, 0),
        PANEL NUMERIC(18, 0),
        ENTITY_FILTER VARCHAR(1024),
        EMBEDDED_ENTITY boolean,
        VISUALIZER VARCHAR(255),
        FIELD_HINT VARCHAR(1024),
        SERIALIZER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        PROPERTY VARCHAR(30) NOT NULL,
        FIELD_DEFINITION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_MENU_ITEM, Owner: SYSDBA */
CREATE TABLE RTM_MENU_ITEM (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        WINDOW_NAME VARCHAR(255),
        ITEMPOSITION NUMERIC(18, 0),
        PARENT VARCHAR(30),
        PERMISSION_TARGET VARCHAR(255),
        PERMISSION_ACTION VARCHAR(255),
        EXTERNAL_LINK boolean,
        TARGET_NAME VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: RTM_MODEL_PROPERTY, Owner: SYSDBA */
CREATE TABLE RTM_MODEL_PROPERTY (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: RTM_TYPE_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_TYPE_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TYPE_NAME VARCHAR(80) NOT NULL,
        SERIALIZER VARCHAR(255),
        VER NUMERIC(18, 0),
        INLINE boolean,
        VISUALIZER VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: TESTTABLE1, Owner: SYSDBA */
CREATE TABLE TESTTABLE1 (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: TMP_OLDTABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_OLDTABNUMS (USER_ID NUMERIC(18, 0),
        TABNO VARCHAR(255));

/* Table: TMP_SAVED_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_SAVED_UNIT_CODES (ID NUMERIC(18, 0),
        CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT_CODES (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_TABNUMS (TABNO INTEGER,
        FIO VARCHAR(255),
        BE VARCHAR(255),
        BENAME VARCHAR(255),
        DEP1 VARCHAR(255),
        DEP1NAME VARCHAR(255),
        DEP2 VARCHAR(255),
        DEP2NAME VARCHAR(255),
        USERSFOUND NUMERIC(18, 0),
        USERID NUMERIC(18, 0),
        CNT INTEGER);

/* Table: TMP_USERS, Owner: SYSDBA */
CREATE TABLE TMP_USERS (LOGIN VARCHAR(80),
        PNAME VARCHAR(255),
        CNT INTEGER,
        UNITPATH VARCHAR(80));
