
SET SQL DIALECT 3; 

/* CREATE DATABASE 'aisbd-initial' PAGE_SIZE 4096 DEFAULT CHARACTER SET WIN1251 */


/*  Generators or sequences */
CREATE GENERATOR ATTACHMENT_ID_SEQ;
CREATE GENERATOR BOOLEANEXPR_ID_SEQ;
CREATE GENERATOR COMMENT_ID_SEQ;
CREATE GENERATOR CONTENT_ID_SEQ;
CREATE GENERATOR DEADLINE_ID_SEQ;
CREATE GENERATOR EMAILNOTIFHEAD_ID_SEQ;
CREATE GENERATOR ERM_SEQUENCE;
CREATE GENERATOR ESCALATION_ID_SEQ;
CREATE GENERATOR HIBERNATE_SEQUENCE;
CREATE GENERATOR I18NTEXT_ID_SEQ;
CREATE GENERATOR NOTIFICATION_ID_SEQ;
CREATE GENERATOR REASSIGNMENT_ID_SEQ;
CREATE GENERATOR SESSIONINFO_ID_SEQ;
CREATE GENERATOR WORKITEMINFO_ID_SEQ;


/* Table: CFG_ARTIFACT, Owner: SYSDBA */
CREATE TABLE CFG_ARTIFACT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        VERSION NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLED SMALLINT,
        INSTALL_LOG BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
PRIMARY KEY (ID));

/* Table: CFG_DEPENDENCY, Owner: SYSDBA */
CREATE TABLE CFG_DEPENDENCY (ID NUMERIC(18, 0) NOT NULL,
        DEPENDENCY_CODE VARCHAR(255) NOT NULL,
        DEPENDENCY_VERSION NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PATH VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        INSTALL_ORDER NUMERIC(18, 0) NOT NULL,
        RESOURCE_TYPE NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_PARAM, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255) NOT NULL,
        PARAM_NAME VARCHAR(255) NOT NULL,
        RESOURCE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_TYPE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLER VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: DELEGATION_DELEGATES, Owner: SYSDBA */
CREATE TABLE DELEGATION_DELEGATES (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: ERM_FOLDER, Owner: SYSDBA */
CREATE TABLE ERM_FOLDER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ENTITY_TYPE VARCHAR(80),
        TENANT_ID NUMERIC(18, 0),
        PARENT_ID NUMERIC(18, 0),
        SORT_INDEX INTEGER,
        LBORDER NUMERIC(18, 0),
        RBORDER NUMERIC(18, 0),
        QUERY_DESC NUMERIC(18, 0),
CONSTRAINT PK_ERM_FOLDER PRIMARY KEY (ID));

/* Table: EVENTTYPES, Owner: SYSDBA */
CREATE TABLE EVENTTYPES (INSTANCEID NUMERIC(18, 0) NOT NULL,
        ELEMENT VARCHAR(255));

/* Table: JBPM4_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYMENT (DBID_ NUMERIC(18, 0) NOT NULL,
        NAME_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        TIMESTAMP_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_DEPLOYPROP, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYPROP (DBID_ NUMERIC(18, 0) NOT NULL,
        DEPLOYMENT_ NUMERIC(18, 0),
        OBJNAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        STRINGVAL_ VARCHAR(255),
        LONGVAL_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_EXECUTION, Owner: SYSDBA */
CREATE TABLE JBPM4_EXECUTION (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ACTIVITYNAME_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        HASVARS_ SMALLINT,
        NAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        ID_ VARCHAR(255),
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        HISACTINST_ NUMERIC(18, 0),
        PARENT_ NUMERIC(18, 0),
        INSTANCE_ NUMERIC(18, 0),
        SUPEREXEC_ NUMERIC(18, 0),
        SUBPROCINST_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_),
UNIQUE (ID_));

/* Table: JBPM4_HIST_ACTINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_ACTINST (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        HPROCI_ NUMERIC(18, 0),
        TYPE_ VARCHAR(255),
        EXECUTION_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        TRANSITION_ VARCHAR(255),
        NEXTIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_DETAIL, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_DETAIL (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USERID_ VARCHAR(255),
        TIME_ TIMESTAMP,
        HPROCI_ NUMERIC(18, 0),
        HPROCIIDX_ INTEGER,
        HACTI_ NUMERIC(18, 0),
        HACTIIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
        HTASKIDX_ INTEGER,
        HVAR_ NUMERIC(18, 0),
        HVARIDX_ INTEGER,
        MESSAGE_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        OLD_STR_ VARCHAR(255),
        NEW_STR_ VARCHAR(255),
        OLD_INT_ INTEGER,
        NEW_INT_ INTEGER,
        OLD_TIME_ TIMESTAMP,
        NEW_TIME_ TIMESTAMP,
        PARENT_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_PROCINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_PROCINST (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        KEY_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
        ENDACTIVITY_ VARCHAR(255),
        NEXTIDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        EXECUTION_ VARCHAR(255),
        OUTCOME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        STATE_ VARCHAR(255),
        CREATE_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        NEXTIDX_ INTEGER,
        SUPERTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_VAR, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_VAR (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        PROCINSTID_ VARCHAR(255),
        EXECUTIONID_ VARCHAR(255),
        VARNAME_ VARCHAR(255),
        VALUE_ VARCHAR(255),
        HPROCI_ NUMERIC(18, 0),
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_GROUP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_GROUP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        NAME_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        PARENT_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_MEMBERSHIP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_MEMBERSHIP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USER_ NUMERIC(18, 0),
        GROUP_ NUMERIC(18, 0),
        NAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_USER, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_USER (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PASSWORD_ VARCHAR(255),
        GIVENNAME_ VARCHAR(255),
        FAMILYNAME_ VARCHAR(255),
        BUSINESSEMAIL_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_JOB, Owner: SYSDBA */
CREATE TABLE JBPM4_JOB (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        DUEDATE_ TIMESTAMP,
        STATE_ VARCHAR(255),
        ISEXCLUSIVE_ SMALLINT,
        LOCKOWNER_ VARCHAR(255),
        LOCKEXPTIME_ TIMESTAMP,
        EXCEPTION_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        RETRIES_ INTEGER,
        PROCESSINSTANCE_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        CFG_ NUMERIC(18, 0),
        SIGNAL_ VARCHAR(255),
        EVENT_ VARCHAR(255),
        REPEAT_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_LOB, Owner: SYSDBA */
CREATE TABLE JBPM4_LOB (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        BLOB_VALUE_ BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        DEPLOYMENT_ NUMERIC(18, 0),
        NAME_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
PRIMARY KEY (DBID_));

/* Table: JBPM4_PARTICIPATION, Owner: SYSDBA */
CREATE TABLE JBPM4_PARTICIPATION (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        GROUPID_ VARCHAR(255),
        USERID_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        TASK_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_PROPERTY, Owner: SYSDBA */
CREATE TABLE JBPM4_PROPERTY (KEY_ VARCHAR(255) NOT NULL,
        VERSION_ INTEGER NOT NULL,
        VALUE_ VARCHAR(255),
PRIMARY KEY (KEY_));

/* Table: JBPM4_SWIMLANE, Owner: SYSDBA */
CREATE TABLE JBPM4_SWIMLANE (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        EXECUTION_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ CHAR(1) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        DESCR_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        FORM_ VARCHAR(255),
        PRIORITY_ INTEGER,
        CREATE_ TIMESTAMP,
        DUEDATE_ TIMESTAMP,
        PROGRESS_ INTEGER,
        SIGNALLING_ SMALLINT,
        EXECUTION_ID_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        HASVARS_ SMALLINT,
        SUPERTASK_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        PROCINST_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
        TASKDEFNAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_VARIABLE, Owner: SYSDBA */
CREATE TABLE JBPM4_VARIABLE (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        KEY_ VARCHAR(255),
        CONVERTER_ VARCHAR(255),
        HIST_ SMALLINT,
        EXECUTION_ NUMERIC(18, 0),
        TASK_ NUMERIC(18, 0),
        LOB_ NUMERIC(18, 0),
        DATE_VALUE_ TIMESTAMP,
        DOUBLE_VALUE_ DOUBLE PRECISION,
        CLASSNAME_ VARCHAR(255),
        LONG_VALUE_ NUMERIC(18, 0),
        STRING_VALUE_ VARCHAR(255),
        TEXT_VALUE_ BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        EXESYS_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM5_HT_ATTACHMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ATTACHMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        ACCESSTYPE INTEGER,
        CONTENTTYPE VARCHAR(255),
        ATTACHEDAT TIMESTAMP,
        ATTACHMENT_SIZE INTEGER,
        ATTACHMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        ATTACHEDBY_ID VARCHAR(255),
        TASKDATA_ATTACHMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_BOOL_EXPR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_BOOL_EXPR (ID NUMERIC(18, 0) NOT NULL,
        TYPE VARCHAR(255),
        EXPRESSION BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        ESCALATION_CONSTRAINTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_COMMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_COMMENT (ID NUMERIC(18, 0) NOT NULL,
        TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        ADDEDAT TIMESTAMP,
        ADDEDBY_ID VARCHAR(255),
        TASKDATA_COMMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_CONTENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_CONTENT (ID NUMERIC(18, 0) NOT NULL,
        CONTENT BLOB SUB_TYPE 0 SEGMENT SIZE 80,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_DEADLINE, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_DEADLINE (ID NUMERIC(18, 0) NOT NULL,
        DEADLINE_DATE TIMESTAMP,
        ESCALATED SMALLINT NOT NULL,
        DEADLINES_ENDDEADLINE_ID NUMERIC(18, 0),
        DEADLINES_STARTDEADLINE_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_ESCALATION, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ESCALATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        DEADLINE_ESCALATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_I18N_TEXT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_I18N_TEXT (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        TASK_DESCRIPTIONS_ID NUMERIC(18, 0),
        TASK_SUBJECTS_ID NUMERIC(18, 0),
        TASK_NAMES_ID NUMERIC(18, 0),
        REASSIGNMENT_DOCUMENTATION_ID NUMERIC(18, 0),
        NOTIFICATION_DESCRIPTIONS_ID NUMERIC(18, 0),
        NOTIFICATION_SUBJECTS_ID NUMERIC(18, 0),
        NOTIFICATION_NAMES_ID NUMERIC(18, 0),
        NOTIFICATION_DOCUMENTATION_ID NUMERIC(18, 0),
        DEADLINE_DOCUMENTATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_MAILNHDR (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        REPLYTOADDRESS VARCHAR(255),
        FROMADDRESS VARCHAR(255),
        SUBJECT VARCHAR(255),
        BODY BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N (DTYPE VARCHAR(31) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ESCALATION_NOTIFICATIONS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N_JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR (JBPM5_HT_N10N_ID NUMERIC(18, 0) NOT NULL,
        EMAILHEADERS_ID NUMERIC(18, 0) NOT NULL,
        MAPKEY VARCHAR(255) NOT NULL,
PRIMARY KEY (JBPM5_HT_N10N_ID, MAPKEY),
UNIQUE (EMAILHEADERS_ID));

/* Table: JBPM5_HT_ORG_ENTITY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ORG_ENTITY (DTYPE VARCHAR(31) NOT NULL,
        ID VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_REASSIGNMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_REASSIGNMENT (ID NUMERIC(18, 0) NOT NULL,
        ESCALATION_REASSIGNMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_SUBTASK_STRATEGY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_SUBTASK_STRATEGY (DTYPE VARCHAR(100) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TASK_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_TASK, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_TASK (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ALLOWEDTODELEGATE VARCHAR(255),
        STATUS VARCHAR(255),
        PREVIOUSSTATUS INTEGER,
        CREATEDON TIMESTAMP,
        ACTIVATIONTIME TIMESTAMP,
        EXPIRATIONTIME TIMESTAMP,
        SKIPABLE SMALLINT NOT NULL,
        WORKITEMID NUMERIC(18, 0) NOT NULL,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        DOCUMENTACCESSTYPE INTEGER,
        DOCUMENTTYPE VARCHAR(255),
        DOCUMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        OUTPUTACCESSTYPE INTEGER,
        OUTPUTTYPE VARCHAR(255),
        OUTPUTCONTENTID NUMERIC(18, 0) NOT NULL,
        FAULTNAME VARCHAR(255),
        FAULTACCESSTYPE INTEGER,
        FAULTTYPE VARCHAR(255),
        FAULTCONTENTID NUMERIC(18, 0) NOT NULL,
        PARENTID NUMERIC(18, 0) NOT NULL,
        PROCESSID VARCHAR(255),
        PROCESSKEY VARCHAR(255),
        PROCESSSESSIONID INTEGER NOT NULL,
        TASKINITIATOR_ID VARCHAR(255),
        CREATEDBY_ID VARCHAR(255),
        ACTUALOWNER_ID VARCHAR(255),
        OPTLOCK INTEGER,
        ARCHIVED SMALLINT,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (ID));

/* Table: JBPM5_PROCINST_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_PROCINST_INFO (INSTANCEID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        PROCESSID VARCHAR(255),
        STARTDATE TIMESTAMP,
        LASTREADDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        STATE INTEGER NOT NULL,
        PROCESSINSTANCEBYTEARRAY BLOB SUB_TYPE 0 SEGMENT SIZE 80,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (INSTANCEID));

/* Table: JBPM5_SESSION_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO (ID INTEGER NOT NULL,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY BLOB SUB_TYPE 0 SEGMENT SIZE 80,
PRIMARY KEY (ID));

/* Table: JBPM5_WORKITEM_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_WORKITEM_INFO (WORKITEMID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        NAME VARCHAR(255),
        CREATIONDATE TIMESTAMP,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        STATE NUMERIC(18, 0) NOT NULL,
        WORKITEMBYTEARRAY BLOB SUB_TYPE 0 SEGMENT SIZE 80,
PRIMARY KEY (WORKITEMID));

/* Table: JB_JOB_TYPE, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ACTION VARCHAR(255) NOT NULL,
        FIRST_DATE_EXPRESSION VARCHAR(255) NOT NULL,
        PERIOD_EXPRESSION VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: JB_JOB_TYPE_PARAM, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        VALUE_EXPRESSION VARCHAR(255),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB (ID NUMERIC(18, 0) NOT NULL,
        START_DATE TIMESTAMP,
        ACTION VARCHAR(255) NOT NULL,
        JOB_KEY VARCHAR(255) NOT NULL,
        PERIOD_VALUE NUMERIC(18, 0),
        LAST_ERROR VARCHAR(1024),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB_PARAM, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB_PARAM (ID NUMERIC(18, 0) NOT NULL,
        STRING_VALUE VARCHAR(255),
        CODE VARCHAR(255) NOT NULL,
        DOUBLE_VALUE DOUBLE PRECISION,
        DATE_VALUE TIMESTAMP,
        SCHEDULED_JOB NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: MSG_USER_MESSAGE, Owner: SYSDBA */
CREATE TABLE MSG_USER_MESSAGE (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY NUMERIC(18, 0),
        SUBJECT VARCHAR(255),
        BODY BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        "READ" SMALLINT,
        DRAFT SMALLINT,
        ARCHIVE SMALLINT,
        MESSAGE_DATE TIMESTAMP,
        USER_FROM NUMERIC(18, 0),
        USER_TO NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0) NOT NULL,
        IS_READ SMALLINT,
PRIMARY KEY (ID));

/* Table: NOTIFICATION_BAS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: NOTIFICATION_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: OC_COMMON_USER, Owner: SYSDBA */
CREATE TABLE OC_COMMON_USER (ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_CUSTOM_PAGE, Owner: SYSDBA */
CREATE TABLE OC_CUSTOM_PAGE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(254) NOT NULL,
        PAGE_TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        PAGE_TYPE VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: OC_ENTITY_LOCK, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_LOCK (ID NUMERIC(18, 0) NOT NULL,
        LOCK_DATE DATE,
        LOCKED_ENTITY_NAME VARCHAR(255),
        LOCKED_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_ENTITY_WORD, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_WORD (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(80) NOT NULL,
        ENTITY_ID_STRING VARCHAR(80),
        ENTITY_ID_LONG NUMERIC(18, 0),
        THEWORD VARCHAR(80),
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT2ENT_FLD_EXPR, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT2ENT_FLD_EXPR (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255),
        EXPRESSION VARCHAR(255),
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        PROCESS_ENTITY_CHECK_EXPR VARCHAR(255),
        PROCESS_ORDER NUMERIC(18, 0),
        IS_ACTIVE SMALLINT,
        EXTERNAL_SYSTEM NUMERIC(18, 0) NOT NULL,
        CHECK_DUPLICATE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_EXT_ENTITY2ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY2ENTITY (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FIELD_TYPE VARCHAR(255),
        CODE VARCHAR(30) NOT NULL,
        FIELD_POSITION NUMERIC(18, 0),
        KEY_POSITION NUMERIC(18, 0),
        EXTERNAL_ENTITY_REFERENCE NUMERIC(18, 0),
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_FLD2FLD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_FLD2FLD (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255) NOT NULL,
        REFERENCED_ENTITY_FIELD_NAME VARCHAR(255),
        EXTERNAL_ENTITY_FIELD NUMERIC(18, 0) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_ID2ID, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_ID2ID (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(255) NOT NULL,
        PK_VALUE VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_PROCESSED_KEYS, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_PROCESSED_KEYS (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(30) NOT NULL,
        GUID VARCHAR(255) NOT NULL,
        COUNTER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_SYSTEM, Owner: SYSDBA */
CREATE TABLE OC_EXT_SYSTEM (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255) NOT NULL,
        IS_ACTIVE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_GROUP_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_GROUP_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_GROUP_ROLE, Owner: SYSDBA */
CREATE TABLE OC_GROUP_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255),
        PROCESS_KEY VARCHAR(255),
        LATEST SMALLINT,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
        LATEST_FOR_PROCESS_ID SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SEL_CRITERIA_CLASS VARCHAR(255),
        SEL_CRITERIA_EXPR VARCHAR(255),
        SEL_CRITERIA_PARAMS_EXPR VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        CONDITION VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
        VAR VARCHAR(255),
        VAR_POSITION NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_DEPLOYMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DEPLOYMENT_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCEXT_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCEXT_RSRC (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROC_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROC_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_NAME VARCHAR(255),
        PROCESS_KEY VARCHAR(255) NOT NULL,
        LATEST SMALLINT,
        PROCESS_VERSION NUMERIC(18, 0) NOT NULL,
        DISABLED SMALLINT,
        PACKAGE_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(1024) NOT NULL,
        RESOURCE_CONTENT BLOB SUB_TYPE 0 SEGMENT SIZE 80 NOT NULL,
        DEPLOYMENT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TASK_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_VAR (ID NUMERIC(18, 0) NOT NULL,
        OPT_LOCK NUMERIC(18, 0),
        STRING_VALUE VARCHAR(1024),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        LONG_VALUE NUMERIC(18, 0),
        INTEGER_VALUE INTEGER,
        BOOLEAN_VALUE SMALLINT,
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        CONVERTER_TYPE_CODE VARCHAR(30),
        LONG_STRING_VALUE BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        TASK NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (TASK, VARIABLE_NAME));

/* Table: OC_JPDL4EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(255),
        PROCESS_DEFINITION_KEY VARCHAR(255),
        PROCESS_DEFINITION_VERSION NUMERIC(18, 0),
        LATEST SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SELECTION_CRITERIA_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        CONDITION VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_PAGE_TYPE, Owner: SYSDBA */
CREATE TABLE OC_PAGE_TYPE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: OC_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION_TARGET VARCHAR(255) NOT NULL,
        PERMISSION_ACTION VARCHAR(255) NOT NULL,
        PERMISSION_DESCRIPTION VARCHAR(1024),
        PERMISSION_CATEGORY NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_PERMISSION_CATEGORY, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION_CATEGORY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY, Owner: SYSDBA */
CREATE TABLE OC_QUERY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
        QUERY_TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        QUERY_TYPE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_QUERY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        FLD_LENGTH NUMERIC(18, 0),
        FIELD_NAME VARCHAR(255),
        POS NUMERIC(18, 0) NOT NULL,
        FIELD_TYPE VARCHAR(255) NOT NULL,
        EXPRESSION VARCHAR(1024),
        FIELD_DESCRIPTION VARCHAR(255),
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_PARAM, Owner: SYSDBA */
CREATE TABLE OC_QUERY_PARAM (ID NUMERIC(18, 0) NOT NULL,
        POS NUMERIC(18, 0) NOT NULL,
        REQUIRED SMALLINT,
        EXPRESSION VARCHAR(1024),
        PARAM_TYPE VARCHAR(255),
        CAPTION VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        MANUAL_INPUT SMALLINT,
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_TYPE, Owner: SYSDBA */
CREATE TABLE OC_QUERY_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_DESC, Owner: SYSDBA */
CREATE TABLE OC_REPORT_DESC (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        ENTITY_CLASS VARCHAR(255),
        TEMPLATE_FILE_NAME VARCHAR(255),
        DEFAULT_OUTPUT_FORMAT VARCHAR(255),
        ENGINE NUMERIC(18, 0) NOT NULL,
        MASTER_QUERY NUMERIC(18, 0),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_ENGINE, Owner: SYSDBA */
CREATE TABLE OC_REPORT_ENGINE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_ROLE_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_ROLE_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_SCRIPT, Owner: SYSDBA */
CREATE TABLE OC_SCRIPT (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255),
        FULL_NAME VARCHAR(255),
        SCRIPT_TEXT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        SCRIPT_POSITION NUMERIC(18, 0),
        SCRIPT_ACTIVE SMALLINT,
PRIMARY KEY (CODE));

/* Table: OC_SECURITY_GROUP, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_GROUP (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_SECURITY_ROLE, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_ROLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_SECURITY_USER, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_USER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        USER_PASSWORD VARCHAR(80) NOT NULL,
        USER_LOGIN VARCHAR(30) NOT NULL,
        X509CERTIFICATE_COMMON_NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        USER_DISABLED SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_TENANT, Owner: SYSDBA */
CREATE TABLE OC_TENANT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        HOST_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_TENANT_USER, Owner: SYSDBA */
CREATE TABLE OC_TENANT_USER (ID NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_TYPED_PRINCIPAL_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_TYPED_PRINCIPAL_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PRINCIPAL_UUID VARCHAR(255),
        PERMISSION NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_USERPROFILE_PARAM, Owner: SYSDBA */
CREATE TABLE OC_USERPROFILE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GRANTED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_GRANTED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GROUP, Owner: SYSDBA */
CREATE TABLE OC_USER_GROUP (ID NUMERIC(18, 0) NOT NULL,
        TENANT_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_REVOKED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_REVOKED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_ROLE, Owner: SYSDBA */
CREATE TABLE OC_USER_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_ZERO_STATE, Owner: SYSDBA */
CREATE TABLE OC_ZERO_STATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        APOSITION NUMERIC(18, 0) NOT NULL,
        SELECT_HQL VARCHAR(1024),
        PROCESS_COLLECTIONS SMALLINT,
        BEFORE_IMPORT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        AFTER_IMPORT BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
        PERSIST_REFERENCES SMALLINT,
PRIMARY KEY (CODE),
UNIQUE (APOSITION));

/* Table: PEOPLEASSIGNMENTS_BAS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_EXCLOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_EXCLOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_POTOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_POTOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_STAKEHOLDERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: REASSIGNMENT_POTENTIALOWNERS, Owner: SYSDBA */
CREATE TABLE REASSIGNMENT_POTENTIALOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: RTM_ENTITY_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME_EXPRESSION VARCHAR(255),
        TO_STRING_EXPRESSION VARCHAR(255),
        QUICK_FILTER_EXPRESSION VARCHAR(255),
        DEFAULT_ORDER VARCHAR(255),
        PATH_EXPRESSION VARCHAR(255),
        DEFAULT_FOLDER VARCHAR(255),
        SUBENTITY_ONLY SMALLINT,
        RM_PROVIDER VARCHAR(50),
        TO_STRING_QUERY VARCHAR(1024),
        CUSTOM_LIST_COMPONENT VARCHAR(255),
        CUSTOM_HOME_COMPONENT VARCHAR(255),
        CUSTOM_ENTITY_FRAME VARCHAR(255),
        CUSTOM_LIST_FRAME VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: RTM_ENTITY_FILTER, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FILTER (ID NUMERIC(18, 0) NOT NULL,
        FILTER_PROPERTY VARCHAR(80) NOT NULL,
        CAPTION VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        FILTER_JOIN_STRING VARCHAR(4000),
        FILTER_WHERE_STRING VARCHAR(4000),
        FILTER_PARAM_EXPRESSION VARCHAR(4000),
        FILTER_POS NUMERIC(18, 0),
        FILTER_VALUE_TYPE VARCHAR(80),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_FORM_PANEL, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FORM_PANEL (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CAPTION VARCHAR(255),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        PANEL_POS NUMERIC(18, 0),
        PANEL_TYPE VARCHAR(80) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PARENT_PANEL NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_OPERATION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_OPERATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        OPERATION_EXPRESSION VARCHAR(255) NOT NULL,
        ENABLED_EXPRESSION VARCHAR(255) NOT NULL,
        OPERATION_POS NUMERIC(18, 0) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PROPERTY VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_VALIDATOR, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_VALIDATOR (ID NUMERIC(18, 0) NOT NULL,
        VALID_EXPRESSION VARCHAR(1024) NOT NULL,
        INVALID_MESSAGE VARCHAR(255) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        CODE VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_DEFINITION (ID NUMERIC(18, 0) NOT NULL,
        FORMAT VARCHAR(255),
        FIELD_NAME VARCHAR(255),
        DEFAULT_EXPRESSION VARCHAR(255),
        CAPTION VARCHAR(255),
        DATA_LEN NUMERIC(18, 0),
        FIELD_POS NUMERIC(18, 0),
        IS_COLLECTION SMALLINT,
        CALC_EXPRESSION VARCHAR(255),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        REQUIRED_EXPRESSION VARCHAR(255),
        SHOW_IN_LIST SMALLINT,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        DATA_TYPE VARCHAR(80) NOT NULL,
        ENTITY_PARENT_FIELD NUMERIC(18, 0),
        PANEL NUMERIC(18, 0),
        ENTITY_FILTER VARCHAR(1024),
        EMBEDDED_ENTITY SMALLINT,
        VISUALIZER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        PROPERTY VARCHAR(30) NOT NULL,
        FIELD_DEFINITION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_MENU_ITEM, Owner: SYSDBA */
CREATE TABLE RTM_MENU_ITEM (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        WINDOW_NAME VARCHAR(255),
        ITEMPOSITION NUMERIC(18, 0),
        PARENT VARCHAR(30),
        PERMISSION_TARGET VARCHAR(255),
        PERMISSION_ACTION VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: RTM_MODEL_PROPERTY, Owner: SYSDBA */
CREATE TABLE RTM_MODEL_PROPERTY (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: RTM_TYPE_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_TYPE_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TYPE_NAME VARCHAR(80) NOT NULL,
        SERIALIZER VARCHAR(255),
        VER NUMERIC(18, 0),
        INLINE SMALLINT,
        VISUALIZER VARCHAR(255),
PRIMARY KEY (CODE));

/*  Index definitions for all user tables */
CREATE INDEX IDX_EVENTTYPES1 ON EVENTTYPES (ELEMENT);
CREATE INDEX IDX_DEPLPROP_DEPL ON JBPM4_DEPLOYPROP (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP1 ON JBPM4_DEPLOYPROP (OBJNAME_, KEY_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP2 ON JBPM4_DEPLOYPROP (STRINGVAL_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP3 ON JBPM4_DEPLOYPROP (KEY_);
CREATE INDEX IDX_EXEC_INSTANCE ON JBPM4_EXECUTION (INSTANCE_);
CREATE INDEX IDX_EXEC_PARENT ON JBPM4_EXECUTION (PARENT_);
CREATE INDEX IDX_EXEC_SUBPI ON JBPM4_EXECUTION (SUBPROCINST_);
CREATE INDEX IDX_EXEC_SUPEREXEC ON JBPM4_EXECUTION (SUPEREXEC_);
CREATE INDEX IDX_JBPM4_EXECUTION1 ON JBPM4_EXECUTION (PROCDEFID_);
CREATE INDEX IDX_HACTI_HPROCI ON JBPM4_HIST_ACTINST (HPROCI_);
CREATE INDEX IDX_HTI_HTASK ON JBPM4_HIST_ACTINST (HTASK_);
CREATE INDEX IDX_HDET_HACTI ON JBPM4_HIST_DETAIL (HACTI_);
CREATE INDEX IDX_HDET_HPROCI ON JBPM4_HIST_DETAIL (HPROCI_);
CREATE INDEX IDX_HDET_HTASK ON JBPM4_HIST_DETAIL (HTASK_);
CREATE INDEX IDX_HDET_HVAR ON JBPM4_HIST_DETAIL (HVAR_);
CREATE INDEX IDX_JBPM4_HIST_PROCINST1 ON JBPM4_HIST_PROCINST (PROCDEFID_);
CREATE INDEX IDX_HSUPERT_SUB ON JBPM4_HIST_TASK (SUPERTASK_);
CREATE INDEX IDX_HVAR_HPROCI ON JBPM4_HIST_VAR (HPROCI_);
CREATE INDEX IDX_HVAR_HTASK ON JBPM4_HIST_VAR (HTASK_);
CREATE INDEX IDX_JBPM4_HIST_VAR_1 ON JBPM4_HIST_VAR (PROCINSTID_, VARNAME_, VALUE_);
CREATE INDEX IDX_GROUP_PARENT ON JBPM4_ID_GROUP (PARENT_);
CREATE INDEX IDX_MEM_GROUP ON JBPM4_ID_MEMBERSHIP (GROUP_);
CREATE INDEX IDX_MEM_USER ON JBPM4_ID_MEMBERSHIP (USER_);
CREATE INDEX IDX_JOBDUEDATE ON JBPM4_JOB (DUEDATE_);
CREATE INDEX IDX_JOBLOCKEXP ON JBPM4_JOB (LOCKEXPTIME_);
CREATE INDEX IDX_JOBRETRIES ON JBPM4_JOB (RETRIES_);
CREATE INDEX IDX_JOB_CFG ON JBPM4_JOB (CFG_);
CREATE INDEX IDX_JOB_EXE ON JBPM4_JOB (EXECUTION_);
CREATE INDEX IDX_JOB_PRINST ON JBPM4_JOB (PROCESSINSTANCE_);
CREATE INDEX IDX_LOB_DEPLOYMENT ON JBPM4_LOB (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_PARTICIPATION1 ON JBPM4_PARTICIPATION (TASK_, TYPE_, USERID_);
CREATE INDEX IDX_PART_TASK ON JBPM4_PARTICIPATION (TASK_);
CREATE INDEX IDX_SWIMLANE_EXEC ON JBPM4_SWIMLANE (EXECUTION_);
CREATE INDEX IDX_JBPM4_TASK1 ON JBPM4_TASK (ASSIGNEE_);
CREATE INDEX IDX_TASK_SUPERTASK ON JBPM4_TASK (SUPERTASK_);
CREATE INDEX IDX_JBPM4_VARIABLE1 ON JBPM4_VARIABLE (CLASS_, KEY_, STRING_VALUE_);
CREATE INDEX IDX_VAR_EXECUTION ON JBPM4_VARIABLE (EXECUTION_);
CREATE INDEX IDX_VAR_EXESYS ON JBPM4_VARIABLE (EXESYS_);
CREATE INDEX IDX_VAR_LOB ON JBPM4_VARIABLE (LOB_);
CREATE INDEX IDX_VAR_TASK ON JBPM4_VARIABLE (TASK_);
CREATE INDEX IDX_OC_JBPM5EXT_PROCDEF_EXT1 ON OC_JBPM5EXT_PROCDEF_EXTENSION (PROCESS_ID);
CREATE INDEX IDX_OC_JPDL4EXT_PROCDEF_EXT1 ON OC_JPDL4EXT_PROCDEF_EXTENSION (PROCESS_DEFINITION_KEY, PROCESS_DEFINITION_VERSION);
CREATE INDEX IDX_OC_PERMISSION1 ON OC_PERMISSION (PERMISSION_TARGET, PERMISSION_ACTION);

ALTER TABLE CFG_DEPENDENCY ADD CONSTRAINT FKB6719226DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DB901B50 FOREIGN KEY (RESOURCE_TYPE) REFERENCES CFG_RESOURCE_TYPE (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE_PARAM ADD CONSTRAINT FK7A56567745CA4CB9 FOREIGN KEY (RESOURCE) REFERENCES CFG_RESOURCE (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D572C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D5736B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE EVENTTYPES ADD CONSTRAINT FKB0E5621F7665489A FOREIGN KEY (INSTANCEID) REFERENCES JBPM5_PROCINST_INFO (INSTANCEID);

ALTER TABLE JBPM4_DEPLOYPROP ADD CONSTRAINT FK_DEPLPROP_DEPL FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_INSTANCE FOREIGN KEY (INSTANCE_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUBPI FOREIGN KEY (SUBPROCINST_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUPEREXEC FOREIGN KEY (SUPEREXEC_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HACTI_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HTI_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HACTI FOREIGN KEY (HACTI_) REFERENCES JBPM4_HIST_ACTINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HVAR FOREIGN KEY (HVAR_) REFERENCES JBPM4_HIST_VAR (DBID_);

ALTER TABLE JBPM4_HIST_TASK ADD CONSTRAINT FK_HSUPERT_SUB FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_ID_GROUP ADD CONSTRAINT FK_GROUP_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_GROUP FOREIGN KEY (GROUP_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_USER FOREIGN KEY (USER_) REFERENCES JBPM4_ID_USER (DBID_);

ALTER TABLE JBPM4_JOB ADD CONSTRAINT FK_JOB_CFG FOREIGN KEY (CFG_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_LOB ADD CONSTRAINT FK_LOB_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_SWIMLANE FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_SWIMLANE ADD CONSTRAINT FK_SWIMLANE_EXEC FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SUPERTASK FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SWIML FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXECUTION FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXESYS FOREIGN KEY (EXESYS_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_LOB FOREIGN KEY (LOB_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD78EF5F064 FOREIGN KEY (ATTACHEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD7F21826D9 FOREIGN KEY (TASKDATA_ATTACHMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_BOOL_EXPR ADD CONSTRAINT FK3690AAF6AFB75F7D FOREIGN KEY (ESCALATION_CONSTRAINTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0B2FF04688 FOREIGN KEY (ADDEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0BB35E68F5 FOREIGN KEY (TASKDATA_COMMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C27ABEB8A FOREIGN KEY (DEADLINES_ENDDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C684BACA3 FOREIGN KEY (DEADLINES_STARTDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_ESCALATION ADD CONSTRAINT FK8459BF49C7A04C70 FOREIGN KEY (DEADLINE_ESCALATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A2162DFB4 FOREIGN KEY (NOTIFICATION_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A3330F6D9 FOREIGN KEY (DEADLINE_DOCUMENTATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A5EEBB6D9 FOREIGN KEY (REASSIGNMENT_DOCUMENTATION_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A69B21EE8 FOREIGN KEY (TASK_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A8046A239 FOREIGN KEY (NOTIFICATION_DOCUMENTATION_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A98B62B FOREIGN KEY (TASK_NAMES_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AB2FA6B18 FOREIGN KEY (TASK_SUBJECTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AD488CEEB FOREIGN KEY (NOTIFICATION_NAMES_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AF952CEE4 FOREIGN KEY (NOTIFICATION_SUBJECTS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_N10N ADD CONSTRAINT FKA36CB2B53E0890B FOREIGN KEY (ESCALATION_NOTIFICATIONS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A91F7B912A FOREIGN KEY (EMAILHEADERS_ID) REFERENCES JBPM5_HT_MAILNHDR (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A98EE05A12 FOREIGN KEY (JBPM5_HT_N10N_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_REASSIGNMENT ADD CONSTRAINT FK11824F4A5C17EE0 FOREIGN KEY (ESCALATION_REASSIGNMENTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_SUBTASK_STRATEGY ADD CONSTRAINT FK8C53C08136B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD396CE1EF3A FOREIGN KEY (ACTUALOWNER_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD399E619A0 FOREIGN KEY (CREATEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD39F213F8B5 FOREIGN KEY (TASKINITIATOR_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JB_JOB_TYPE_PARAM ADD CONSTRAINT FKB413F6F165EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB ADD CONSTRAINT FK9447C66465EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB_PARAM ADD CONSTRAINT FK673EE6F2D83EF726 FOREIGN KEY (SCHEDULED_JOB) REFERENCES JB_SCHEDULED_JOB (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1D46DC060 FOREIGN KEY (USER_TO) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1F1695C8F FOREIGN KEY (USER_FROM) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE02C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE09C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E9C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE OC_COMMON_USER ADD CONSTRAINT FK940943B41BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_CUSTOM_PAGE ADD CONSTRAINT FK9CCD5CB24CB60E09 FOREIGN KEY (PAGE_TYPE) REFERENCES OC_PAGE_TYPE (CODE);

ALTER TABLE OC_EXT_ENT2ENT_FLD_EXPR ADD CONSTRAINT FK51B13C1ACA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY ADD CONSTRAINT FKEC84FB0CF0ECEDE4 FOREIGN KEY (EXTERNAL_SYSTEM) REFERENCES OC_EXT_SYSTEM (ID);

ALTER TABLE OC_EXT_ENTITY2ENTITY ADD CONSTRAINT FK641E3609BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607B027AA58 FOREIGN KEY (EXTERNAL_ENTITY_REFERENCE) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836D2DDA4D17 FOREIGN KEY (EXTERNAL_ENTITY_FIELD) REFERENCES OC_EXT_ENTITY_FIELD (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836DCA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENT_ID2ID ADD CONSTRAINT FKF5665DB5CA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69A12F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69AFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D1958112F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D19581F1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_JBPM5EXT_ATTRIBUTE ADD CONSTRAINT FK2B5A04A93572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_PROCESS_VARIABLE ADD CONSTRAINT FKE07A5F9F3572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VALIDATION ADD CONSTRAINT FKFC6F0FC03572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833EAF2F98 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JBPM5EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JBPM5REPO_PROCEXT_RSRC ADD CONSTRAINT FK9B6B8DBEE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_PROC_RESOURCE ADD CONSTRAINT FKF19E98FFE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_RESOURCE ADD CONSTRAINT FK971FA4E6567B3CB3 FOREIGN KEY (DEPLOYMENT) REFERENCES OC_JBPM5REPO_DEPLOYMENT (ID);

ALTER TABLE OC_JBPM5_TASK_VAR ADD CONSTRAINT FKA4BF6AF7928994C4 FOREIGN KEY (TASK) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE OC_JPDL4EXT_ATTRIBUTE ADD CONSTRAINT FKC6148E6350B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_PROCESS_VARIABLE ADD CONSTRAINT FK9B1E50A550B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VALIDATION ADD CONSTRAINT FKC8A5E5FA50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D27F42577 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JPDL4EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_PERMISSION ADD CONSTRAINT FK8686E11AF1EBAB7 FOREIGN KEY (PERMISSION_CATEGORY) REFERENCES OC_PERMISSION_CATEGORY (ID);

ALTER TABLE OC_QUERY ADD CONSTRAINT FK2836DA9D59C34F46 FOREIGN KEY (QUERY_TYPE) REFERENCES OC_QUERY_TYPE (ID);

ALTER TABLE OC_QUERY_FIELD ADD CONSTRAINT FKCF48B4D86A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_QUERY_PARAM ADD CONSTRAINT FKCFD22C6B6A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D133F526F7 FOREIGN KEY (MASTER_QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D1A985BF25 FOREIGN KEY (ENGINE) REFERENCES OC_REPORT_ENGINE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_SECURITY_GROUP ADD CONSTRAINT FK77A5DE8BDBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E4551BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E455DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TYPED_PRINCIPAL_PERMISSION ADD CONSTRAINT FK3DA89080FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USERPROFILE_PARAM ADD CONSTRAINT FKF9E5E2E1F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C5612F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C564DD86731 FOREIGN KEY (TENANT_USER) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C568C6EA467 FOREIGN KEY (TENANT_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E42C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E436B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C22C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C236B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D52C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D536B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFF2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFFE17E130F FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE RTM_ENTITY_DEFINITION ADD CONSTRAINT FKAE4EB63BED0054E FOREIGN KEY (CODE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK6243006039AA7BD0 FOREIGN KEY (FILTER_VALUE_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK62430060F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B170CE9EC6 FOREIGN KEY (PARENT_PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B1F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_OPERATION ADD CONSTRAINT FK6AAD977FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_ENTITY_VALIDATOR ADD CONSTRAINT FKC56CCD6AF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C2389DA9B FOREIGN KEY (PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C238C53A FOREIGN KEY (ENTITY_PARENT_FIELD) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF8F8EA10 FOREIGN KEY (DATA_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E083419AF1 FOREIGN KEY (FIELD_DEFINITION) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E0F919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_MENU_ITEM ADD CONSTRAINT FK147B8FFC08A43F7 FOREIGN KEY (PARENT) REFERENCES RTM_MENU_ITEM (CODE);
COMMIT WORK;
SET AUTODDL OFF;
SET TERM ^ ;

/* Stored procedures */
CREATE PROCEDURE ADD_FIELD (ENTITY VARCHAR(255) CHARACTER SET WIN1251,
FN VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
DT VARCHAR(255) CHARACTER SET WIN1251,
PANEL VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (F_ID NUMERIC(18, 0))
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE CALC_COUNTS RETURNS (CNT INTEGER,
TABLENAME VARCHAR(32) CHARACTER SET WIN1251)
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE CLEARDEFS AS 
BEGIN EXIT; END ^
CREATE PROCEDURE CREATE_ACTENTITYDEFINITION (DT VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
ROOT VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (ID NUMERIC(18, 0))
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE CREATE_ENTITYDEFINITION (DT VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
ROOT VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (ID NUMERIC(18, 0))
AS 
BEGIN SUSPEND; END ^
CREATE PROCEDURE RENAME_DEFINITION (OLD_TYPE VARCHAR(80) CHARACTER SET WIN1251,
NEW_TYPE VARCHAR(80) CHARACTER SET WIN1251)
RETURNS (RESULT INTEGER)
AS 
BEGIN SUSPEND; END ^

ALTER PROCEDURE ADD_FIELD (ENTITY VARCHAR(255) CHARACTER SET WIN1251,
FN VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
DT VARCHAR(255) CHARACTER SET WIN1251,
PANEL VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (F_ID NUMERIC(18, 0))
AS 
declare variable ENT_ID varchar(255);
declare variable DT_ID varchar(255);
declare variable PANEL_ID numeric(18,0);
declare variable pos numeric(18,0);
begin



select first 1 ed.code from rtm_entity_definition ed, rtm_type_definition td
where ed.code = td.code and td.type_name = :entity
order by td.ver desc
into :ent_id;

select p.id from rtm_entity_form_panel p
where p.entity_definition = :ent_id and p.name = :panel
into :panel_id;

select max(fd.field_pos) + 10 from RTM_FIELD_DEFINITION fd where fd.entity_definition = :ent_id
into :pos;
if (:pos is null) then
begin
    pos = 10;
end


select first 1 td.code from rtm_type_definition td
where td.type_name = :dt
order by td.ver desc
into :dt_id;

select gen_id(hibernate_sequence, 1) from rdb$database into :f_id;

  
insert into RTM_FIELD_DEFINITION
(ID, FORMAT, FIELD_NAME, DEFAULT_EXPRESSION, CAPTION, DATA_LEN, FIELD_POS, IS_COLLECTION, CALC_EXPRESSION, VISIBLE_EXPRESSION, WRITABLE_EXPRESSION, REQUIRED_EXPRESSION, SHOW_IN_LIST, ENTITY_DEFINITION, DATA_TYPE, ENTITY_PARENT_FIELD, PANEL, ENTITY_FILTER)
values
(:f_id, '', :fn, '', :caption, 255, :pos, 0, '', '', '', '', 1, :ent_id, :dt_id, null, :panel_id, null);
  suspend;
end ^

ALTER PROCEDURE CALC_COUNTS RETURNS (CNT INTEGER,
TABLENAME VARCHAR(32) CHARACTER SET WIN1251)
AS 
begin
  for select  trim(rdb$relation_name) from rdb$relations
  where rdb$relation_name not like '%$%'
  order by rdb$relation_name
  into :tablename do
  begin
  execute statement 'select count(*) from ' ||  :tablename
  into :cnt;
  suspend;
  end
end ^

ALTER PROCEDURE CLEARDEFS AS 
begin
    delete from rtm_entity_filter;
    delete from rtm_entity_operation;
    delete from rtm_entity_property_value;
    delete from rtm_field_property_value;
    delete from rtm_entity_validator;
    update rtm_field_definition f set f.entity_parent_field = null where f.entity_parent_field is not null;
    delete from rtm_field_definition;
    update rtm_entity_form_panel p set p.parent_panel = null where p.parent_panel is not null;
    delete from rtm_entity_form_panel;
    delete from rtm_entity_definition;
    delete from rtm_type_definition;
end ^

ALTER PROCEDURE CREATE_ACTENTITYDEFINITION (DT VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
ROOT VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (ID NUMERIC(18, 0))
AS 
declare variable CODE varchar(255);
begin

    -- select gen_id(hibernate_sequence, 1) from rdb$database into :id;

    code = dt || ':1';
    
insert into RTM_TYPE_DEFINITION (CODE, NAME, TYPE_NAME, SERIALIZER, VER, INLINE, VISUALIZER)
values (:code, :caption, :dt, null, 1, 0, null);

insert into RTM_ENTITY_DEFINITION (CODE, NAME_EXPRESSION, TO_STRING_EXPRESSION, QUICK_FILTER_EXPRESSION, DEFAULT_ORDER, PATH_EXPRESSION, DEFAULT_FOLDER, SUBENTITY_ONLY)
 values (:code, '#{instance.docNumber}', '#{instance.docNumber}', null, null, null, :root, 0);

-- select * from add_field(:dt,  'code', 'Код', 'java.lang.String', null)
-- into :id;
 select gen_id(hibernate_sequence, 1) from rdb$database
 into  :id;

 insert into rtm_entity_form_panel(id, name, caption, panel_type, entity_definition, parent_panel, panel_pos)
 values (:id, 'form', null, 'TABS', :code, null, 10);

  insert into rtm_entity_form_panel(id, name, caption, panel_type, entity_definition, parent_panel, panel_pos)
  select gen_id(hibernate_sequence, 1), 'common', 'Документ', 'VERTICAL', :code, :id, 20
  from rdb$database;

  insert into rtm_entity_form_panel(id, name, caption, panel_type, entity_definition, parent_panel, panel_pos)
  select gen_id(hibernate_sequence, 1), 'actdata', 'Данные акта', 'VERTICAL', :code, :id, 30
  from rdb$database;

 select F_ID from add_field(:dt,  'docNumber', 'Номер акта', 'java.lang.String', 'common')
 into :id;

 update rtm_field_definition f set f.data_len = 15 where f.id = :id;

 select F_ID from add_field(:dt,  'docDate', 'Дата акта', 'java.util.Date', 'common')
 into :id;
 select F_ID from add_field(:dt,  'content', 'Образ', 'BinaryContent', 'common')
 into :id;

  suspend;
end ^

ALTER PROCEDURE CREATE_ENTITYDEFINITION (DT VARCHAR(255) CHARACTER SET WIN1251,
CAPTION VARCHAR(255) CHARACTER SET WIN1251,
ROOT VARCHAR(255) CHARACTER SET WIN1251)
RETURNS (ID NUMERIC(18, 0))
AS 
declare variable CODE varchar(255);
begin

    -- select gen_id(hibernate_sequence, 1) from rdb$database into :id;

    code = dt || ':1';
    
INSERT INTO RTM_TYPE_DEFINITION (CODE, NAME, TYPE_NAME, SERIALIZER, VER, INLINE, VISUALIZER)
VALUES (:code, :caption, :dt, NULL, 1, 0, NULL);

INSERT INTO RTM_ENTITY_DEFINITION (CODE, NAME_EXPRESSION, TO_STRING_EXPRESSION, QUICK_FILTER_EXPRESSION, DEFAULT_ORDER, PATH_EXPRESSION, DEFAULT_FOLDER, SUBENTITY_ONLY)
 VALUES (:code, '#{instance.aname}', '#{instance.aname}', NULL, NULL, NULL, :root, 0);

-- select * from add_field(:dt,  'code', 'Код', 'java.lang.String', null)
-- into :id;

 select F_ID from add_field(:dt,  'aname', 'Наименование', 'java.lang.String', null)
 into :id;

  suspend;
end ^

ALTER PROCEDURE RENAME_DEFINITION (OLD_TYPE VARCHAR(80) CHARACTER SET WIN1251,
NEW_TYPE VARCHAR(80) CHARACTER SET WIN1251)
RETURNS (RESULT INTEGER)
AS 
declare variable OLD_CODE varchar(80);
declare variable NEW_CODE varchar(80);
declare variable TMP numeric(18,0);
begin

old_code = :old_type || ':1';
new_code = :new_type || ':1';

result = 0;

/* prevent renaming already renamed definitions (remove 'renamedFrom' prop val if you want ) */
select id from rtm_entity_property_value v
where v.entity_definition = :old_code
and v.property = 'renamedFrom'
into :tmp;
if (:tmp is not null) then
begin
  result = -1;
  suspend;
  exit;
end

/* create new with new type name */

INSERT INTO RTM_TYPE_DEFINITION (CODE, NAME, TYPE_NAME, SERIALIZER, VER, INLINE, VISUALIZER)
select            :new_code, name, :new_type, SERIALIZER, VER, INLINE, VISUALIZER
from rtm_type_definition where code = :old_code;

INSERT INTO RTM_ENTITY_DEFINITION (CODE, NAME_EXPRESSION, TO_STRING_EXPRESSION, QUICK_FILTER_EXPRESSION, DEFAULT_ORDER, PATH_EXPRESSION, DEFAULT_FOLDER, SUBENTITY_ONLY, RM_PROVIDER, TO_STRING_QUERY)
select :new_code,  NAME_EXPRESSION, TO_STRING_EXPRESSION, QUICK_FILTER_EXPRESSION, DEFAULT_ORDER, PATH_EXPRESSION, DEFAULT_FOLDER, SUBENTITY_ONLY, RM_PROVIDER, TO_STRING_QUERY
from RTM_ENTITY_DEFINITION where code = :old_code;

/* update all old */
update rtm_entity_filter t set t.entity_definition = :new_code where t.entity_definition = :old_code;
update rtm_entity_filter t set t.filter_value_type = :new_code where t.filter_value_type = :old_code;
update rtm_field_definition t set t.entity_definition = :new_code where t.entity_definition = :old_code;
update rtm_field_definition t set t.data_type = :new_code where t.data_type = :old_code;
update rtm_entity_form_panel t set t.entity_definition = :new_code where t.entity_definition = :old_code;
update rtm_entity_operation t set t.entity_definition = :new_code where t.entity_definition = :old_code;
update rtm_entity_property_value t set t.entity_definition = :new_code where t.entity_definition = :old_code;
update rtm_entity_validator t set t.entity_definition = :new_code where t.entity_definition = :old_code;


INSERT INTO RTM_ENTITY_PROPERTY_VALUE (ID, PROPERTY_VALUE, ENTITY_DEFINITION, PROPERTY)
select gen_id(hibernate_sequence, 1), :old_type, :new_code, 'renamedFrom'
from rdb$database;

/* delete old */
delete from rtm_entity_definition where code = :old_code;
delete from rtm_type_definition where code = :old_code;

result = 1;
suspend;
end ^
SET TERM ; ^
COMMIT WORK ;
SET AUTODDL ON;

/* Grant permissions for this database */
GRANT DELETE, INSERT, SELECT ON RTM_ENTITY_DEFINITION TO PROCEDURE RENAME_DEFINITION;
GRANT SELECT, UPDATE ON RTM_ENTITY_FILTER TO PROCEDURE RENAME_DEFINITION;
GRANT SELECT, UPDATE ON RTM_ENTITY_FORM_PANEL TO PROCEDURE RENAME_DEFINITION;
GRANT SELECT, UPDATE ON RTM_ENTITY_OPERATION TO PROCEDURE RENAME_DEFINITION;
GRANT INSERT, SELECT, UPDATE ON RTM_ENTITY_PROPERTY_VALUE TO PROCEDURE RENAME_DEFINITION;
GRANT SELECT, UPDATE ON RTM_ENTITY_VALIDATOR TO PROCEDURE RENAME_DEFINITION;
GRANT SELECT, UPDATE ON RTM_FIELD_DEFINITION TO PROCEDURE RENAME_DEFINITION;
GRANT DELETE, INSERT, SELECT ON RTM_TYPE_DEFINITION TO PROCEDURE RENAME_DEFINITION;
