/* CREATE DATABASE 'aisbd_test' PAGE_SIZE 16384 DEFAULT CHARACTER SET WIN1251 */


/*  Generators or sequences */
CREATE SEQUENCE ATTACHMENT_ID_SEQ;
CREATE SEQUENCE BOOLEANEXPR_ID_SEQ;
CREATE SEQUENCE COMMENT_ID_SEQ;
CREATE SEQUENCE CONTENT_ID_SEQ;
CREATE SEQUENCE DEADLINE_ID_SEQ;
CREATE SEQUENCE EMAILNOTIFHEAD_ID_SEQ;
CREATE SEQUENCE ERM_SEQUENCE;
CREATE SEQUENCE ESCALATION_ID_SEQ;
CREATE SEQUENCE HIBERNATE_SEQUENCE;
CREATE SEQUENCE I18NTEXT_ID_SEQ;
CREATE SEQUENCE NOTIFICATION_ID_SEQ;
CREATE SEQUENCE OC_JBPM5_TASK_TX_TXID_SEQ;
CREATE SEQUENCE OC_JBPM5_TIMER_INFO_SEQ;
CREATE SEQUENCE REASSIGNMENT_ID_SEQ;
CREATE SEQUENCE SESSIONINFO_ID_SEQ;
CREATE SEQUENCE WORKITEMINFO_ID_SEQ;


/* Table: CFG_ARTIFACT, Owner: SYSDBA */
CREATE TABLE CFG_ARTIFACT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        VERSION NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLED SMALLINT,
        INSTALL_LOG TEXT,
PRIMARY KEY (ID));

/* Table: CFG_DEPENDENCY, Owner: SYSDBA */
CREATE TABLE CFG_DEPENDENCY (ID NUMERIC(18, 0) NOT NULL,
        DEPENDENCY_CODE VARCHAR(255) NOT NULL,
        DEPENDENCY_VERSION NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PATH VARCHAR(255) NOT NULL,
        DESCRIPTION VARCHAR(255) NOT NULL,
        INSTALL_ORDER NUMERIC(18, 0) NOT NULL,
        RESOURCE_TYPE NUMERIC(18, 0) NOT NULL,
        ARTIFACT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_PARAM, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255) NOT NULL,
        PARAM_NAME VARCHAR(255) NOT NULL,
        RESOURCE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: CFG_RESOURCE_TYPE, Owner: SYSDBA */
CREATE TABLE CFG_RESOURCE_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        INSTALLER VARCHAR(255) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: DELEGATION_DELEGATES, Owner: SYSDBA */
CREATE TABLE DELEGATION_DELEGATES (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: ERMS_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERMS_EXTLINK (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERMS_EXTLINK PRIMARY KEY (ID));

/* Table: ERMS_FILTERED, Owner: SYSDBA */
CREATE TABLE ERMS_FILTERED (ID NUMERIC(18, 0) NOT NULL,
        SEARCHID NUMERIC(18, 0));

/* Table: ERMS_SAVED_FILTER, Owner: SYSDBA */
CREATE TABLE ERMS_SAVED_FILTER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0) NOT NULL,
        USER_ID NUMERIC(18, 0),
        NAME VARCHAR(250) NOT NULL,
        XMLDATA OID NOT NULL,
CONSTRAINT PK_ERMS_SAVED_FILTER PRIMARY KEY (ID));

/* Table: ERM_ADDRESSEEDOC, Owner: SYSDBA */
CREATE TABLE ERM_ADDRESSEEDOC (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        INTCONTRAGENT SMALLINT,
        ADDRESSEE NUMERIC(18, 0),
        INTADDRESSEE NUMERIC(18, 0),
        RECIPIENT VARCHAR(255),
        INTRECIPIENT NUMERIC(18, 0),
        DELIVERYKIND NUMERIC(18, 0),
        DATEDELIVERY TIMESTAMP,
CONSTRAINT PK_ERM_ADDRESSEEDOC PRIMARY KEY (ID));

/* Table: ERM_AGENTREQUEST, Owner: SYSDBA */
CREATE TABLE ERM_AGENTREQUEST (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        AGENTTYPE NUMERIC(18, 0),
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN NUMERIC(18, 0),
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        DOCDATE TIMESTAMP,
        COMMENTS VARCHAR(255),
        RESULT NUMERIC(18, 0),
        USERREQUEST NUMERIC(18, 0),
        SHORTTITLE VARCHAR(255),
        KPP NUMERIC(18, 0),
CONSTRAINT PK_ERM_AGENTREQUEST PRIMARY KEY (ID));

/* Table: ERM_AGENTTYPE, Owner: SYSDBA */
CREATE TABLE ERM_AGENTTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_AGENTTYPE PRIMARY KEY (ID));

/* Table: ERM_ASUDINTEGRATIONRULE, Owner: SYSDBA */
CREATE TABLE ERM_ASUDINTEGRATIONRULE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        TASKPROCESSORNAME VARCHAR(255),
        TASKNAME VARCHAR(255),
        JBPMPROCESS NUMERIC(18, 0),
        COMMANDELEXPRESSION VARCHAR(1024),
        TASKTYPE NUMERIC(18, 0),
        SKIPEXPRESSION VARCHAR(1024),
CONSTRAINT PK_ERM_ASUDINTEGRATIONRULE PRIMARY KEY (ID));

/* Table: ERM_BIN_CONTENT, Owner: SYSDBA */
CREATE TABLE ERM_BIN_CONTENT (ID NUMERIC(18, 0) NOT NULL,
        CONTENT_ID NUMERIC(18, 0) NOT NULL,
        CONTENT_VER INTEGER NOT NULL,
        MODIFIED_BY VARCHAR(255),
        LAST_MODIFIED TIMESTAMP,
        IS_ACTUAL SMALLINT,
        SIGNED SMALLINT,
        SIGN_DATE TIMESTAMP,
        SIGN_AUTHOR VARCHAR(255),
        MIMETYPE VARCHAR(255),
        ENCODING VARCHAR(255),
        FILENAME VARCHAR(255),
        SIGN_ALGORITHM VARCHAR(255),
CONSTRAINT PK_ERM_BIN_CONTENT PRIMARY KEY (ID));

/* Table: ERM_BOARD, Owner: SYSDBA */
CREATE TABLE ERM_BOARD (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CHAIRMAN NUMERIC(18, 0),
        SECRETARY NUMERIC(18, 0),
        ANAME VARCHAR(255),
        CODE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
CONSTRAINT PK_ERM_BOARD PRIMARY KEY (ID));

/* Table: ERM_CONTRAGENT, Owner: SYSDBA */
CREATE TABLE ERM_CONTRAGENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        AGENTTYPE NUMERIC(18, 0),
        SURNAME VARCHAR(64),
        FIRSTNAME VARCHAR(64),
        PATRONYMIC VARCHAR(64),
        ANAME VARCHAR(255),
        OPF VARCHAR(64),
        TITLE VARCHAR(255),
        INN NUMERIC(18, 0),
        LOWADRESS VARCHAR(255),
        POSTADRESS VARCHAR(255),
        PHONE VARCHAR(255),
        EMAIL VARCHAR(255),
        REQUISITES VARCHAR(600),
        CONTACT VARCHAR(255),
        ACTIVE SMALLINT,
        SHORTTITLE VARCHAR(255),
        KPP NUMERIC(18, 0),
CONSTRAINT PK_ERM_CONTRAGENT PRIMARY KEY (ID));

/* Table: ERM_DELEGATION, Owner: SYSDBA */
CREATE TABLE ERM_DELEGATION (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EMPLOYER NUMERIC(18, 0),
        DELEGAT NUMERIC(18, 0),
        PROCESS NUMERIC(18, 0),
        USERTASK NUMERIC(18, 0),
        ADDTASK SMALLINT,
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        ACTIVE SMALLINT,
CONSTRAINT PK_ERM_DELEGATION PRIMARY KEY (ID));

/* Table: ERM_DELIVERYKIND, Owner: SYSDBA */
CREATE TABLE ERM_DELIVERYKIND (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DELIVERYKIND PRIMARY KEY (ID));

/* Table: ERM_DOCKIND, Owner: SYSDBA */
CREATE TABLE ERM_DOCKIND (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
        INDEXKIND VARCHAR(16),
        APPROVAL SMALLINT,
        BOARD SMALLINT,
        ACTIVE SMALLINT,
CONSTRAINT PK_ERM_DOCKIND PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERING, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERING (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ORGUNIT NUMERIC(18, 0),
        BOARD NUMERIC(18, 0),
        DOCTYPE NUMERIC(18, 0),
        DOCKIND NUMERIC(18, 0),
        PERIOD NUMERIC(18, 0),
        PREFIX VARCHAR(255),
        POSTFIX VARCHAR(255),
CONSTRAINT PK_ERM_DOCNUMBERING PRIMARY KEY (ID));

/* Table: ERM_DOCNUMBERSEQ, Owner: SYSDBA */
CREATE TABLE ERM_DOCNUMBERSEQ (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODCODE VARCHAR(10),
        NEXTNUMBER NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCNUMBERSEQ PRIMARY KEY (ID));

/* Table: ERM_DOCRELATED, Owner: SYSDBA */
CREATE TABLE ERM_DOCRELATED (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOC NUMERIC(18, 0),
        ANAME NUMERIC(18, 0),
        SOURCEDOC NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCRELATED PRIMARY KEY (ID));

/* Table: ERM_DOCSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_DOCSTATUS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_DOCSTATUS PRIMARY KEY (ID));

/* Table: ERM_DOCTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTEMPLATE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        DOCKIND NUMERIC(18, 0),
        ORGUNIT NUMERIC(18, 0),
        FILE NUMERIC(18, 0),
        LINK VARCHAR(255),
CONSTRAINT PK_ERM_DOCTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_DOCTYPE, Owner: SYSDBA */
CREATE TABLE ERM_DOCTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(5),
        ANAME VARCHAR(255),
        INDEXTYPE VARCHAR(16),
CONSTRAINT PK_ERM_DOCTYPE PRIMARY KEY (ID));

/* Table: ERM_DOCUMENT, Owner: SYSDBA */
CREATE TABLE ERM_DOCUMENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        BRANCH NUMERIC(18, 0),
        STATUS NUMERIC(18, 0),
        DOCTYPE NUMERIC(18, 0),
        DOCKIND NUMERIC(18, 0),
        NUMBER VARCHAR(255),
        REGDATE TIMESTAMP,
        OUTNUMBER VARCHAR(255),
        INTCONTRAGENT SMALLINT,
        ASUD VARCHAR(255),
        AGENT NUMERIC(18, 0),
        AGENTREQUEST NUMERIC(18, 0),
        INAUTHOR VARCHAR(255),
        INTCORRESPONDENT NUMERIC(18, 0),
        BOARD NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        SUBJECT VARCHAR(1024),
        DELIVERYKIND NUMERIC(18, 0),
        NOMENCLATURE NUMERIC(18, 0),
        REGISTRATOR NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
        NEEDAGREEMENT SMALLINT,
        SIGNER NUMERIC(18, 0),
        ARCHIVE SMALLINT,
        OUTDATE TIMESTAMP,
        ORIGINAL SMALLINT,
        STORAGE NUMERIC(18, 0),
        TRANSFERDATE TIMESTAMP,
        CLERKNOTE VARCHAR(1024),
        CREATEDATE TIMESTAMP,
        SUPERVISOR NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCUMENT PRIMARY KEY (ID));

/* Table: ERM_DOCUSER, Owner: SYSDBA */
CREATE TABLE ERM_DOCUSER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCUSER NUMERIC(18, 0),
CONSTRAINT PK_ERM_DOCUSER PRIMARY KEY (ID));

/* Table: ERM_ENTITYEVENT, Owner: SYSDBA */
CREATE TABLE ERM_ENTITYEVENT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        EVENTDATE TIMESTAMP,
        EVENTTYPE VARCHAR(80),
        ANAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        EVENTUSER NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
CONSTRAINT PK_ERM_ENTITYEVENT PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATE, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        TEMPLATEOWNER NUMERIC(18, 0),
        COMMON SMALLINT,
        TEMPLATELEVEL NUMERIC(18, 0),
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATE PRIMARY KEY (ID));

/* Table: ERM_EXECUTANTSTEMPLATEITEM, Owner: SYSDBA */
CREATE TABLE ERM_EXECUTANTSTEMPLATEITEM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        EXECUTANT NUMERIC(18, 0),
CONSTRAINT PK_ERM_EXECUTANTSTEMPLATEITEM PRIMARY KEY (ID));

/* Table: ERM_EXTLINK, Owner: SYSDBA */
CREATE TABLE ERM_EXTLINK (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_TYPE VARCHAR(80) NOT NULL,
        ENTITY_ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_SYSTEM VARCHAR(80) NOT NULL,
        EXTERNAL_TYPE VARCHAR(80) NOT NULL,
        EXTERNAL_ID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_EXTLINK PRIMARY KEY (ID));

/* Table: ERM_FAVORITES, Owner: SYSDBA */
CREATE TABLE ERM_FAVORITES (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        FAVORITE NUMERIC(18, 0),
CONSTRAINT PK_ERM_FAVORITES PRIMARY KEY (ID));

/* Table: ERM_FILE, Owner: SYSDBA */
CREATE TABLE ERM_FILE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        FILE NUMERIC(18, 0),
        FILETYPE NUMERIC(18, 0),
        NOTE VARCHAR(255),
        USERREF NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
CONSTRAINT PK_ERM_FILE PRIMARY KEY (ID));

/* Table: ERM_FILETYPE, Owner: SYSDBA */
CREATE TABLE ERM_FILETYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        DEFAULTFILE SMALLINT,
CONSTRAINT PK_ERM_FILETYPE PRIMARY KEY (ID));

/* Table: ERM_FOLDER, Owner: SYSDBA */
CREATE TABLE ERM_FOLDER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ENTITY_TYPE VARCHAR(80),
        TENANT_ID NUMERIC(18, 0),
        PARENT_ID NUMERIC(18, 0),
        SORT_INDEX INTEGER,
        LBORDER NUMERIC(18, 0),
        RBORDER NUMERIC(18, 0),
        QUERY_DESC NUMERIC(18, 0),
CONSTRAINT PK_ERM_FOLDER PRIMARY KEY (ID));

/* Table: ERM_LINKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_LINKTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_LINKTYPE PRIMARY KEY (ID));

/* Table: ERM_LISTNUMBER, Owner: SYSDBA */
CREATE TABLE ERM_LISTNUMBER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        DOCID NUMERIC(18, 0),
        REGNUMBER VARCHAR(255),
        REF NUMERIC(18, 0),
CONSTRAINT PK_ERM_LISTNUMBER PRIMARY KEY (ID));

/* Table: ERM_NOMENCLATURE, Owner: SYSDBA */
CREATE TABLE ERM_NOMENCLATURE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PARENTNOMENCLATURE NUMERIC(18, 0),
        INDEXFIELD VARCHAR(255),
        TITLE VARCHAR(255),
        AMOUNT NUMERIC(18, 0),
        LIFESTORAGE VARCHAR(255),
        ORGUNIT NUMERIC(18, 0),
        COMMENT VARCHAR(255),
        ACTIVE SMALLINT,
        ARTICLE VARCHAR(255),
        CHILDACCESS SMALLINT,
CONSTRAINT PK_ERM_NOMENCLATURE PRIMARY KEY (ID));

/* Table: ERM_NOTE, Owner: SYSDBA */
CREATE TABLE ERM_NOTE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        NOTEINDEX NUMERIC(18, 0),
        REPLYTO NUMERIC(18, 0),
        TEXT VARCHAR(2048),
        CREATEDATE TIMESTAMP,
        USERNOTE NUMERIC(18, 0),
        STATUS VARCHAR(255),
CONSTRAINT PK_ERM_NOTE PRIMARY KEY (ID));

/* Table: ERM_ORGTYPE, Owner: SYSDBA */
CREATE TABLE ERM_ORGTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ORGTYPE PRIMARY KEY (ID));

/* Table: ERM_ORGUNIT, Owner: SYSDBA */
CREATE TABLE ERM_ORGUNIT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(10),
        ANAME VARCHAR(255),
        PARENTUNIT NUMERIC(18, 0),
        DESCRIPTION VARCHAR(255),
        ACTIVE SMALLINT,
        SHORTNAME VARCHAR(25),
        INDEXCASE VARCHAR(255),
        ORGTYPE NUMERIC(18, 0),
        MANAGER NUMERIC(18, 0),
        UNITPATH VARCHAR(255),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        CFO NUMERIC(18, 0),
CONSTRAINT PK_ERM_ORGUNIT PRIMARY KEY (ID));

/* Table: ERM_PERIOD, Owner: SYSDBA */
CREATE TABLE ERM_PERIOD (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_PERIOD PRIMARY KEY (ID));

/* Table: ERM_PERIODICTASK, Owner: SYSDBA */
CREATE TABLE ERM_PERIODICTASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        PERIODTEXT VARCHAR(255),
        PERIODTYPE NUMERIC(18, 0),
        DAYNUMBER NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
        TASKOWNER NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        CONTROLDAYS NUMERIC(18, 0),
        TASK VARCHAR(1024),
        EXECUTOR NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        FINISHDATE TIMESTAMP,
        NEXTSTART TIMESTAMP,
        LASTSTART TIMESTAMP,
        ISACTIVE SMALLINT,
CONSTRAINT PK_ERM_PERIODICTASK PRIMARY KEY (ID));

/* Table: ERM_PERM, Owner: SYSDBA */
CREATE TABLE ERM_PERM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0) NOT NULL,
        PERM_ACTION VARCHAR(80) NOT NULL,
        PRINCIPAL_UID VARCHAR(80) NOT NULL,
CONSTRAINT PK_ERM_PERM PRIMARY KEY (ID));

/* Table: ERM_PFM, Owner: SYSDBA */
CREATE TABLE ERM_PFM (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        PARENTUNIT NUMERIC(18, 0),
        BE NUMERIC(18, 0),
        STARTDATE TIMESTAMP,
        ENDDATE TIMESTAMP,
CONSTRAINT PK_ERM_PFM PRIMARY KEY (ID));

/* Table: ERM_PROCESS, Owner: SYSDBA */
CREATE TABLE ERM_PROCESS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        PROCESSKEY VARCHAR(80),
        ANAME VARCHAR(256),
CONSTRAINT PK_ERM_PROCESS PRIMARY KEY (ID));

/* Table: ERM_ROLE, Owner: SYSDBA */
CREATE TABLE ERM_ROLE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(255),
        ANAME VARCHAR(255),
CONSTRAINT PK_ERM_ROLE PRIMARY KEY (ID));

/* Table: ERM_STAGE, Owner: SYSDBA */
CREATE TABLE ERM_STAGE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE NUMERIC(18, 0),
        ANAME VARCHAR(15),
CONSTRAINT PK_ERM_STAGE PRIMARY KEY (ID));

/* Table: ERM_TASK, Owner: SYSDBA */
CREATE TABLE ERM_TASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASKSUBJECT VARCHAR(255),
        TASK VARCHAR(2048),
        EXECUTOR NUMERIC(18, 0),
        STATUS NUMERIC(18, 0),
        AUTHOR NUMERIC(18, 0),
        SUPERVISOR NUMERIC(18, 0),
        CREATEDATE TIMESTAMP,
        CANCELREASON VARCHAR(255),
        CONTROLDATE TIMESTAMP,
        TASKACTIVE SMALLINT,
        TASKACTUAL SMALLINT,
        REFTASK NUMERIC(18, 0),
        DOCBASE VARCHAR(255),
        FILE NUMERIC(18, 0),
        NEEDREPORT SMALLINT,
        ADATE TIMESTAMP,
        TASKTYPE NUMERIC(18, 0),
        FILES NUMERIC(18, 0),
        PARENTTASK NUMERIC(18, 0),
        ANUMBER VARCHAR(16),
        TASKTEXT VARCHAR(1024),
        ISDONE SMALLINT,
        DOCUMENT NUMERIC(18, 0),
        STAGE NUMERIC(18, 0),
        NOTE VARCHAR(1024),
        STARTDATE TIMESTAMP,
        RESULTDATE TIMESTAMP,
        GETDATE TIMESTAMP,
CONSTRAINT PK_ERM_TASK PRIMARY KEY (ID));

/* Table: ERM_TASKDELEGATED, Owner: SYSDBA */
CREATE TABLE ERM_TASKDELEGATED (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        TASK NUMERIC(18, 0),
CONSTRAINT PK_ERM_TASKDELEGATED PRIMARY KEY (ID));

/* Table: ERM_TASKREPORT, Owner: SYSDBA */
CREATE TABLE ERM_TASKREPORT (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        REPORT VARCHAR(2048),
        REPORTDATE TIMESTAMP,
        ACCEPTED SMALLINT,
        NOTE VARCHAR(1024),
        NOTEDATE TIMESTAMP,
        NOTEUSER NUMERIC(18, 0),
        DOCUMENT NUMERIC(18, 0),
CONSTRAINT PK_ERM_TASKREPORT PRIMARY KEY (ID));

/* Table: ERM_TASKSTATUS, Owner: SYSDBA */
CREATE TABLE ERM_TASKSTATUS (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ANAME VARCHAR(255),
        CODE VARCHAR(16),
CONSTRAINT PK_ERM_TASKSTATUS PRIMARY KEY (ID));

/* Table: ERM_TASKTYPE, Owner: SYSDBA */
CREATE TABLE ERM_TASKTYPE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        CODE VARCHAR(16),
        ANAME VARCHAR(255),
        REPORT SMALLINT,
        PREF VARCHAR(16),
CONSTRAINT PK_ERM_TASKTYPE PRIMARY KEY (ID));

/* Table: ERM_USER, Owner: SYSDBA */
CREATE TABLE ERM_USER (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        SURNAME VARCHAR(255),
        FIRSTNAME VARCHAR(255),
        PATRONYMIC VARCHAR(255),
        LOGIN VARCHAR(255),
        ANAME VARCHAR(255),
        ORGUNIT NUMERIC(18, 0),
        JOBNAME VARCHAR(255),
        EMAIL VARCHAR(255),
        TABNUMBER VARCHAR(255),
        DISMISSED SMALLINT,
        DELEGAT NUMERIC(18, 0),
        USERREF NUMERIC(18, 0),
        INDEXUSER VARCHAR(16),
        PHONE VARCHAR(255),
        ALLOWEDDOCSOFUNIT NUMERIC(18, 0),
        ORGUNITNAME VARCHAR(255),
        SSOLOGIN VARCHAR(255),
        PARENTORGUNIT NUMERIC(18, 0),
        NOTE VARCHAR(255),
CONSTRAINT PK_ERM_USER PRIMARY KEY (ID));

/* Table: ERM_USERROLE, Owner: SYSDBA */
CREATE TABLE ERM_USERROLE (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ROLE NUMERIC(18, 0),
CONSTRAINT PK_ERM_USERROLE PRIMARY KEY (ID));

/* Table: ERM_USERTASK, Owner: SYSDBA */
CREATE TABLE ERM_USERTASK (ID NUMERIC(18, 0) NOT NULL,
        FOLDER_ID NUMERIC(18, 0),
        ERM_OWNER NUMERIC(18, 0),
        ERM_OWNER_TYPE VARCHAR(80),
        ERM_OWNER_FIELD VARCHAR(80),
        ERM_SORT INTEGER,
        ANAME VARCHAR(256),
        PROCESS NUMERIC(18, 0),
CONSTRAINT PK_ERM_USERTASK PRIMARY KEY (ID));

/* Table: EVENTTYPES, Owner: SYSDBA */
CREATE TABLE EVENTTYPES (INSTANCEID NUMERIC(18, 0) NOT NULL,
        ELEMENT VARCHAR(255));

/* Table: JBPM4_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYMENT (DBID_ NUMERIC(18, 0) NOT NULL,
        NAME_ TEXT,
        TIMESTAMP_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_DEPLOYPROP, Owner: SYSDBA */
CREATE TABLE JBPM4_DEPLOYPROP (DBID_ NUMERIC(18, 0) NOT NULL,
        DEPLOYMENT_ NUMERIC(18, 0),
        OBJNAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        STRINGVAL_ VARCHAR(255),
        LONGVAL_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_EXECUTION, Owner: SYSDBA */
CREATE TABLE JBPM4_EXECUTION (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ACTIVITYNAME_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        HASVARS_ SMALLINT,
        NAME_ VARCHAR(255),
        KEY_ VARCHAR(255),
        ID_ VARCHAR(255),
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        HISACTINST_ NUMERIC(18, 0),
        PARENT_ NUMERIC(18, 0),
        INSTANCE_ NUMERIC(18, 0),
        SUPEREXEC_ NUMERIC(18, 0),
        SUBPROCINST_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_),
UNIQUE (ID_));

/* Table: JBPM4_HIST_ACTINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_ACTINST (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        HPROCI_ NUMERIC(18, 0),
        TYPE_ VARCHAR(255),
        EXECUTION_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        TRANSITION_ VARCHAR(255),
        NEXTIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_DETAIL, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_DETAIL (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USERID_ VARCHAR(255),
        TIME_ TIMESTAMP,
        HPROCI_ NUMERIC(18, 0),
        HPROCIIDX_ INTEGER,
        HACTI_ NUMERIC(18, 0),
        HACTIIDX_ INTEGER,
        HTASK_ NUMERIC(18, 0),
        HTASKIDX_ INTEGER,
        HVAR_ NUMERIC(18, 0),
        HVARIDX_ INTEGER,
        MESSAGE_ TEXT,
        OLD_STR_ VARCHAR(255),
        NEW_STR_ VARCHAR(255),
        OLD_INT_ INTEGER,
        NEW_INT_ INTEGER,
        OLD_TIME_ TIMESTAMP,
        NEW_TIME_ TIMESTAMP,
        PARENT_ NUMERIC(18, 0),
        PARENT_IDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_PROCINST, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_PROCINST (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PROCDEFID_ VARCHAR(255),
        KEY_ VARCHAR(255),
        START_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        STATE_ VARCHAR(255),
        ENDACTIVITY_ VARCHAR(255),
        NEXTIDX_ INTEGER,
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        EXECUTION_ VARCHAR(255),
        OUTCOME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        PRIORITY_ INTEGER,
        STATE_ VARCHAR(255),
        CREATE_ TIMESTAMP,
        END_ TIMESTAMP,
        DURATION_ NUMERIC(18, 0),
        NEXTIDX_ INTEGER,
        SUPERTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_HIST_VAR, Owner: SYSDBA */
CREATE TABLE JBPM4_HIST_VAR (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        PROCINSTID_ VARCHAR(255),
        EXECUTIONID_ VARCHAR(255),
        VARNAME_ VARCHAR(255),
        VALUE_ VARCHAR(255),
        HPROCI_ NUMERIC(18, 0),
        HTASK_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_GROUP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_GROUP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        NAME_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        PARENT_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_MEMBERSHIP, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_MEMBERSHIP (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        USER_ NUMERIC(18, 0),
        GROUP_ NUMERIC(18, 0),
        NAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_ID_USER, Owner: SYSDBA */
CREATE TABLE JBPM4_ID_USER (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        ID_ VARCHAR(255),
        PASSWORD_ VARCHAR(255),
        GIVENNAME_ VARCHAR(255),
        FAMILYNAME_ VARCHAR(255),
        BUSINESSEMAIL_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_JOB, Owner: SYSDBA */
CREATE TABLE JBPM4_JOB (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        DUEDATE_ TIMESTAMP,
        STATE_ VARCHAR(255),
        ISEXCLUSIVE_ SMALLINT,
        LOCKOWNER_ VARCHAR(255),
        LOCKEXPTIME_ TIMESTAMP,
        EXCEPTION_ TEXT,
        RETRIES_ INTEGER,
        PROCESSINSTANCE_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        CFG_ NUMERIC(18, 0),
        SIGNAL_ VARCHAR(255),
        EVENT_ VARCHAR(255),
        REPEAT_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_LOB, Owner: SYSDBA */
CREATE TABLE JBPM4_LOB (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        BLOB_VALUE_ OID,
        DEPLOYMENT_ NUMERIC(18, 0),
        NAME_ TEXT,
PRIMARY KEY (DBID_));

/* Table: JBPM4_PARTICIPATION, Owner: SYSDBA */
CREATE TABLE JBPM4_PARTICIPATION (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        GROUPID_ VARCHAR(255),
        USERID_ VARCHAR(255),
        TYPE_ VARCHAR(255),
        TASK_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_PROPERTY, Owner: SYSDBA */
CREATE TABLE JBPM4_PROPERTY (KEY_ VARCHAR(255) NOT NULL,
        VERSION_ INTEGER NOT NULL,
        VALUE_ VARCHAR(255),
PRIMARY KEY (KEY_));

/* Table: JBPM4_SWIMLANE, Owner: SYSDBA */
CREATE TABLE JBPM4_SWIMLANE (DBID_ NUMERIC(18, 0) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        EXECUTION_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM4_TASK, Owner: SYSDBA */
CREATE TABLE JBPM4_TASK (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ CHAR(1) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        NAME_ VARCHAR(255),
        DESCR_ TEXT,
        STATE_ VARCHAR(255),
        SUSPHISTSTATE_ VARCHAR(255),
        ASSIGNEE_ VARCHAR(255),
        FORM_ VARCHAR(255),
        PRIORITY_ INTEGER,
        CREATE_ TIMESTAMP,
        DUEDATE_ TIMESTAMP,
        PROGRESS_ INTEGER,
        SIGNALLING_ SMALLINT,
        EXECUTION_ID_ VARCHAR(255),
        ACTIVITY_NAME_ VARCHAR(255),
        HASVARS_ SMALLINT,
        SUPERTASK_ NUMERIC(18, 0),
        EXECUTION_ NUMERIC(18, 0),
        PROCINST_ NUMERIC(18, 0),
        SWIMLANE_ NUMERIC(18, 0),
        TASKDEFNAME_ VARCHAR(255),
PRIMARY KEY (DBID_));

/* Table: JBPM4_VARIABLE, Owner: SYSDBA */
CREATE TABLE JBPM4_VARIABLE (DBID_ NUMERIC(18, 0) NOT NULL,
        CLASS_ VARCHAR(255) NOT NULL,
        DBVERSION_ INTEGER NOT NULL,
        KEY_ VARCHAR(255),
        CONVERTER_ VARCHAR(255),
        HIST_ SMALLINT,
        EXECUTION_ NUMERIC(18, 0),
        TASK_ NUMERIC(18, 0),
        LOB_ NUMERIC(18, 0),
        DATE_VALUE_ TIMESTAMP,
        DOUBLE_VALUE_ DOUBLE PRECISION,
        CLASSNAME_ VARCHAR(255),
        LONG_VALUE_ NUMERIC(18, 0),
        STRING_VALUE_ VARCHAR(255),
        TEXT_VALUE_ TEXT,
        EXESYS_ NUMERIC(18, 0),
PRIMARY KEY (DBID_));

/* Table: JBPM5_HT_ATTACHMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ATTACHMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        ACCESSTYPE INTEGER,
        CONTENTTYPE VARCHAR(255),
        ATTACHEDAT TIMESTAMP,
        ATTACHMENT_SIZE INTEGER,
        ATTACHMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        ATTACHEDBY_ID VARCHAR(255),
        TASKDATA_ATTACHMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_BOOL_EXPR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_BOOL_EXPR (ID NUMERIC(18, 0) NOT NULL,
        TYPE VARCHAR(255),
        EXPRESSION TEXT,
        ESCALATION_CONSTRAINTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_COMMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_COMMENT (ID NUMERIC(18, 0) NOT NULL,
        TEXT TEXT,
        ADDEDAT TIMESTAMP,
        ADDEDBY_ID VARCHAR(255),
        TASKDATA_COMMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_CONTENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_CONTENT (ID NUMERIC(18, 0) NOT NULL,
        CONTENT OID,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_DEADLINE, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_DEADLINE (ID NUMERIC(18, 0) NOT NULL,
        DEADLINE_DATE TIMESTAMP,
        ESCALATED SMALLINT NOT NULL,
        DEADLINES_ENDDEADLINE_ID NUMERIC(18, 0),
        DEADLINES_STARTDEADLINE_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_ESCALATION, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ESCALATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        DEADLINE_ESCALATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_I18N_TEXT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_I18N_TEXT (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        TEXT TEXT,
        TASK_DESCRIPTIONS_ID NUMERIC(18, 0),
        TASK_SUBJECTS_ID NUMERIC(18, 0),
        TASK_NAMES_ID NUMERIC(18, 0),
        REASSIGNMENT_DOCUMENTATION_ID NUMERIC(18, 0),
        NOTIFICATION_DESCRIPTIONS_ID NUMERIC(18, 0),
        NOTIFICATION_SUBJECTS_ID NUMERIC(18, 0),
        NOTIFICATION_NAMES_ID NUMERIC(18, 0),
        NOTIFICATION_DOCUMENTATION_ID NUMERIC(18, 0),
        DEADLINE_DOCUMENTATION_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_MAILNHDR (ID NUMERIC(18, 0) NOT NULL,
        LANGUAGE VARCHAR(255),
        REPLYTOADDRESS VARCHAR(255),
        FROMADDRESS VARCHAR(255),
        SUBJECT VARCHAR(255),
        BODY TEXT,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N (DTYPE VARCHAR(31) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ESCALATION_NOTIFICATIONS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_N10N_JBPM5_HT_MAILNHDR, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR (JBPM5_HT_N10N_ID NUMERIC(18, 0) NOT NULL,
        EMAILHEADERS_ID NUMERIC(18, 0) NOT NULL,
        MAPKEY VARCHAR(255) NOT NULL,
PRIMARY KEY (JBPM5_HT_N10N_ID, MAPKEY),
UNIQUE (EMAILHEADERS_ID));

/* Table: JBPM5_HT_ORG_ENTITY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_ORG_ENTITY (DTYPE VARCHAR(31) NOT NULL,
        ID VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: JBPM5_HT_REASSIGNMENT, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_REASSIGNMENT (ID NUMERIC(18, 0) NOT NULL,
        ESCALATION_REASSIGNMENTS_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_SUBTASK_STRATEGY, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_SUBTASK_STRATEGY (DTYPE VARCHAR(100) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TASK_ID NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: JBPM5_HT_TASK, Owner: SYSDBA */
CREATE TABLE JBPM5_HT_TASK (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY INTEGER NOT NULL,
        ALLOWEDTODELEGATE VARCHAR(255),
        STATUS VARCHAR(255),
        PREVIOUSSTATUS INTEGER,
        CREATEDON TIMESTAMP,
        ACTIVATIONTIME TIMESTAMP,
        EXPIRATIONTIME TIMESTAMP,
        SKIPABLE SMALLINT NOT NULL,
        WORKITEMID NUMERIC(18, 0) NOT NULL,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        DOCUMENTACCESSTYPE INTEGER,
        DOCUMENTTYPE VARCHAR(255),
        DOCUMENTCONTENTID NUMERIC(18, 0) NOT NULL,
        OUTPUTACCESSTYPE INTEGER,
        OUTPUTTYPE VARCHAR(255),
        OUTPUTCONTENTID NUMERIC(18, 0) NOT NULL,
        FAULTNAME VARCHAR(255),
        FAULTACCESSTYPE INTEGER,
        FAULTTYPE VARCHAR(255),
        FAULTCONTENTID NUMERIC(18, 0) NOT NULL,
        PARENTID NUMERIC(18, 0) NOT NULL,
        PROCESSID VARCHAR(255),
        PROCESSKEY VARCHAR(255),
        PROCESSSESSIONID INTEGER NOT NULL,
        TASKINITIATOR_ID VARCHAR(255),
        CREATEDBY_ID VARCHAR(255),
        ACTUALOWNER_ID VARCHAR(255),
        OPTLOCK INTEGER,
        ARCHIVED SMALLINT,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (ID));

/* Table: JBPM5_PROCINST_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_PROCINST_INFO (INSTANCEID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        PROCESSID VARCHAR(255),
        STARTDATE TIMESTAMP,
        LASTREADDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        STATE INTEGER NOT NULL,
        PROCESSINSTANCEBYTEARRAY OID,
        PROCESSINSTANCEIDSPATH VARCHAR(255),
PRIMARY KEY (INSTANCEID));

/* Table: JBPM5_SESSION_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO (ID INTEGER NOT NULL,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY OID,
        CLUSTERNODENAME VARCHAR(80),
PRIMARY KEY (ID));

/* Table: JBPM5_SESSION_INFO_SAVED, Owner: SYSDBA */
CREATE TABLE JBPM5_SESSION_INFO_SAVED (ID INTEGER,
        OPTLOCK INTEGER,
        STARTDATE TIMESTAMP,
        LASTMODIFICATIONDATE TIMESTAMP,
        RULESBYTEARRAY OID,
        CLUSTERNODENAME VARCHAR(80));

/* Table: JBPM5_WORKITEM_INFO, Owner: SYSDBA */
CREATE TABLE JBPM5_WORKITEM_INFO (WORKITEMID NUMERIC(18, 0) NOT NULL,
        OPTLOCK INTEGER,
        NAME VARCHAR(255),
        CREATIONDATE TIMESTAMP,
        PROCESSINSTANCEID NUMERIC(18, 0) NOT NULL,
        STATE NUMERIC(18, 0) NOT NULL,
        WORKITEMBYTEARRAY OID,
PRIMARY KEY (WORKITEMID));

/* Table: JB_JOB_TYPE, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        ACTION VARCHAR(255) NOT NULL,
        FIRST_DATE_EXPRESSION VARCHAR(255) NOT NULL,
        PERIOD_EXPRESSION VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: JB_JOB_TYPE_PARAM, Owner: SYSDBA */
CREATE TABLE JB_JOB_TYPE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        VALUE_EXPRESSION VARCHAR(255),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB (ID NUMERIC(18, 0) NOT NULL,
        START_DATE TIMESTAMP,
        ACTION VARCHAR(255) NOT NULL,
        JOB_KEY VARCHAR(255) NOT NULL,
        PERIOD_VALUE NUMERIC(18, 0),
        LAST_ERROR VARCHAR(1024),
        JOB_TYPE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: JB_SCHEDULED_JOB_PARAM, Owner: SYSDBA */
CREATE TABLE JB_SCHEDULED_JOB_PARAM (ID NUMERIC(18, 0) NOT NULL,
        STRING_VALUE VARCHAR(255),
        CODE VARCHAR(255) NOT NULL,
        DOUBLE_VALUE DOUBLE PRECISION,
        DATE_VALUE TIMESTAMP,
        SCHEDULED_JOB NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: MSG_USER_MESSAGE, Owner: SYSDBA */
CREATE TABLE MSG_USER_MESSAGE (ID NUMERIC(18, 0) NOT NULL,
        PRIORITY NUMERIC(18, 0),
        SUBJECT VARCHAR(255),
        BODY TEXT,
        READ SMALLINT,
        DRAFT SMALLINT,
        ARCHIVE SMALLINT,
        MESSAGE_DATE TIMESTAMP,
        USER_FROM NUMERIC(18, 0),
        USER_TO NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0) NOT NULL,
        IS_READ SMALLINT,
PRIMARY KEY (ID));

/* Table: NOTIFICATION_BAS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: NOTIFICATION_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE NOTIFICATION_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: OC_CLUSTER_NODE, Owner: SYSDBA */
CREATE TABLE OC_CLUSTER_NODE (ID NUMERIC(18, 0) NOT NULL,
        LATEST_PING_TIME TIMESTAMP NOT NULL,
        MASTER_NODE SMALLINT NOT NULL,
        NODE_HTTP_PORT NUMERIC(18, 0) NOT NULL,
        NODE_IP_ADDRESS VARCHAR(255) NOT NULL,
        NODE_IS_STOPPED SMALLINT,
        NODE_NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_COMMON_USER, Owner: SYSDBA */
CREATE TABLE OC_COMMON_USER (ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_CUSTOM_PAGE, Owner: SYSDBA */
CREATE TABLE OC_CUSTOM_PAGE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(254) NOT NULL,
        PAGE_TEXT TEXT,
        PAGE_TYPE VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: OC_ENTITY_LOCK, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_LOCK (ID NUMERIC(18, 0) NOT NULL,
        LOCK_DATE DATE,
        LOCKED_ENTITY_NAME VARCHAR(255),
        LOCKED_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_ID VARCHAR(255),
        LOCKER_ENTITY_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_ENTITY_WORD, Owner: SYSDBA */
CREATE TABLE OC_ENTITY_WORD (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(80) NOT NULL,
        ENTITY_ID_STRING VARCHAR(80),
        ENTITY_ID_LONG NUMERIC(18, 0),
        THEWORD VARCHAR(80),
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT2ENT_FLD_EXPR, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT2ENT_FLD_EXPR (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255),
        EXPRESSION VARCHAR(255),
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        PROCESS_ENTITY_CHECK_EXPR VARCHAR(255),
        PROCESS_ORDER NUMERIC(18, 0),
        IS_ACTIVE SMALLINT,
        EXTERNAL_SYSTEM NUMERIC(18, 0) NOT NULL,
        CHECK_DUPLICATE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_EXT_ENTITY2ENTITY, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY2ENTITY (ID NUMERIC(18, 0) NOT NULL,
        ENTITY_CLASS VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENTITY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENTITY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FIELD_TYPE VARCHAR(255),
        CODE VARCHAR(30) NOT NULL,
        FIELD_POSITION NUMERIC(18, 0),
        KEY_POSITION NUMERIC(18, 0),
        EXTERNAL_ENTITY_REFERENCE NUMERIC(18, 0),
        EXTERNAL_ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_FLD2FLD, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_FLD2FLD (ID NUMERIC(18, 0) NOT NULL,
        FIELD_NAME VARCHAR(255) NOT NULL,
        REFERENCED_ENTITY_FIELD_NAME VARCHAR(255),
        EXTERNAL_ENTITY_FIELD NUMERIC(18, 0) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_ID2ID, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_ID2ID (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(255) NOT NULL,
        PK_VALUE VARCHAR(255) NOT NULL,
        EXTERNAL_ENTITY2ENTITY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_ENT_PROCESSED_KEYS, Owner: SYSDBA */
CREATE TABLE OC_EXT_ENT_PROCESSED_KEYS (ID NUMERIC(18, 0) NOT NULL,
        EXTERNAL_PK_VALUE VARCHAR(30) NOT NULL,
        GUID VARCHAR(255) NOT NULL,
        COUNTER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_EXT_SYSTEM, Owner: SYSDBA */
CREATE TABLE OC_EXT_SYSTEM (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255) NOT NULL,
        IS_ACTIVE SMALLINT,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_GROUP_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_GROUP_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_GROUP_ROLE, Owner: SYSDBA */
CREATE TABLE OC_GROUP_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_HELP_BIN_OBJECT, Owner: SYSDBA */
CREATE TABLE OC_HELP_BIN_OBJECT (ID NUMERIC(18, 0) NOT NULL,
        BIN_CONTENT OID,
        MIME_TYPE VARCHAR(80),
        NAME VARCHAR(255),
        HELP_TOPIC VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_HELP_SECTION, Owner: SYSDBA */
CREATE TABLE OC_HELP_SECTION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(250),
PRIMARY KEY (CODE));

/* Table: OC_HELP_TOPIC, Owner: SYSDBA */
CREATE TABLE OC_HELP_TOPIC (CODE VARCHAR(255) NOT NULL,
        CONTENT_TEXT TEXT,
        LINK_URL VARCHAR(250),
        NAME VARCHAR(250) NOT NULL,
        SECTION VARCHAR(80) NOT NULL,
CONSTRAINT PK_OC_HELP_TOPIC PRIMARY KEY (CODE));

/* Table: OC_JBPM5EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255),
        PROCESS_KEY VARCHAR(255),
        LATEST SMALLINT,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
        LATEST_FOR_PROCESS_ID SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SEL_CRITERIA_CLASS VARCHAR(255),
        SEL_CRITERIA_EXPR VARCHAR(255),
        SEL_CRITERIA_PARAMS_EXPR VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        CONDITION VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
        VAR VARCHAR(255),
        VAR_POSITION NUMERIC(18, 0),
        HIDDEN SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_DEPLOYMENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_DEPLOYMENT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        DEPLOYMENT_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCEXT_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCEXT_RSRC (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        EXTENSION_VERSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROCIMG_RSRC, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROCIMG_RSRC (PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_KEY VARCHAR(255) NOT NULL,
        PROCESS_VERSION NUMERIC(18, 0) NOT NULL,
        ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_PROC_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_PROC_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        PROCESS_ID VARCHAR(255) NOT NULL,
        PROCESS_NAME VARCHAR(255),
        PROCESS_KEY VARCHAR(255) NOT NULL,
        LATEST SMALLINT,
        PROCESS_VERSION NUMERIC(18, 0) NOT NULL,
        DISABLED SMALLINT,
        PACKAGE_NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5REPO_RESOURCE, Owner: SYSDBA */
CREATE TABLE OC_JBPM5REPO_RESOURCE (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(1024) NOT NULL,
        RESOURCE_CONTENT OID NOT NULL,
        DEPLOYMENT NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_PROC_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_PROC_VAR (ID NUMERIC(18, 0) NOT NULL,
        BOOLEAN_VALUE SMALLINT,
        CONVERTER_TYPE_CODE VARCHAR(30),
        INTEGER_VALUE INTEGER,
        LONG_STRING_VALUE TEXT,
        LONG_VALUE NUMERIC(18, 0),
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        STRING_VALUE VARCHAR(255),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        PROC_INST_ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (PROC_INST_ID, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_SHORTLIVE_EVENT, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_SHORTLIVE_EVENT (ID NUMERIC(18, 0) NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        EVENT_TYPE VARCHAR(255) NOT NULL,
        TASK_ID NUMERIC(18, 0) NOT NULL,
        USER_ID VARCHAR(255),
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TASK_TX, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX (TASK_ID NUMERIC(18, 0) NOT NULL,
        TX_ID NUMERIC(18, 0) NOT NULL,
        WAS_OPENED SMALLINT NOT NULL,
PRIMARY KEY (TASK_ID, TX_ID));

/* Table: OC_JBPM5_TASK_TX_SEQGEN, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_TX_SEQGEN (TX_ID NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (TX_ID));

/* Table: OC_JBPM5_TASK_VAR, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_VAR (ID NUMERIC(18, 0) NOT NULL,
        OPT_LOCK NUMERIC(18, 0),
        STRING_VALUE VARCHAR(1024),
        VALUE_TYPE VARCHAR(255) NOT NULL,
        VARIABLE_NAME VARCHAR(255) NOT NULL,
        LONG_VALUE NUMERIC(18, 0),
        INTEGER_VALUE INTEGER,
        BOOLEAN_VALUE SMALLINT,
        PERSISTENT_VALUE_TYPE VARCHAR(255) NOT NULL,
        CONVERTER_TYPE_CODE VARCHAR(30),
        LONG_STRING_VALUE TEXT,
        TASK NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (TASK, VARIABLE_NAME));

/* Table: OC_JBPM5_TASK_WAS_OPENED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TASK_WAS_OPENED (ID NUMERIC(18, 0) NOT NULL,
        EVENT_TIMESTAMP TIMESTAMP NOT NULL,
        USER_ID VARCHAR(255),
        TASK NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO (ID NUMERIC(18, 0) NOT NULL,
        BYTEARRAYSIZE NUMERIC(18, 0),
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY OID,
PRIMARY KEY (ID));

/* Table: OC_JBPM5_TIMER_INFO_SEVED, Owner: SYSDBA */
CREATE TABLE OC_JBPM5_TIMER_INFO_SEVED (ID NUMERIC(18, 0) NOT NULL,
        BYTEARRAYSIZE NUMERIC(18, 0),
        CREATIONDATE TIMESTAMP,
        TIMERINFOBYTEARRAY OID);

/* Table: OC_JPDL4EXT_ATTRIBUTE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_ATTRIBUTE (ID NUMERIC(18, 0) NOT NULL,
        AVALUE VARCHAR(255),
        AKEY VARCHAR(255),
        SUBJECT_TYPE VARCHAR(255),
        SUBJECT_ID VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCDEF_EXTENSION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCDEF_EXTENSION (ID NUMERIC(18, 0) NOT NULL,
        RESOURCE_NAME VARCHAR(255),
        PROCESS_DEFINITION_KEY VARCHAR(255),
        PROCESS_DEFINITION_VERSION NUMERIC(18, 0),
        LATEST SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_PROCESS_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_PROCESS_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255),
        TYPE VARCHAR(255),
        DEFAULT_VALUE VARCHAR(255),
        CAPTION VARCHAR(255),
        EMBEDDED SMALLINT,
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        SHOW_IN_TASK_LIST SMALLINT,
        SELECTION_CRITERIA_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VALIDATION, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VALIDATION (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        ERROR_MESSAGE VARCHAR(255),
        CONDITION VARCHAR(255),
        VALIDATION_CLASS VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_JPDL4EXT_TASK_VARIABLE, Owner: SYSDBA */
CREATE TABLE OC_JPDL4EXT_TASK_VARIABLE (ID NUMERIC(18, 0) NOT NULL,
        TASK VARCHAR(255),
        REQUIRED SMALLINT,
        READONLY SMALLINT,
        ENTITY_HOME_MODE VARCHAR(255),
        EXTENSION NUMERIC(18, 0) NOT NULL,
        PROCESS_VARIABLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_MAIL_MSGTEMPLATE, Owner: SYSDBA */
CREATE TABLE OC_MAIL_MSGTEMPLATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TEMPLATE_TEXT TEXT NOT NULL,
PRIMARY KEY (CODE),
UNIQUE (NAME));

/* Table: OC_PAGE_TYPE, Owner: SYSDBA */
CREATE TABLE OC_PAGE_TYPE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: OC_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION_TARGET VARCHAR(255) NOT NULL,
        PERMISSION_ACTION VARCHAR(255) NOT NULL,
        PERMISSION_DESCRIPTION VARCHAR(1024),
        PERMISSION_CATEGORY NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_PERMISSION_CATEGORY, Owner: SYSDBA */
CREATE TABLE OC_PERMISSION_CATEGORY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY, Owner: SYSDBA */
CREATE TABLE OC_QUERY (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
        QUERY_TEXT TEXT,
        QUERY_TYPE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_QUERY_FIELD, Owner: SYSDBA */
CREATE TABLE OC_QUERY_FIELD (ID NUMERIC(18, 0) NOT NULL,
        FLD_LENGTH NUMERIC(18, 0),
        FIELD_NAME VARCHAR(255),
        POS NUMERIC(18, 0) NOT NULL,
        FIELD_TYPE VARCHAR(255) NOT NULL,
        EXPRESSION VARCHAR(1024),
        FIELD_DESCRIPTION VARCHAR(255),
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_PARAM, Owner: SYSDBA */
CREATE TABLE OC_QUERY_PARAM (ID NUMERIC(18, 0) NOT NULL,
        POS NUMERIC(18, 0) NOT NULL,
        REQUIRED SMALLINT,
        EXPRESSION VARCHAR(1024),
        PARAM_TYPE VARCHAR(255),
        CAPTION VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SELECTION_SOURCE VARCHAR(255),
        SELECTION_PROPERTY VARCHAR(255),
        MANUAL_INPUT SMALLINT,
        QUERY NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_QUERY_TYPE, Owner: SYSDBA */
CREATE TABLE OC_QUERY_TYPE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_DESC, Owner: SYSDBA */
CREATE TABLE OC_REPORT_DESC (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        ENTITY_CLASS VARCHAR(255),
        TEMPLATE_FILE_NAME VARCHAR(255),
        DEFAULT_OUTPUT_FORMAT VARCHAR(255),
        ENGINE NUMERIC(18, 0) NOT NULL,
        MASTER_QUERY NUMERIC(18, 0),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_REPORT_ENGINE, Owner: SYSDBA */
CREATE TABLE OC_REPORT_ENGINE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(80) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        COMPONENT_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_ROLE_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_ROLE_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_SCRIPT, Owner: SYSDBA */
CREATE TABLE OC_SCRIPT (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255),
        FULL_NAME VARCHAR(255),
        SCRIPT_TEXT TEXT,
        SCRIPT_POSITION NUMERIC(18, 0),
        SCRIPT_ACTIVE SMALLINT,
PRIMARY KEY (CODE));

/* Table: OC_SECURITY_GROUP, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_GROUP (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_SECURITY_ROLE, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_ROLE (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(30) NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME),
UNIQUE (CODE));

/* Table: OC_SECURITY_USER, Owner: SYSDBA */
CREATE TABLE OC_SECURITY_USER (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        USER_PASSWORD VARCHAR(80) NOT NULL,
        USER_LOGIN VARCHAR(30) NOT NULL,
        X509CERTIFICATE_COMMON_NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        USER_DISABLED SMALLINT,
PRIMARY KEY (ID));

/* Table: OC_TENANT, Owner: SYSDBA */
CREATE TABLE OC_TENANT (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        HOST_NAME VARCHAR(255),
PRIMARY KEY (ID),
UNIQUE (NAME));

/* Table: OC_TENANT_USER, Owner: SYSDBA */
CREATE TABLE OC_TENANT_USER (ID NUMERIC(18, 0) NOT NULL,
        TENANT NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_TYPED_PRINCIPAL_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_TYPED_PRINCIPAL_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PRINCIPAL_UUID VARCHAR(255),
        PERMISSION NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: OC_USERPROFILE_PARAM, Owner: SYSDBA */
CREATE TABLE OC_USERPROFILE_PARAM (ID NUMERIC(18, 0) NOT NULL,
        PARAM_VALUE VARCHAR(255),
        PARAM_NAME VARCHAR(255),
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GRANTED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_GRANTED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_GROUP, Owner: SYSDBA */
CREATE TABLE OC_USER_GROUP (ID NUMERIC(18, 0) NOT NULL,
        TENANT_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_GROUP NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_REVOKED_PERMISSION, Owner: SYSDBA */
CREATE TABLE OC_USER_REVOKED_PERMISSION (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        PERMISSION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_ROLE, Owner: SYSDBA */
CREATE TABLE OC_USER_ROLE (ID NUMERIC(18, 0) NOT NULL,
        SECURITY_USER NUMERIC(18, 0) NOT NULL,
        SECURITY_ROLE NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_USER_SETTING, Owner: SYSDBA */
CREATE TABLE OC_USER_SETTING (ID NUMERIC(18, 0) NOT NULL,
        CODE VARCHAR(250) NOT NULL,
        SETTING_VALUES TEXT,
        SETTING_USER NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: OC_ZERO_STATE, Owner: SYSDBA */
CREATE TABLE OC_ZERO_STATE (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        FILE_NAME VARCHAR(255) NOT NULL,
        APOSITION NUMERIC(18, 0) NOT NULL,
        SELECT_HQL VARCHAR(1024),
        PROCESS_COLLECTIONS SMALLINT,
        BEFORE_IMPORT TEXT,
        AFTER_IMPORT TEXT,
        PERSIST_REFERENCES SMALLINT,
PRIMARY KEY (CODE),
UNIQUE (APOSITION));

/* Table: PEOPLEASSIGNMENTS_BAS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_BAS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_EXCLOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_EXCLOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_POTOWNERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_POTOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_RECIPIENTS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_RECIPIENTS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: PEOPLEASSIGNMENTS_STAKEHOLDERS, Owner: SYSDBA */
CREATE TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: REASSIGNMENT_POTENTIALOWNERS, Owner: SYSDBA */
CREATE TABLE REASSIGNMENT_POTENTIALOWNERS (TASK_ID NUMERIC(18, 0) NOT NULL,
        ENTITY_ID VARCHAR(255) NOT NULL);

/* Table: RTM_ENTITY_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME_EXPRESSION VARCHAR(255),
        TO_STRING_EXPRESSION VARCHAR(255),
        QUICK_FILTER_EXPRESSION VARCHAR(255),
        DEFAULT_ORDER VARCHAR(255),
        PATH_EXPRESSION VARCHAR(255),
        DEFAULT_FOLDER VARCHAR(255),
        SUBENTITY_ONLY SMALLINT,
        RM_PROVIDER VARCHAR(50),
        TO_STRING_QUERY VARCHAR(1024),
        CUSTOM_LIST_COMPONENT VARCHAR(255),
        CUSTOM_HOME_COMPONENT VARCHAR(255),
        CUSTOM_ENTITY_FRAME VARCHAR(255),
        CUSTOM_LIST_FRAME VARCHAR(255),
        QUICK_SEARCH_FIELDS VARCHAR(1024),
PRIMARY KEY (CODE));

/* Table: RTM_ENTITY_FILTER, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FILTER (ID NUMERIC(18, 0) NOT NULL,
        FILTER_PROPERTY VARCHAR(80) NOT NULL,
        CAPTION VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        FILTER_JOIN_STRING VARCHAR(4000),
        FILTER_WHERE_STRING VARCHAR(4000),
        FILTER_PARAM_EXPRESSION VARCHAR(4000),
        FILTER_POS NUMERIC(18, 0),
        FILTER_VALUE_TYPE VARCHAR(80),
        FILTER_HANDLER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_FORM_PANEL, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_FORM_PANEL (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CAPTION VARCHAR(255),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        PANEL_POS NUMERIC(18, 0),
        PANEL_TYPE VARCHAR(80) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PARENT_PANEL NUMERIC(18, 0),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_OPERATION, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_OPERATION (ID NUMERIC(18, 0) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        CODE VARCHAR(255) NOT NULL,
        OPERATION_EXPRESSION VARCHAR(1024) NOT NULL,
        ENABLED_EXPRESSION VARCHAR(1024) NOT NULL,
        OPERATION_POS NUMERIC(18, 0) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        HIDE_NAME SMALLINT,
        OPERATION_DESCRIPTION VARCHAR(255),
        OPERATION_ICON VARCHAR(1024),
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        PROPERTY VARCHAR(30) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_ENTITY_VALIDATOR, Owner: SYSDBA */
CREATE TABLE RTM_ENTITY_VALIDATOR (ID NUMERIC(18, 0) NOT NULL,
        VALID_EXPRESSION VARCHAR(1024) NOT NULL,
        INVALID_MESSAGE VARCHAR(255) NOT NULL,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        CODE VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_DEFINITION (ID NUMERIC(18, 0) NOT NULL,
        FORMAT VARCHAR(255),
        FIELD_NAME VARCHAR(255),
        DEFAULT_EXPRESSION VARCHAR(255),
        CAPTION VARCHAR(255),
        DATA_LEN NUMERIC(18, 0),
        FIELD_POS NUMERIC(18, 0),
        IS_COLLECTION SMALLINT,
        CALC_EXPRESSION VARCHAR(1024),
        VISIBLE_EXPRESSION VARCHAR(255),
        WRITABLE_EXPRESSION VARCHAR(255),
        REQUIRED_EXPRESSION VARCHAR(255),
        SHOW_IN_LIST SMALLINT,
        ENTITY_DEFINITION VARCHAR(80) NOT NULL,
        DATA_TYPE VARCHAR(80) NOT NULL,
        ENTITY_PARENT_FIELD NUMERIC(18, 0),
        PANEL NUMERIC(18, 0),
        ENTITY_FILTER VARCHAR(1024),
        EMBEDDED_ENTITY SMALLINT,
        VISUALIZER VARCHAR(255),
        FIELD_HINT VARCHAR(1024),
        SERIALIZER VARCHAR(255),
PRIMARY KEY (ID));

/* Table: RTM_FIELD_PROPERTY_VALUE, Owner: SYSDBA */
CREATE TABLE RTM_FIELD_PROPERTY_VALUE (ID NUMERIC(18, 0) NOT NULL,
        PROPERTY_VALUE VARCHAR(255),
        PROPERTY VARCHAR(30) NOT NULL,
        FIELD_DEFINITION NUMERIC(18, 0) NOT NULL,
PRIMARY KEY (ID));

/* Table: RTM_MENU_ITEM, Owner: SYSDBA */
CREATE TABLE RTM_MENU_ITEM (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        WINDOW_NAME VARCHAR(255),
        ITEMPOSITION NUMERIC(18, 0),
        PARENT VARCHAR(30),
        PERMISSION_TARGET VARCHAR(255),
        PERMISSION_ACTION VARCHAR(255),
        EXTERNAL_LINK SMALLINT,
        TARGET_NAME VARCHAR(80),
PRIMARY KEY (CODE));

/* Table: RTM_MODEL_PROPERTY, Owner: SYSDBA */
CREATE TABLE RTM_MODEL_PROPERTY (CODE VARCHAR(30) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
PRIMARY KEY (CODE));

/* Table: RTM_TYPE_DEFINITION, Owner: SYSDBA */
CREATE TABLE RTM_TYPE_DEFINITION (CODE VARCHAR(80) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        TYPE_NAME VARCHAR(80) NOT NULL,
        SERIALIZER VARCHAR(255),
        VER NUMERIC(18, 0),
        INLINE SMALLINT,
        VISUALIZER VARCHAR(255),
PRIMARY KEY (CODE));

/* Table: TESTTABLE1, Owner: SYSDBA */
CREATE TABLE TESTTABLE1 (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: TMP_OLDTABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_OLDTABNUMS (USER_ID NUMERIC(18, 0),
        TABNO VARCHAR(255));

/* Table: TMP_SAVED_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_SAVED_UNIT_CODES (ID NUMERIC(18, 0),
        CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNO_UNIT_CODES, Owner: SYSDBA */
CREATE TABLE TMP_TABNO_UNIT_CODES (TAB_NO VARCHAR(80),
        UNIT_CODE VARCHAR(80));

/* Table: TMP_TABNUMS, Owner: SYSDBA */
CREATE TABLE TMP_TABNUMS (TABNO INTEGER,
        FIO VARCHAR(255),
        BE VARCHAR(255),
        BENAME VARCHAR(255),
        DEP1 VARCHAR(255),
        DEP1NAME VARCHAR(255),
        DEP2 VARCHAR(255),
        DEP2NAME VARCHAR(255),
        USERSFOUND NUMERIC(18, 0),
        USERID NUMERIC(18, 0),
        CNT INTEGER);

/* Table: TMP_USERS, Owner: SYSDBA */
CREATE TABLE TMP_USERS (LOGIN VARCHAR(80),
        PNAME VARCHAR(255),
        CNT INTEGER,
        UNITPATH VARCHAR(80));

/*  Index definitions for all user tables */
CREATE INDEX ERMS_EXTLINK_IDX1 ON ERMS_EXTLINK (ENTITY_ID);
CREATE INDEX ERMS_EXTLINK_IDX2 ON ERMS_EXTLINK (EXTERNAL_ID, EXTERNAL_TYPE, EXTERNAL_SYSTEM);
CREATE INDEX IX_ERMS_FILTERED_1 ON ERMS_FILTERED (ID);
CREATE INDEX IDX_ERMS_SVD_FLT1 ON ERMS_SAVED_FILTER (FOLDER_ID, USER_ID);
CREATE INDEX IX_1502550961 ON ERM_ADDRESSEEDOC (INTADDRESSEE);
CREATE INDEX IX_1557013804 ON ERM_ADDRESSEEDOC (INTRECIPIENT);
CREATE INDEX IX_280456214 ON ERM_ADDRESSEEDOC (ADDRESSEE);
CREATE INDEX IX_627480830 ON ERM_ADDRESSEEDOC (FOLDER_ID);
CREATE INDEX IX_933593987 ON ERM_ADDRESSEEDOC (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_946355886 ON ERM_ADDRESSEEDOC (DELIVERYKIND);
CREATE INDEX IX_1327325019 ON ERM_AGENTREQUEST (AGENTTYPE);
CREATE INDEX IX_470962719 ON ERM_AGENTREQUEST (RESULT);
CREATE INDEX IX_740039096 ON ERM_AGENTREQUEST (FOLDER_ID);
CREATE INDEX IX_776165632 ON ERM_AGENTREQUEST (USERREQUEST);
CREATE INDEX IX_836511649 ON ERM_AGENTTYPE (FOLDER_ID);
CREATE INDEX IX_1359437263 ON ERM_ASUDINTEGRATIONRULE (FOLDER_ID);
CREATE INDEX IX_1434184189 ON ERM_ASUDINTEGRATIONRULE (JBPMPROCESS);
CREATE INDEX IX_382339428 ON ERM_ASUDINTEGRATIONRULE (TASKTYPE);
CREATE INDEX IX_ERM_BIN_CONTENT_1 ON ERM_BIN_CONTENT (CONTENT_ID);
CREATE INDEX IX_179335045 ON ERM_BOARD (CHAIRMAN);
CREATE INDEX IX_2059412666 ON ERM_BOARD (FOLDER_ID);
CREATE INDEX IX_968489554 ON ERM_BOARD (SECRETARY);
CREATE INDEX IX_1434233610 ON ERM_CONTRAGENT (AGENTTYPE);
CREATE INDEX IX_793369571 ON ERM_CONTRAGENT (FOLDER_ID);
CREATE INDEX IX_175959942 ON ERM_DELEGATION (DELEGAT);
CREATE INDEX IX_2035929079 ON ERM_DELEGATION (PROCESS);
CREATE INDEX IX_2050319702 ON ERM_DELEGATION (USERTASK);
CREATE INDEX IX_217739847 ON ERM_DELEGATION (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_695444026 ON ERM_DELEGATION (FOLDER_ID);
CREATE INDEX IX_785643455 ON ERM_DELEGATION (EMPLOYER);
CREATE INDEX IX_977140122 ON ERM_DELIVERYKIND (FOLDER_ID);
CREATE INDEX IX_1112837780 ON ERM_DOCKIND (FOLDER_ID);
CREATE INDEX IX_DOCKIND_ANAME_UP ON ERM_DOCKIND (upper(ANAME));
CREATE INDEX IX_1315407009 ON ERM_DOCNUMBERING (FOLDER_ID);
CREATE INDEX IX_1667991067 ON ERM_DOCNUMBERING (DOCTYPE);
CREATE INDEX IX_1668274625 ON ERM_DOCNUMBERING (DOCKIND);
CREATE INDEX IX_2082059726 ON ERM_DOCNUMBERING (PERIOD);
CREATE INDEX IX_405784613 ON ERM_DOCNUMBERING (ORGUNIT);
CREATE INDEX IX_776768231 ON ERM_DOCNUMBERING (BOARD);
CREATE INDEX IX_1905858660 ON ERM_DOCNUMBERSEQ (FOLDER_ID);
CREATE INDEX IX_648187933 ON ERM_DOCNUMBERSEQ (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1652930845 ON ERM_DOCRELATED (DOC);
CREATE INDEX IX_2042022191 ON ERM_DOCRELATED (FOLDER_ID);
CREATE INDEX IX_27020130 ON ERM_DOCRELATED (SOURCEDOC);
CREATE INDEX IX_674157295 ON ERM_DOCRELATED (ANAME);
CREATE INDEX IX_959567186 ON ERM_DOCRELATED (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_19698186 ON ERM_DOCSTATUS (FOLDER_ID);
CREATE INDEX IX_1268833166 ON ERM_DOCTEMPLATE (ORGUNIT);
CREATE INDEX IX_1674509906 ON ERM_DOCTEMPLATE (FOLDER_ID);
CREATE INDEX IX_6343154 ON ERM_DOCTEMPLATE (DOCKIND);
CREATE INDEX IX_988802450 ON ERM_DOCTYPE (FOLDER_ID);
CREATE INDEX IX_DOCTYPE_ANAME_UP ON ERM_DOCTYPE (upper(ANAME));
CREATE INDEX IDX_ERM_DOCUMENT_REGDATE_DESC ON ERM_DOCUMENT (REGDATE DESC);
CREATE INDEX IX_1041875555 ON ERM_DOCUMENT (AGENTREQUEST);
CREATE INDEX IX_1153396438 ON ERM_DOCUMENT (NOMENCLATURE);
CREATE INDEX IX_1284957505 ON ERM_DOCUMENT (DOCTYPE);
CREATE INDEX IX_1285241063 ON ERM_DOCUMENT (DOCKIND);
CREATE INDEX IX_1366668485 ON ERM_DOCUMENT (DELIVERYKIND);
CREATE INDEX IX_1408570395 ON ERM_DOCUMENT (STATUS);
CREATE INDEX IX_1418556643 ON ERM_DOCUMENT (SIGNER);
CREATE INDEX IX_1707625913 ON ERM_DOCUMENT (FOLDER_ID);
CREATE INDEX IX_1897119339 ON ERM_DOCUMENT (BRANCH);
CREATE INDEX IX_1910780193 ON ERM_DOCUMENT (REGISTRATOR);
CREATE INDEX IX_1922417282 ON ERM_DOCUMENT (AUTHOR);
CREATE INDEX IX_29880608 ON ERM_DOCUMENT (INTCORRESPONDENT);
CREATE INDEX IX_526333403 ON ERM_DOCUMENT (SUPERVISOR);
CREATE INDEX IX_703159096 ON ERM_DOCUMENT (STORAGE);
CREATE INDEX IX_754023309 ON ERM_DOCUMENT (BOARD);
CREATE INDEX IX_755181422 ON ERM_DOCUMENT (AGENT);
CREATE INDEX IX_SUBJECT_UP ON ERM_DOCUMENT (upper(SUBJECT));
CREATE INDEX IX_1061779229 ON ERM_DOCUSER (FOLDER_ID);
CREATE INDEX IX_1612739834 ON ERM_DOCUSER (DOCUSER);
CREATE INDEX IX_246203236 ON ERM_DOCUSER (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1193365239 ON ERM_ENTITYEVENT (FOLDER_ID);
CREATE INDEX IX_698253744 ON ERM_ENTITYEVENT (EVENTUSER);
CREATE INDEX IX_806412664 ON ERM_ENTITYEVENT (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1899234194 ON ERM_EXECUTANTSTEMPLATE (TEMPLATELEVEL);
CREATE INDEX IX_1902533313 ON ERM_EXECUTANTSTEMPLATE (TEMPLATEOWNER);
CREATE INDEX IX_2111451892 ON ERM_EXECUTANTSTEMPLATE (FOLDER_ID);
CREATE INDEX IX_1256073159 ON ERM_EXECUTANTSTEMPLATEITEM (FOLDER_ID);
CREATE INDEX IX_362428910 ON ERM_EXECUTANTSTEMPLATEITEM (EXECUTANT);
CREATE INDEX IX_421665352 ON ERM_EXECUTANTSTEMPLATEITEM (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1155399215 ON ERM_FAVORITES (FAVORITE);
CREATE INDEX IX_1619767160 ON ERM_FAVORITES (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_855121143 ON ERM_FAVORITES (FOLDER_ID);
CREATE INDEX IX_1106939507 ON ERM_FILE (DOCUMENT);
CREATE INDEX IX_1591740200 ON ERM_FILE (FILETYPE);
CREATE INDEX IX_2006137366 ON ERM_FILE (USERREF);
CREATE INDEX IX_2113722149 ON ERM_FILE (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_371409830 ON ERM_FILE (FOLDER_ID);
CREATE INDEX IX_2136679020 ON ERM_FILETYPE (FOLDER_ID);
CREATE INDEX ERM_FOLDER_IDX1 ON ERM_FOLDER (LBORDER);
CREATE INDEX ERM_FOLDER_IDX2 ON ERM_FOLDER (RBORDER DESC);
CREATE INDEX IX_94870638 ON ERM_LINKTYPE (FOLDER_ID);
CREATE INDEX IX_143458758 ON ERM_LISTNUMBER (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_397161659 ON ERM_LISTNUMBER (FOLDER_ID);
CREATE INDEX IX_818601324 ON ERM_LISTNUMBER (DOCID);
CREATE INDEX IX_1640889288 ON ERM_NOMENCLATURE (PARENTNOMENCLATURE);
CREATE INDEX IX_1935086187 ON ERM_NOMENCLATURE (FOLDER_ID);
CREATE INDEX IX_375144559 ON ERM_NOMENCLATURE (ORGUNIT);
CREATE INDEX IX_661881878 ON ERM_NOMENCLATURE (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1002829575 ON ERM_NOTE (USERNOTE);
CREATE INDEX IX_516552841 ON ERM_NOTE (REPLYTO);
CREATE INDEX IX_848667824 ON ERM_NOTE (FOLDER_ID);
CREATE INDEX IX_97524689 ON ERM_NOTE (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1101022658 ON ERM_ORGTYPE (FOLDER_ID);
CREATE INDEX IX_1015036110 ON ERM_ORGUNIT (PARENTUNIT);
CREATE INDEX IX_1155212627 ON ERM_ORGUNIT (UNITPATH);
CREATE INDEX IX_123357062 ON ERM_ORGUNIT (ORGTYPE);
CREATE INDEX IX_1748458808 ON ERM_ORGUNIT (CFO);
CREATE INDEX IX_1915788297 ON ERM_ORGUNIT (MANAGER);
CREATE INDEX IX_467193848 ON ERM_ORGUNIT (FOLDER_ID);
CREATE INDEX IX_897810295 ON ERM_ORGUNIT (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_323005087 ON ERM_PERIOD (FOLDER_ID);
CREATE INDEX IX_1545409481 ON ERM_PERIODICTASK (PERIODTYPE);
CREATE INDEX IX_1624995327 ON ERM_PERIODICTASK (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_281204759 ON ERM_PERIODICTASK (DOCUMENT);
CREATE INDEX IX_543436418 ON ERM_PERIODICTASK (FOLDER_ID);
CREATE INDEX IX_576837593 ON ERM_PERIODICTASK (AUTHOR);
CREATE INDEX IX_875173088 ON ERM_PERIODICTASK (TASKOWNER);
CREATE INDEX IX_900091809 ON ERM_PERIODICTASK (EXECUTOR);
CREATE INDEX IDX_ERM_PERM1 ON ERM_PERM (FOLDER_ID, PERM_ACTION, PRINCIPAL_UID);
CREATE INDEX IX_1033676648 ON ERM_PFM (BE);
CREATE INDEX IX_108006249 ON ERM_PFM (FOLDER_ID);
CREATE INDEX IX_1529844867 ON ERM_PFM (PARENTUNIT);
CREATE INDEX IX_2005187407 ON ERM_PROCESS (FOLDER_ID);
CREATE INDEX IX_391403220 ON ERM_ROLE (FOLDER_ID);
CREATE INDEX IX_644444510 ON ERM_STAGE (FOLDER_ID);
CREATE INDEX ERM_TASK_IDX1 ON ERM_TASK (CREATEDATE DESC);
CREATE INDEX IX_1284804180 ON ERM_TASK (AUTHOR);
CREATE INDEX IX_1388734257 ON ERM_TASK (REFTASK);
CREATE INDEX IX_1398199375 ON ERM_TASK (SUPERVISOR);
CREATE INDEX IX_1469852580 ON ERM_TASK (DOCUMENT);
CREATE INDEX IX_1643818148 ON ERM_TASK (EXECUTOR);
CREATE INDEX IX_1798651067 ON ERM_TASK (STATUS);
CREATE INDEX IX_198956232 ON ERM_TASK (TASKTYPE);
CREATE INDEX IX_2095233757 ON ERM_TASK (FOLDER_ID);
CREATE INDEX IX_55292280 ON ERM_TASK (PARENTTASK);
CREATE INDEX IX_612209909 ON ERM_TASK (STAGE);
CREATE INDEX IX_781385636 ON ERM_TASK (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_1602617001 ON ERM_TASKDELEGATED (TASK);
CREATE INDEX IX_2127252091 ON ERM_TASKDELEGATED (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_44294662 ON ERM_TASKDELEGATED (FOLDER_ID);
CREATE INDEX IX_1413351408 ON ERM_TASKREPORT (DOCUMENT);
CREATE INDEX IX_1582054184 ON ERM_TASKREPORT (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_2133756306 ON ERM_TASKREPORT (NOTEUSER);
CREATE INDEX IX_448197207 ON ERM_TASKREPORT (FOLDER_ID);
CREATE INDEX IX_786732949 ON ERM_TASKSTATUS (FOLDER_ID);
CREATE INDEX IX_24238557 ON ERM_TASKTYPE (FOLDER_ID);
CREATE INDEX ERM_USER_IDX1 ON ERM_USER (USERREF);
CREATE INDEX IX_1449505509 ON ERM_USER (ORGUNIT);
CREATE INDEX IX_2091305578 ON ERM_USER (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_686446907 ON ERM_USER (PARENTORGUNIT);
CREATE INDEX IX_793027607 ON ERM_USER (FOLDER_ID);
CREATE INDEX IX_806163013 ON ERM_USER (ALLOWEDDOCSOFUNIT);
CREATE INDEX IX_91145379 ON ERM_USER (DELEGAT);
CREATE INDEX IX_1566225375 ON ERM_USERROLE (FOLDER_ID);
CREATE INDEX IX_1590437053 ON ERM_USERROLE (ROLE);
CREATE INDEX IX_687044192 ON ERM_USERROLE (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_7115151 ON ERM_USERTASK (PROCESS);
CREATE INDEX IX_712251729 ON ERM_USERTASK (ERM_OWNER, ERM_OWNER_TYPE);
CREATE INDEX IX_920411602 ON ERM_USERTASK (FOLDER_ID);
CREATE INDEX IDX_EVENTTYPES1 ON EVENTTYPES (ELEMENT);
CREATE INDEX IDX_DEPLPROP_DEPL ON JBPM4_DEPLOYPROP (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP1 ON JBPM4_DEPLOYPROP (OBJNAME_, KEY_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP2 ON JBPM4_DEPLOYPROP (STRINGVAL_);
CREATE INDEX IDX_JBPM4_DEPLOYPROP3 ON JBPM4_DEPLOYPROP (KEY_);
CREATE INDEX IDX_EXEC_INSTANCE ON JBPM4_EXECUTION (INSTANCE_);
CREATE INDEX IDX_EXEC_PARENT ON JBPM4_EXECUTION (PARENT_);
CREATE INDEX IDX_EXEC_SUBPI ON JBPM4_EXECUTION (SUBPROCINST_);
CREATE INDEX IDX_EXEC_SUPEREXEC ON JBPM4_EXECUTION (SUPEREXEC_);
CREATE INDEX IDX_JBPM4_EXECUTION1 ON JBPM4_EXECUTION (PROCDEFID_);
CREATE INDEX IDX_HACTI_HPROCI ON JBPM4_HIST_ACTINST (HPROCI_);
CREATE INDEX IDX_HTI_HTASK ON JBPM4_HIST_ACTINST (HTASK_);
CREATE INDEX IDX_HDET_HACTI ON JBPM4_HIST_DETAIL (HACTI_);
CREATE INDEX IDX_HDET_HPROCI ON JBPM4_HIST_DETAIL (HPROCI_);
CREATE INDEX IDX_HDET_HTASK ON JBPM4_HIST_DETAIL (HTASK_);
CREATE INDEX IDX_HDET_HVAR ON JBPM4_HIST_DETAIL (HVAR_);
CREATE INDEX IDX_JBPM4_HIST_PROCINST1 ON JBPM4_HIST_PROCINST (PROCDEFID_);
CREATE INDEX IDX_HSUPERT_SUB ON JBPM4_HIST_TASK (SUPERTASK_);
CREATE INDEX IDX_HVAR_HPROCI ON JBPM4_HIST_VAR (HPROCI_);
CREATE INDEX IDX_HVAR_HTASK ON JBPM4_HIST_VAR (HTASK_);
CREATE INDEX IDX_JBPM4_HIST_VAR_1 ON JBPM4_HIST_VAR (PROCINSTID_, VARNAME_, VALUE_);
CREATE INDEX IDX_GROUP_PARENT ON JBPM4_ID_GROUP (PARENT_);
CREATE INDEX IDX_MEM_GROUP ON JBPM4_ID_MEMBERSHIP (GROUP_);
CREATE INDEX IDX_MEM_USER ON JBPM4_ID_MEMBERSHIP (USER_);
CREATE INDEX IDX_JOBDUEDATE ON JBPM4_JOB (DUEDATE_);
CREATE INDEX IDX_JOBLOCKEXP ON JBPM4_JOB (LOCKEXPTIME_);
CREATE INDEX IDX_JOBRETRIES ON JBPM4_JOB (RETRIES_);
CREATE INDEX IDX_JOB_CFG ON JBPM4_JOB (CFG_);
CREATE INDEX IDX_JOB_EXE ON JBPM4_JOB (EXECUTION_);
CREATE INDEX IDX_JOB_PRINST ON JBPM4_JOB (PROCESSINSTANCE_);
CREATE INDEX IDX_LOB_DEPLOYMENT ON JBPM4_LOB (DEPLOYMENT_);
CREATE INDEX IDX_JBPM4_PARTICIPATION1 ON JBPM4_PARTICIPATION (TASK_, TYPE_, USERID_);
CREATE INDEX IDX_PART_TASK ON JBPM4_PARTICIPATION (TASK_);
CREATE INDEX IDX_SWIMLANE_EXEC ON JBPM4_SWIMLANE (EXECUTION_);
CREATE INDEX IDX_JBPM4_TASK1 ON JBPM4_TASK (ASSIGNEE_);
CREATE INDEX IDX_TASK_SUPERTASK ON JBPM4_TASK (SUPERTASK_);
CREATE INDEX IDX_JBPM4_VARIABLE1 ON JBPM4_VARIABLE (CLASS_, KEY_, STRING_VALUE_);
CREATE INDEX IDX_VAR_EXECUTION ON JBPM4_VARIABLE (EXECUTION_);
CREATE INDEX IDX_VAR_EXESYS ON JBPM4_VARIABLE (EXESYS_);
CREATE INDEX IDX_VAR_LOB ON JBPM4_VARIABLE (LOB_);
CREATE INDEX IDX_VAR_TASK ON JBPM4_VARIABLE (TASK_);
CREATE INDEX IDX_JBPM5_HT_TASK_PIID ON JBPM5_HT_TASK (PROCESSINSTANCEID);
CREATE INDEX IDX_JBPM5_HT_TASK_WIID ON JBPM5_HT_TASK (WORKITEMID);
CREATE INDEX IDX_OC_JBPM5EXT_PROCDEF_EXT1 ON OC_JBPM5EXT_PROCDEF_EXTENSION (PROCESS_ID);
CREATE INDEX IDX_OC_JBPM5_TSLE_EVENT ON OC_JBPM5_TASK_SHORTLIVE_EVENT (EVENT_TYPE);
CREATE INDEX IDX_OC_JBPM5_TSLE_TASK ON OC_JBPM5_TASK_SHORTLIVE_EVENT (TASK_ID);
CREATE INDEX IDX_OC_JBPM5_TSLE_TSTAMP ON OC_JBPM5_TASK_SHORTLIVE_EVENT (EVENT_TIMESTAMP);
CREATE INDEX IDX_OC_JBPM5_TSLE_USER ON OC_JBPM5_TASK_SHORTLIVE_EVENT (USER_ID);
CREATE INDEX OC_JBPM5_TASK_VAR_IDX1 ON OC_JBPM5_TASK_VAR (LONG_VALUE, TASK);
CREATE INDEX OC_JBPM5_TASK_VAR_IDX2 ON OC_JBPM5_TASK_VAR (STRING_VALUE, TASK);
CREATE INDEX IDX_OC_JBPM5_TWO_USER ON OC_JBPM5_TASK_WAS_OPENED (USER_ID);
CREATE INDEX IDX_OC_JPDL4EXT_PROCDEF_EXT1 ON OC_JPDL4EXT_PROCDEF_EXTENSION (PROCESS_DEFINITION_KEY, PROCESS_DEFINITION_VERSION);
CREATE INDEX IDX_OC_PERMISSION1 ON OC_PERMISSION (PERMISSION_TARGET, PERMISSION_ACTION);
CREATE INDEX TMP_TABNO_UNIT_IDX1 ON TMP_TABNO_UNIT (UNIT_CODE);
CREATE INDEX TMP_TABNUMS_IDX1 ON TMP_TABNUMS (FIO);
CREATE INDEX TMP_TABNUMS_IDX2 ON TMP_TABNUMS (USERID);

ALTER TABLE CFG_DEPENDENCY ADD CONSTRAINT FKB6719226DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DB901B50 FOREIGN KEY (RESOURCE_TYPE) REFERENCES CFG_RESOURCE_TYPE (ID);

ALTER TABLE CFG_RESOURCE ADD CONSTRAINT FK6B767DA9DBF6D041 FOREIGN KEY (ARTIFACT) REFERENCES CFG_ARTIFACT (ID);

ALTER TABLE CFG_RESOURCE_PARAM ADD CONSTRAINT FK7A56567745CA4CB9 FOREIGN KEY (RESOURCE) REFERENCES CFG_RESOURCE (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D572C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE DELEGATION_DELEGATES ADD CONSTRAINT FK47485D5736B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE EVENTTYPES ADD CONSTRAINT FKB0E5621F7665489A FOREIGN KEY (INSTANCEID) REFERENCES JBPM5_PROCINST_INFO (INSTANCEID);

ALTER TABLE JBPM4_DEPLOYPROP ADD CONSTRAINT FK_DEPLPROP_DEPL FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_INSTANCE FOREIGN KEY (INSTANCE_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUBPI FOREIGN KEY (SUBPROCINST_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_EXECUTION ADD CONSTRAINT FK_EXEC_SUPEREXEC FOREIGN KEY (SUPEREXEC_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HACTI_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_ACTINST ADD CONSTRAINT FK_HTI_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HACTI FOREIGN KEY (HACTI_) REFERENCES JBPM4_HIST_ACTINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_DETAIL ADD CONSTRAINT FK_HDETAIL_HVAR FOREIGN KEY (HVAR_) REFERENCES JBPM4_HIST_VAR (DBID_);

ALTER TABLE JBPM4_HIST_TASK ADD CONSTRAINT FK_HSUPERT_SUB FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HPROCI FOREIGN KEY (HPROCI_) REFERENCES JBPM4_HIST_PROCINST (DBID_);

ALTER TABLE JBPM4_HIST_VAR ADD CONSTRAINT FK_HVAR_HTASK FOREIGN KEY (HTASK_) REFERENCES JBPM4_HIST_TASK (DBID_);

ALTER TABLE JBPM4_ID_GROUP ADD CONSTRAINT FK_GROUP_PARENT FOREIGN KEY (PARENT_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_GROUP FOREIGN KEY (GROUP_) REFERENCES JBPM4_ID_GROUP (DBID_);

ALTER TABLE JBPM4_ID_MEMBERSHIP ADD CONSTRAINT FK_MEM_USER FOREIGN KEY (USER_) REFERENCES JBPM4_ID_USER (DBID_);

ALTER TABLE JBPM4_JOB ADD CONSTRAINT FK_JOB_CFG FOREIGN KEY (CFG_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_LOB ADD CONSTRAINT FK_LOB_DEPLOYMENT FOREIGN KEY (DEPLOYMENT_) REFERENCES JBPM4_DEPLOYMENT (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_SWIMLANE FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_PARTICIPATION ADD CONSTRAINT FK_PART_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_SWIMLANE ADD CONSTRAINT FK_SWIMLANE_EXEC FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SUPERTASK FOREIGN KEY (SUPERTASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM4_TASK ADD CONSTRAINT FK_TASK_SWIML FOREIGN KEY (SWIMLANE_) REFERENCES JBPM4_SWIMLANE (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXECUTION FOREIGN KEY (EXECUTION_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_EXESYS FOREIGN KEY (EXESYS_) REFERENCES JBPM4_EXECUTION (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_LOB FOREIGN KEY (LOB_) REFERENCES JBPM4_LOB (DBID_);

ALTER TABLE JBPM4_VARIABLE ADD CONSTRAINT FK_VAR_TASK FOREIGN KEY (TASK_) REFERENCES JBPM4_TASK (DBID_);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD78EF5F064 FOREIGN KEY (ATTACHEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_ATTACHMENT ADD CONSTRAINT FK1E702DD7F21826D9 FOREIGN KEY (TASKDATA_ATTACHMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_BOOL_EXPR ADD CONSTRAINT FK3690AAF6AFB75F7D FOREIGN KEY (ESCALATION_CONSTRAINTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0B2FF04688 FOREIGN KEY (ADDEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_COMMENT ADD CONSTRAINT FKD5366E0BB35E68F5 FOREIGN KEY (TASKDATA_COMMENTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C27ABEB8A FOREIGN KEY (DEADLINES_ENDDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_DEADLINE ADD CONSTRAINT FK1384500C684BACA3 FOREIGN KEY (DEADLINES_STARTDEADLINE_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_ESCALATION ADD CONSTRAINT FK8459BF49C7A04C70 FOREIGN KEY (DEADLINE_ESCALATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A2162DFB4 FOREIGN KEY (NOTIFICATION_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A3330F6D9 FOREIGN KEY (DEADLINE_DOCUMENTATION_ID) REFERENCES JBPM5_HT_DEADLINE (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A5EEBB6D9 FOREIGN KEY (REASSIGNMENT_DOCUMENTATION_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A69B21EE8 FOREIGN KEY (TASK_DESCRIPTIONS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A8046A239 FOREIGN KEY (NOTIFICATION_DOCUMENTATION_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7A98B62B FOREIGN KEY (TASK_NAMES_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AB2FA6B18 FOREIGN KEY (TASK_SUBJECTS_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AD488CEEB FOREIGN KEY (NOTIFICATION_NAMES_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_I18N_TEXT ADD CONSTRAINT FK5ACD5B7AF952CEE4 FOREIGN KEY (NOTIFICATION_SUBJECTS_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_N10N ADD CONSTRAINT FKA36CB2B53E0890B FOREIGN KEY (ESCALATION_NOTIFICATIONS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A91F7B912A FOREIGN KEY (EMAILHEADERS_ID) REFERENCES JBPM5_HT_MAILNHDR (ID);

ALTER TABLE JBPM5_HT_N10N_JBPM5_HT_MAILNHDR ADD CONSTRAINT FKE8EC94A98EE05A12 FOREIGN KEY (JBPM5_HT_N10N_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE JBPM5_HT_REASSIGNMENT ADD CONSTRAINT FK11824F4A5C17EE0 FOREIGN KEY (ESCALATION_REASSIGNMENTS_ID) REFERENCES JBPM5_HT_ESCALATION (ID);

ALTER TABLE JBPM5_HT_SUBTASK_STRATEGY ADD CONSTRAINT FK8C53C08136B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD396CE1EF3A FOREIGN KEY (ACTUALOWNER_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD399E619A0 FOREIGN KEY (CREATEDBY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JBPM5_HT_TASK ADD CONSTRAINT FKA36FAD39F213F8B5 FOREIGN KEY (TASKINITIATOR_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE JB_JOB_TYPE_PARAM ADD CONSTRAINT FKB413F6F165EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB ADD CONSTRAINT FK9447C66465EF8208 FOREIGN KEY (JOB_TYPE) REFERENCES JB_JOB_TYPE (CODE);

ALTER TABLE JB_SCHEDULED_JOB_PARAM ADD CONSTRAINT FK673EE6F2D83EF726 FOREIGN KEY (SCHEDULED_JOB) REFERENCES JB_SCHEDULED_JOB (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1D46DC060 FOREIGN KEY (USER_TO) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE MSG_USER_MESSAGE ADD CONSTRAINT FKB6001BB1F1695C8F FOREIGN KEY (USER_FROM) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE02C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_BAS ADD CONSTRAINT FK2DD68EE09C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE NOTIFICATION_RECIPIENTS ADD CONSTRAINT FK98FD214E9C76EABA FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_N10N (ID);

ALTER TABLE OC_COMMON_USER ADD CONSTRAINT FK940943B41BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_CUSTOM_PAGE ADD CONSTRAINT FK9CCD5CB24CB60E09 FOREIGN KEY (PAGE_TYPE) REFERENCES OC_PAGE_TYPE (CODE);

ALTER TABLE OC_EXT_ENT2ENT_FLD_EXPR ADD CONSTRAINT FK51B13C1ACA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY ADD CONSTRAINT FKEC84FB0CF0ECEDE4 FOREIGN KEY (EXTERNAL_SYSTEM) REFERENCES OC_EXT_SYSTEM (ID);

ALTER TABLE OC_EXT_ENTITY2ENTITY ADD CONSTRAINT FK641E3609BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607B027AA58 FOREIGN KEY (EXTERNAL_ENTITY_REFERENCE) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENTITY_FIELD ADD CONSTRAINT FK58528607BFEFD14C FOREIGN KEY (EXTERNAL_ENTITY) REFERENCES OC_EXT_ENTITY (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836D2DDA4D17 FOREIGN KEY (EXTERNAL_ENTITY_FIELD) REFERENCES OC_EXT_ENTITY_FIELD (ID);

ALTER TABLE OC_EXT_ENT_FLD2FLD ADD CONSTRAINT FKA6E1836DCA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_EXT_ENT_ID2ID ADD CONSTRAINT FKF5665DB5CA3C3A7E FOREIGN KEY (EXTERNAL_ENTITY2ENTITY) REFERENCES OC_EXT_ENTITY2ENTITY (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69A12F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_PERMISSION ADD CONSTRAINT FK5682A69AFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D1958112F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_GROUP_ROLE ADD CONSTRAINT FKF1D19581F1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_HELP_BIN_OBJECT ADD CONSTRAINT FK58F51CCAE3A167FF FOREIGN KEY (HELP_TOPIC) REFERENCES OC_HELP_TOPIC (CODE);

ALTER TABLE OC_HELP_TOPIC ADD CONSTRAINT FK2A2E5FC9BB44229 FOREIGN KEY (SECTION) REFERENCES OC_HELP_SECTION (CODE);

ALTER TABLE OC_JBPM5EXT_ATTRIBUTE ADD CONSTRAINT FK2B5A04A93572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_PROCESS_VARIABLE ADD CONSTRAINT FKE07A5F9F3572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VALIDATION ADD CONSTRAINT FKFC6F0FC03572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833572E39B FOREIGN KEY (EXTENSION) REFERENCES OC_JBPM5EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JBPM5EXT_TASK_VARIABLE ADD CONSTRAINT FK3C93BF833EAF2F98 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JBPM5EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JBPM5REPO_PROCEXT_RSRC ADD CONSTRAINT FK9B6B8DBEE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_PROCIMG_RSRC ADD CONSTRAINT FKDEDCB55CE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_PROC_RESOURCE ADD CONSTRAINT FKF19E98FFE8DB4E92 FOREIGN KEY (ID) REFERENCES OC_JBPM5REPO_RESOURCE (ID);

ALTER TABLE OC_JBPM5REPO_RESOURCE ADD CONSTRAINT FK971FA4E6567B3CB3 FOREIGN KEY (DEPLOYMENT) REFERENCES OC_JBPM5REPO_DEPLOYMENT (ID);

ALTER TABLE OC_JBPM5_TASK_VAR ADD CONSTRAINT FKA4BF6AF7928994C4 FOREIGN KEY (TASK) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE OC_JBPM5_TASK_WAS_OPENED ADD CONSTRAINT FK8E9604AF928994C4 FOREIGN KEY (TASK) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE OC_JPDL4EXT_ATTRIBUTE ADD CONSTRAINT FKC6148E6350B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_PROCESS_VARIABLE ADD CONSTRAINT FK9B1E50A550B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VALIDATION ADD CONSTRAINT FKC8A5E5FA50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D27F42577 FOREIGN KEY (PROCESS_VARIABLE) REFERENCES OC_JPDL4EXT_PROCESS_VARIABLE (ID);

ALTER TABLE OC_JPDL4EXT_TASK_VARIABLE ADD CONSTRAINT FK7F1EDC3D50B1DC5C FOREIGN KEY (EXTENSION) REFERENCES OC_JPDL4EXT_PROCDEF_EXTENSION (ID);

ALTER TABLE OC_PERMISSION ADD CONSTRAINT FK8686E11AF1EBAB7 FOREIGN KEY (PERMISSION_CATEGORY) REFERENCES OC_PERMISSION_CATEGORY (ID);

ALTER TABLE OC_QUERY ADD CONSTRAINT FK2836DA9D59C34F46 FOREIGN KEY (QUERY_TYPE) REFERENCES OC_QUERY_TYPE (ID);

ALTER TABLE OC_QUERY_FIELD ADD CONSTRAINT FKCF48B4D86A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_QUERY_PARAM ADD CONSTRAINT FKCFD22C6B6A306B14 FOREIGN KEY (QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D133F526F7 FOREIGN KEY (MASTER_QUERY) REFERENCES OC_QUERY (ID);

ALTER TABLE OC_REPORT_DESC ADD CONSTRAINT FKF808D0D1A985BF25 FOREIGN KEY (ENGINE) REFERENCES OC_REPORT_ENGINE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_ROLE_PERMISSION ADD CONSTRAINT FKDF5410CDFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_SECURITY_GROUP ADD CONSTRAINT FK77A5DE8BDBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E4551BC91B42 FOREIGN KEY (ID) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_TENANT_USER ADD CONSTRAINT FK7767E455DBF64306 FOREIGN KEY (TENANT) REFERENCES OC_TENANT (ID);

ALTER TABLE OC_TYPED_PRINCIPAL_PERMISSION ADD CONSTRAINT FK3DA89080FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USERPROFILE_PARAM ADD CONSTRAINT FKF9E5E2E1F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_GRANTED_PERMISSION ADD CONSTRAINT FKE45C815CFEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C5612F63D03 FOREIGN KEY (SECURITY_GROUP) REFERENCES OC_SECURITY_GROUP (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C564DD86731 FOREIGN KEY (TENANT_USER) REFERENCES OC_TENANT_USER (ID);

ALTER TABLE OC_USER_GROUP ADD CONSTRAINT FK180A1C568C6EA467 FOREIGN KEY (TENANT_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999F1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_REVOKED_PERMISSION ADD CONSTRAINT FK28077999FEF978FA FOREIGN KEY (PERMISSION) REFERENCES OC_PERMISSION (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1CDECE7 FOREIGN KEY (SECURITY_ROLE) REFERENCES OC_SECURITY_ROLE (ID);

ALTER TABLE OC_USER_ROLE ADD CONSTRAINT FKA5F4C3BFF1D0C391 FOREIGN KEY (SECURITY_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE OC_USER_SETTING ADD CONSTRAINT FKA2D61A673A981681 FOREIGN KEY (SETTING_USER) REFERENCES OC_SECURITY_USER (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_BAS ADD CONSTRAINT FK9D8CF4EC36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E42C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_EXCLOWNERS ADD CONSTRAINT FKC77B97E436B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_POTOWNERS ADD CONSTRAINT FK1EE418D36B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C22C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_RECIPIENTS ADD CONSTRAINT FKC6F615C236B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D52C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE PEOPLEASSIGNMENTS_STAKEHOLDERS ADD CONSTRAINT FK482F79D536B2F154 FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_TASK (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFF2C122ED2 FOREIGN KEY (ENTITY_ID) REFERENCES JBPM5_HT_ORG_ENTITY (ID);

ALTER TABLE REASSIGNMENT_POTENTIALOWNERS ADD CONSTRAINT FK90B59CFFE17E130F FOREIGN KEY (TASK_ID) REFERENCES JBPM5_HT_REASSIGNMENT (ID);

ALTER TABLE RTM_ENTITY_DEFINITION ADD CONSTRAINT FKAE4EB63BED0054E FOREIGN KEY (CODE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK6243006039AA7BD0 FOREIGN KEY (FILTER_VALUE_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FILTER ADD CONSTRAINT FK62430060F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B170CE9EC6 FOREIGN KEY (PARENT_PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_ENTITY_FORM_PANEL ADD CONSTRAINT FKFA7657B1F61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_OPERATION ADD CONSTRAINT FK6AAD977FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_ENTITY_PROPERTY_VALUE ADD CONSTRAINT FKBD572B6FF919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_ENTITY_VALIDATOR ADD CONSTRAINT FKC56CCD6AF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C2389DA9B FOREIGN KEY (PANEL) REFERENCES RTM_ENTITY_FORM_PANEL (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2C238C53A FOREIGN KEY (ENTITY_PARENT_FIELD) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF61C1AF9 FOREIGN KEY (ENTITY_DEFINITION) REFERENCES RTM_ENTITY_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_DEFINITION ADD CONSTRAINT FK39598D2CF8F8EA10 FOREIGN KEY (DATA_TYPE) REFERENCES RTM_TYPE_DEFINITION (CODE);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E083419AF1 FOREIGN KEY (FIELD_DEFINITION) REFERENCES RTM_FIELD_DEFINITION (ID);

ALTER TABLE RTM_FIELD_PROPERTY_VALUE ADD CONSTRAINT FK884B21E0F919343F FOREIGN KEY (PROPERTY) REFERENCES RTM_MODEL_PROPERTY (CODE);

ALTER TABLE RTM_MENU_ITEM ADD CONSTRAINT FK147B8FFC08A43F7 FOREIGN KEY (PARENT) REFERENCES RTM_MENU_ITEM (CODE);
